haraka/Haraka

docs/Outbound.md, outbound.js
This is to address issue #682
FYI: I tried to come up with a way to ensure that a message was delivered over the same IP addresses that it was received on, but it does not seem to be possible due to the way that the connection local_ip is reported by the kernel.  e.g. if you bind the listening socket to :: or 0.0.0.0 then that is what it returned as the local IP address.
=> Allow plugins to set outbound IP

tests/transaction.js, transaction.js
Previously, if you called Transaction.attachment_hooks before Transaction.set_banner or .add_body_filter, your banner or filter wouldn't be applied because the body had already been created inside attachment_hooks.  This delays creating the body until it's actually going to be used, so all of these methods can be called in any order and still take effect.
I also snuck in a test for my last pull request (#739), which added Transaction.add_body_filter but no test on it.
=> Fix Txn.attachment_hooks to defer body creation like similar methods

plugins/connect.asn.js, plugins/connect.geoip.js
* asn: permit asn plugin to have 0 providers
* asn: only register lookup_rdns hook if a provider is available
* geoip: emit log entry of ASN results, when found
* geoip: moved ASN lookup into it's own function
The net change is that the geoip plugin now emits a log entry like this:
````
[connect.geoip] asn: 53264, org: Continuum Data Centers, LLC.
````
=> GeoIP & ASN

mailbody.js, tests/mailbody.js
Currently, if you add Body filters (e.g. with Transaction.add_body_filter or indirectly with .set_banner), messages that contain a MIME multi-part preamble (often "This is a multi-part message in MIME format.") will be enqueued with that preamble repeated at the very end of the message, after the terminating boundary line.  This adds a test to catch the error and fixes it by not capturing the body text for multi-part containers.  It doesn't seem useful to capture that text anyway--it's not a text part for one, and we already don't capture the "text" of attachments.
The reason this fixes the issue is that when Body.parse_end is called, the body text for each body part is added to the returned "line" before filters are applied.  With no body text for containers, there's nothing to …
=> Prevent duplication of multi-part preamble text

config/rabbitmq_amqplib.ini, docs/plugins/queue/rabbitmq.md, docs/plugins/queue/rabbitmq_amqplib.md, plugins/queue/rabbitmq.js, plugins/queue/rabbitmq_amqplib.js
The first commit is for the plugin `queue/rabbitmq` that depends of `amqp` package. I added settings to specify user and password for the connection with RabbitMQ.
The second commit is a new plugin similar to `queue/rabbitmq` but depends of `amqplib` package. I wrote this plugin for people who want to use the package `amqplib` not to replace the default plugin for RabbitMQ.
=> Added plugin for RabbitMQ using amqplib, and added support for user and password to queue/rabbitmq

outbound.js, tests/outbound.js
this is an alternative to PR #767 
And it includes a handy little test that validates that it does what it's supposed to. Thanks to @chazomaticus for suggesting this regexp.
````
$ ./run_tests tests/outbound.js 
Running tests:  [ 'tests/outbound.js' ]
outbound.js
✔ outbound - converts \n and \r\n line endings to \r\n
OK: 2 assertions (3ms)
````
=> only replace line ending if not \r\n

plugins.js
Helps plugin developers organize their development/testing environment how they'd like it set up. Provides power for hosted platforms as well to install as NPM but put plugin directory somewhere else.
=> Added environment definable plugin directories using semi-colon ';' delim

logger.js
The current method of adding a log timestamp results in the startup time of
Haraka being added to every log message, which isn't ideal. Use a proxy function
which uses a new Date for every log message written to the console.
=> fix adding timestamps to log messages

docs/Net_Utils.md, net_utils.js, plugins/auth/flat_file.js, plugins/connect.asn.js, plugins/connect.fcrdns.js, plugins/connect.geoip.js, plugins/data.uribl.js, plugins/dnsbl.js, plugins/helo.checks.js, plugins/messagesniffer.js, plugins/spf.js, tests/net_utils.js
* rename net_utils.is_rfc1918 -> is_private_ip
* closes #850
* added net_utils.is_local_ipv4, is_private_ipv4, & is_local_ipv6.
* updated is_private_ip to use them
* adds IPv6 link local to is_private_ip
* adds additional test coverage
* considerably easier to maintain than one regex for ipv4 and one for ipv6
* no significant performance impact (0.05 second difference on 2 million iterations)
* side note: using ?: in /regex/.test(str) seems to make no performance different (less than rounding error in testing).
=> net_utils: refactoring for IPv6 compatibility, simplicity and maintainability

docs/plugins/queue/smtp_forward.md, docs/plugins/queue/smtp_proxy.md, smtp_client.js
=> Fix SMTP AUTH in smtp_forward/proxy and add docs

address.js
fixes 'Invalid domain in address' error parsing domains which contain underscores.  Underscores in domain name do not break spec and are often used.
=> allow domains with underscore

tests/spf.js
````
$ ./run_tests tests/spf.js 
Running tests:  [ 'tests/spf.js' ]
spf.js
✔ SPF - new SPF
✔ SPF - constants
✔ SPF - mod_redirect, true
✔ SPF - mod_redirect, false
OK: 13 assertions (121ms)
````
````
$ ./run_tests tests/spf.js  2>&1 | wc -l
273
````
=> tests/spf: quiet excessive DEBUG noise

package.json, plugins/log.syslog.js
which works under node 0.12.
strong-fork-syslog is a fork of schamana/node-syslog, [who is npm-AWOL](https://github.com/schamane/node-syslog/pull/33), so the **other** project maintainers who are responsiive have published under the fork name, until such a time as schamane either a) permits someone else to publish to npm or b) does it himself. (it's been many months and releases and neither has happened).
=> log.syslog: try loading strong-fork-syslog

docs/Outbound.md, docs/Plugins.md, outbound.js
Requires the use of the get_mx hook to return an MX object that supplies `auth_user` and `auth_pass` properties.
Also adds an auth=[Y|N] to the outbound delivery line to show if AUTH was used:
````
[NOTICE] [5E910B8A-C52B-46E9-8EB0-8B88FCE139FF.1.1] [outbound] delivered file=1426782311656_0_25646_3451.mail1-ec2.fsl.com domain="tnpi.net" host="mail.theartfarm.com" ip=66.128.51.165 port=25 mode=SMTP tls=Y auth=Y response="ok 1426782313 qp 36423 (995AD5EE-DC67-4E4A-88BB-A2CE2075960F.1)" delay=2.205 fails=0 rcpts=1/0/0
````
=> Add AUTH support to outbound

docs/plugins/toobusy.md, plugins/toobusy.js
The toobusy plugin by llyod seems to be dead. A newly maintained fork has been created and can be found here:
https://github.com/STRML/node-toobusy
I'm recommending upgrading to this current fork. There doesn't seem to be any breaking changes, and this fork makes a good drop in replacement. I've updated the core plugin and docs. I suggest another point release to 2.6.2 since this is a breaking change for the latest node stable version.
=> toobusy plugin compatibility issues with Nodejs 0.12

dkim.js
Uncovered thanks to the Washington Post incorrectly publishing a TXT record instead of a CNAME:
`````
[smf@mail1-ec2 Haraka]$ host -t TXT sailthru._domainkey.e.washingtonpost.com
sailthru._domainkey.e.washingtonpost.com descriptive text "e.washingtonpost.com.sailthrudkim.com"
`````
=> Fix timeout issue in dkim_verify

configfile.js, tests/config.js, tests/config/test.ini, tests/configfile.js, tests/plugins/karma.js
(such as auth/auth_*)
for @celesteking
This rule should have worked for you:
````
results.auth/auth_base.fail      = -4  if length gt 0
````
However, Haraka's custom ini parser didn't permit it to work because of the forward slash:
````
[ERROR] [-] [core] Invalid line in config file 'karma.ini': results.auth/auth_base.fail = -4  if length gt 0
````
So attached is also a commit which adds the '/' char to the permitted list.
=> karma: add rule tests for plugins with / in name

plugins/data.uribl.js, utils.js
This is important in cases where there are a lot of URIs within a message to ensure that a random sample it looked up to the maximum query limit of each list.
=> Add Fisher-Yates shuffle to randomize lookup order in data.uribl

plugins/connect.fcrdns.js
Make it easier for other plugins to consume results by making sure fcrdns results are always initialized.
=> fcrdns: always init results

.gitignore, TODO, config/graph.ini, config/http.ini, http/Gruntfile.js, http/bower.json, http/html/index.html, http/package.json, plugins/graph.js, server.js
* server: add http child listeners
* server: only load http if configured
* http.ini: new config file
* updated plugins/graph for new HTTP server
* warn if http enabled but can't load express or ws
* add config/bower.json, Gruntfile, package.json
* allows multiple plugins to serve on the same HTTP(S) port
* provides an index/landing page
* closes #433 
* the basis for facilities to manage the outbound queue (@baudehlo in #443)
* ~~the html/* directory is not included. Yet.~~ (installed with bower)
* ~~how to install web dependencies and avoid test failures re: them? (optionalDeps isn't ideal)~~ (bower)
* ~~docroot handling for haraka and per-plugin~~ (each plugin registers a route)
* populate plugin tabs dynamically (based on plugins that register routes)
* auth via any SMTP-AUTH provider …
=> add HTTP support

plugins/limit.js, tests/plugins/limit.js
Remember issue #947 where plugins that do anything other than next(CONT) at lookup_rdns cause me issues? This still increments the concurrency at lookup_rdns but waits until hook_connect to DENY.
=> limit: concurrent reject at connect (not rdns)

.travis.yml, Gruntfile.js, package.json
Our first grunt task:
```js
[matt@imac27] ~/Documents/git/haraka $ grunt versioncheck
Running "versioncheck" task
>> nopt (npm) is out of date. Your version: ~2.1.2 latest: 3.0.1
>> generic-pool (npm) is out of date. Your version: ~2.0.2 latest: 2.2.0
>> iconv (npm) is up to date.
>> ipaddr.js (npm) is out of date. Your version: ~0.1.2 latest: 1.0.1
>> async (npm) is out of date. Your version: ~0.2.9 latest: 0.9.0
>> daemon (npm) is up to date.
>> npid (npm) is up to date.
>> address-rfc2822 (npm) is up to date.
>> js-yaml (npm) is out of date. Your version: ~3.2.3 latest: 3.3.0
>> jscoverage (npm) is up to date.
>> coveralls (npm) is up to date.
>> grunt (npm) is up to date.
>> grunt-contrib-clean (npm) is up to date.
>> grunt-contrib-jshint (npm) is up to date.
>> grunt-version-check …
```
=> add Gruntfile.js

tls_socket.js
I had a deprecation message when haraka start about createCredentials that told me to use the tls function instead.
Here is the doc: https://nodejs.org/api/crypto.html#crypto_crypto_createcredentials_details
It shows that it is the same options as well but i'm not sure about the bug mentioned in the file comment and how to exactly test it so if someone want me to make some more test with something specific let me know
=> Changing createCredentials to tls.createSecureContext

docs/plugins/avg.md, plugins/avg.js
* use path.join to assemble tmpfile (Windows friendly)
* move config loading into register()
* save results in result_store
* added two config file options
* [defer]error=false
* [defer]timeout=false
The motivation for the [defer] options is being able to test deploy this plugin in a safe manner. When there's an AVG engine/connection/network error, I don't want it to block all mail. The default behavior is still to defer on error/timeout, unless the config file options are set.
=> avg: result_store, defer options

plugins/early_talker.js
Part of this PR is a question: Why would you put that line `if (!connection.early_talker) { return next(); }` inside the setTimeout?  It looks to me like a non-optimization.
This also adds a log message when a relaying client trips over the early_talker plugin. Yes, I've seen it happen 3 times now, so I'm sure it's happening more often. Just not quite sure how often.
=> earlytalker: store results when relayclient talks early

config/rspamd.ini, docs/plugins/rspamd.md, plugins/rspamd.js
as connection properties are much more likely to exist.
* if no fcrdns plugin, get hostname from connection.remote_host
* get helo from connection.remote_host (vs helo.checks, same data)
* convert rcpt_to objects to email addresses
* set Deliver-To for single-recipient transactions
* add scan timer
* include urls, emails, and messages which might be present in rspamd reply (edit
config/results.ini to control which are logged)
* correct port comment in rspamd.ini
* added option to skip reject for authenticated users
* added option to skip scanning for authenticated users
=> rspamd: use connection properties vs plugin data

plugins/auth/auth_base.js
i had to distinguish between different reason on why the login was denied from my plugin. As smf suggested on irc, i added a message variable when i return the boolean for exemple: 
exports.check_plain_passwd = function (connection, user, passwd, cb) {
if (user === 'me' && passwd === 'imAnoob') {
return cb(true, 'you are logged');
}
return cb(false, 'get lost');
}
If no message is provided the default message will be shown
=> Add optional return message to auth_base

plugins/queue/smtp_forward.js
adds this bit of data to the ES results:
```json
"queue/smtp_forward": {
"pass": [
"2.6.0 <03B521FEF618B64588A9F1AB6FCD34D0020F4347A3C2@IIG-EXCHANGE.********.com> [InternalId=14493] Queued mail for delivery"
]
}
```
=> smtp_forward: save to result_store

connection.js, logger.js
* make queue attempt failures visible to watch and elasticsearch plugins via result_store.
* store queue result in transaction.results, providing more insight into what happened when queue attempts != 'ok'
=> connection: save queue results to result_store

docs/Results.md, result_store.js
doesn't show up in human or human_html output (by default)
This is already possible by adding hide= config settings in results.ini, this
establishes a convention for doing it by default for the underscore pattern.
=> permit result_store consumers to store data that

result_store.js, tests/result_store.js
when adding results to a pre-defined result array (pass, fail, msg, err,
skip), if the result is itself an array, extend the result array with the
contents.
IE, the result ends up as this:
[ 'result1', 'result2', 'result3' ]
instead of
[ 'result1', [ 'result2', 'result3' ]]
=> result_store: extend arrays instead of nesting

config/karma.ini, docs/plugins/karma.md, plugins/karma.js, tests/plugins/karma.js
* removed unused ipaddr.js
* rename connect to score (easier to understand what it is)
* in addition to computed history (good - bad), report good and bad
* be less verbose by default (when loglevel=info)
* don't tarpit quit (rarely works anyway)
* removed early_talker check
* added all_good and all_bad results
* on hook_deny, also permit DENYSOFTDISCONNECT to pass through
* moved static -1 penalty for env_user_match to karma.ini
* emit logs much less frequently
* added [asn]report_as feature
=> karma: simplifying further

package.json
iconv no longer supports 0.8, we've stopped Travis testing Haraka on 0.8.
=> package.json: make node 0.10 requirement official

connection.js, plugins/queue/smtp_forward.js, plugins/queue/smtp_proxy.js
1. Don't save txn results in queue/smtp_forward, redundant with #950
2. Don't append txn ID to queue message in queue/smtp_*
3. Do append txn ID in connection.queue_*_respond
Question: Is there any reason for the txn ID to be appended? Log
messages are already prefixed with the txn ID and txn results already have
the txn ID available, so at that point, it's entirely redundant data.
Near as I can tell, the only reason to append it there is so that it's
returned to the sending MTA in queue_*_respond. If that's the case, I'd rather
append it there.
Thoughts?
=> smtp_forward: revert part of #962 w/overlap #950

config/karma.ini, docs/plugins/clamd.md, plugins/clamd.js, tests/plugins/clamd.js
* allow connections to continue if clamd error or virus found
* particularly useful if testing with multiple virus scanners, to compare
detection rates
* easier to use than clamd.excludes
* sets appropriate defaults
* emit: true is the default for results.add( {err: ...}) (no need to specify)
=> clamd: added reject options to clamd.ini

config/outbound.ini, docs/Outbound.md, outbound.js
The header involved gets added to the transaction after the `queue_outbound` event which is the last event before `queue_ok` that can modify the transaction (if I'm understanding the code correctly). This change simply lets the value of that header be customized with a simple string in the config/outbound.ini file. The default remains 'Haraka outbound'.
=> add support for custom Outbound Received header value

result_store.js
* moved the 'logging' paragraph from .add() into _.log()
* call from .add() and .push()
So the next bloke who calls results.push(plugin, { some: 'stuff', emit: true })
doesn't have to figure out why emit isn't working.
=> results: enable 'emit' feature for .push() fn

connection.js
* stores all sender and recipient attempts in results_store
* move rcpt incrementing into rcpt_incr, which also saves to results
replaces 10 of these:
this.transaction.rcpt_count[action]++;
this.rcpt_count[action]++;
with 10 of this:
this.rcpt_incr('accept');  // or 'reject' or 'tempfail'
This change drains some impetus for #945
=> connection: add MAIL and RCPT to results

connection.js
Discovered in #1021 - recipient log lines are normally logged by rcpt_respond() except when the hook returns OK which causes rcpt_ok_respond to do the logging instead - at which point CONT doesn't make any sense, so we change it to OK instead for consistency as CONT at hook_rcpt should be impossible.
=> Fix recipient log code when hook_rcpt_ok returns CONT

configfile.js, docs/Config.md, tests/config.js, tests/config/test.ini, tests/configfile.js
I'd like the INI key to be permissible without an = character. Currently, this
works:
key=
But this does not:
key
It seems not-very-intuitive to require that = sign to be present.
```ini
[hosts]
es1.nyc.example.com
es2.nyc.example.com
es1.lax.example.com=protocol:https, dc:lax
es2.lax.example.com=protocol:https, dc:lax
```
There's also quite a few places where we shove data off to separate files to get `list` loading ability, and this permits storing that data in an ini [section].
=> config: make ini values optional

server.js, tests/server.js
* run wss_init hooks in init_http_respond
* organize all HTTP stuff into a Server.http object
```js
Server.http = {
cfg: ...  // contents of http.ini
app:      // express app
server:   // 'http' server
express:  // express lib
}
```
fixes #987
=> server: run http_init in init_[master|child]_respond

connection.js
This fixes the behaviour when hook_rcpt returns `next(OK, 'message here')`.   Currently the message is ignored as hook_rcpt_ok takes the message sent by any plugins that it ran instead.   This patch applies any message from hook_rcpt where the message is unset in hook_rcpt_ok.
=> Allow hook_rcpt to return OK with message

plugins/auth/auth_base.js
* store auth results in a static location (was: name of auth plugin, so a
fishing expedition of active auth plugins was needed to find where to locate
auth results)
* store auth method
* when saving to 'relay', replace the pass message of 'auth' with the auth
plugin that succeeded.
=> auth_base: save auth results to 'auth' plugin result

plugins/rcpt_to.ldap.js
I had problems with a missing plugin while trying to rcpt_to.ldap -- looks like this inherits line should include the full name of the plugin or else it doesn't work.
=> Incorrect plugin name

plugins/connect.geoip.js
Jun 18 11:28:50 node haraka[35247]: [CRIT] [B4AB32E7.1] [core] Plugin connect.geoip failed:
TypeError: Cannot read property 'countryCode' of undefined at Plugin.exports.received_headers
Jun 17 14:48:52 node haraka[43032]: [CRIT] [2AA87F05.1] [core] Plugin connect.geoip failed:
TypeError: Object [object Object] has no method 'user_agent'     at
Plugin.exports.add_headers (/usr/local/lib/node_modules/Haraka/plugins/connect.geoip.js:266:23)
=> geoip: fix two CRIT errors:

connection.js
since I told ES that field is a boolean, it gets cranky about this
````
Jun 19 10:45:35 node haraka[97348]: [ERROR] [34C15870-6E62-41F1-A6DF-F749240EEC6E] [log.elasticsearch] MapperParsingException[failed to parse [conn.early_talker]]; nested: JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors  at [Source: [B@457ee1bd; line: 1, column: 1010]]; 
````
related to #983
=> early_talker: fix boolean being assigned as number

config.js, configfile.js, haraka.js
This was partly broken by https://github.com/baudehlo/Haraka/commit/d8d74cea30938fc71270955ee87b126f1964e0f6 as the override works by replacing the cache for the filename, and it can't know the options being passed beforehand.
So to fix this - overrides are tracked and get_config_cache returns the bare name for these without the options.
Additionally - the smtp.json file wasn't being loaded early enough to override smtp.ini, loglevel etc., so that has moved to config.js instead of haraka.js.
=> Fix JSON/YAML overrides

docs/plugins/access.md, plugins/access.js, tests/plugins/access.js
* move get_domain() into it's own function
* document what gets saved in results
* no listing = unlisted(hook_name:any)
* whitelist  = pass(hook:any)
* blacklist  = fail(hook:any)
* un-nest load_access_ini
* remove nested and not-necessary callbacks in list loading functions
* use register() in test setup instead of calling each _init() function in each test
=> access: use connection.hook to determine hook

docs/Results.md, result_store.js, tests/plugins/karma.js, tests/result_store.js
Note that this is just PR #910 reopened. Also note that a related change that makes this more useful now was merged in #950. Besides @celesteking 's purpose, I have since found another use for this feature (besides making the test writing syntax cleaner). That will come in a future PR.
=> results: permit a string or object as 1st arg

plugins.js, tests/plugins.js
Order of plugin loading:
1. process.env.HARAKA_PLUGIN_PATH (if defined)
2. process.env.HARAKA/plugins
3. process.env.HARAKA/node_modules
4. __dir/plugins
5. __dir/node_modules
* __dir = Haraka config dir  (haraka -i this_value)
* process.env.HARAKA = Haraka install dir
closes #946
=> permit loading of plugins in node_modules

plugins.js
Allows plugins to be loaded from modules installed using 'npm install' in the Haraka install directory.
Closes #1056
=> Load plugins from install directory's node_modules

config/log.elasticsearch.ini, docs/plugins/log.elasticsearch.md, package.json, plugins/log.elasticsearch.js, tests/plugins/log.elasticsearch.js
* merge transaction results into connection results
* get decoded message headers
* skip logging connection if already logged in transaction
* added exclude_hosts option
handy for not polluting ES results with monitoring and testing connections
* add default config file
* move transaction "stored" node outside cb
so that connections doesn't get stored if the transaction already did
* make ES index names configurable
* added config setting to nest plugin result inside another object
* add tests
* added log_connections option
* list of message headers to add is now a config setting
* the top level names (plugin, connection, message) are configuration with config options
* connection properties names can be aliased with config settings in [report_as] block
* removed index map template (until …
=> log connection info to Elasticsearch

package.json
Bump to 1.2.0 for node-syslog to prevent error when installing using node v0.12.
=> Bumped version of node-syslog to fix build error on node v0.12

connection.js
this code is a recent addition (with Elasticsearch plugin), this just makes it a little less noisy.
=> only store the extra recipient info when action != accept

plugins/connect.fcrdns.js
instead of storing an error object (which looks like: { Object: Object }, store the error message.
=> fcrdns: better error message to results

plugins/connect.geoip.js
From:
`````
[ERROR] [-] [Error]
`````
To:
`````
[ERROR] [-] [connect.geoip] Required DB not available. Possible types: ""
`````
=> Fix error message in connect.geoip

connection.js
Prevent this:
````
Jul 18 15:55:04 mail haraka[99856]: [CRIT] [-] [core] TypeError: Cannot read property 'header' of null
Jul 18 15:55:04 mail haraka[99856]: [CRIT] [-] [core]     at Connection.data_post_respond (/usr/local/lib/node_modules/Haraka/connection.js:1543:31)
Jul 18 15:55:04 mail haraka[99856]: [CRIT] [-] [core]     at callback (/usr/local/lib/node_modules/Haraka/plugins.js:345:35)
````
=> check for this.transaction before accessing it

plugins/connect.geoip.js
Currently reported as:
`"human": "US, MD, Baltimore, undefinedkm",`
and
`X-Haraka-GeoIP: US, MD, Baltimore, undefinedkm`
=> Fix distance reporting to X-Haraka-GeoIP for geoip-lite

connection.js, transaction.js
The delay between the ending dot and when the message is accepted is a key statistic as most senders do not honour the RFC timer of 5 minutes for this phase, typically most senders timeouts are much shorter, so the delay must be kept to a minimum.
I've moved the recording and storage of this to the transaction object as it seemed the more logical place to keep it and so that this can be used later by a plugin e.g. one that logs the delay to a database.
=> Move data_post hook timer into transaction object

outbound.js
Prevents this:
`250 Message Queued (9E4BCB7C-6006-451E-BA1D-7F80FCABBE72.1) (9E4BCB7C-6006-451E-BA1D-7F80FCABBE72.1)`
Due to the changes in https://github.com/baudehlo/Haraka/commit/167a65452b0d26db3b19cf3ecdef8bcc4f588231
=> Remove UUID from queued message

connection.js, docs/Connection.md
Allows you to do something like this in a plugin:
`````
// Do an A record lookup of the host name
dns.resolve(host, 'A', function (err, addrs) {
if (err) return next();
if (addrs.indexOf(server.notes.public_ip) !== -1) {
connection.loginfo(plugin, 'host matches public IP');
return check_user();
}
if (addrs.indexOf(connection.haproxy_ip) !== -1) {
connection.loginfo(plugin, 'host matches HAProxy IP');
return check_user();
}
return next();
});
````
=> Store HAProxy IP in connection object

plugins.js
Just realised that my plugin ordering changes in https://github.com/baudehlo/Haraka/commit/24d15b6006789b630392eac4343ba5100ec25483 incorrectly cased the object ordering to change even when no priorities are set.
This patch fixes that and retains the original order as per the ordering in `config/plugins` when no priorities are set.
=> Fix plugin ordering

connection.js
When HAProxy was used the port was turn into a string preventing the "Require authentication on connections to port 587 & 465
" to work properly like when HAProxy wasn't used.
=> Fix port to number instead of string for HAProxy

plugins/karma.js, plugins/tls.js
Fixes @celesteking issue as reported on IRC:
`````
11:28:28 - cek: [INFO] [E3540B59-60C2-4B0C-A98E-D232141349E7] [max_unrecognized_commands] max: 3, count: 0, fail:Unrecognized command: STARTTLS,
11:28:39 - cek:  [tls] timeout
11:28:57 - cek: [core] hook=unrecognized_command plugin=tls function=tls_unrecognized_command params="STARTTLS" retval=DENYSOFTDISCONNECT msg=""
11:29:07 - cek: [tls] secured: cipher=AES128-SHA version=TLSv1/SSLv3 verified=false error="Error: unable to get issuer certificate"
11:29:14 - cek: [core] tls plugin ran callback multiple times - ignoring subsequent calls
`````
=> TLS fixes: add timed_out flag and karma should not run deny hook on it.

README.md
Installing Haraka with NPM directly takes care of dependencies, but before you can run it out of a git repo, you have to install dependencies.  I assume `npm install` (installing the deps locally rather than globally) is the preferred way to do this
=> Include dep installation step in git instructions

outbound.js
When sending outbound email, the reason string in the Bounce-Message was missing STMP code and extended code for 5XX responses when not responded to the RCPT-TO command.
A test scenario is for example a swaks to gmail.com with --data option omitting headers, which is responded with "550 5.7.1 [...] likely unsolicited mail [...]" after the DATA command.
=> Include STMP-code in bounce-reason string for upstream 5XX responses

outbound.js
By default windows supports no DOTFILES, so it need a prefix - i take `__tmp__` for this.
#598 can closed after merge.
=> Fix #598 on windows systems.

configfile.js, tests/plugins/rcpt_to.routes.js
* Fix config flat files read and removes \r at line end - tests was before failed
* Fix test that wrong implemented for rcpt_to.routes.js
=> Fix tests and configfile parser

plugins/connect.fcrdns.js
(now that every request is being made for IPv4 and IPv6, so at least one fails
on every request)
=> fcrdns: don't log error for ENODATA

plugins/connect.fcrdns.js, tests/plugins/connect.fcrdns.js
After merging #1123, every domain has an A and AAAA query performed. The AAAA query failures were calling handle_a_error, which certainly was the wrong thing. 
This logs and otherwise ignores the errors, so a ptr_valid failure is only emitted if neither query returns a result.
=> repair ptr_valid errors introduced with #1123

plugins/dcc.js
simple syntax error in plugin/dcc.js fixed (not tested)
=> Plugin dcc: fixed syntax error

outbound.js, tests/fixtures/util_hmailitem.js, tests/outbound_protocol.js, tests/outbound_protocol/basic_outbound_trial_test.js
Mainly, introduced HMailItem.prototype.try_deliver_host_on_socket to be able to inject a mocked socket for testing
* a basic test on outbound.js triggering bounce
* Fix tests/outbound_protocol.js on node 0.10.40
* replaced hacky "this" in global context in call to util_hmailitem.createHMailItem by (hacky) explicit context.
* Fixed errorneus global in tearDown-func
* some code clean-up/code-style, docs/comments improved, fixed errorneus global
* PR squashed
* trailing whitespace cleanup (@msimerson)
* closes #1157
=> Improve outbound testability

plugins.js
This makes the server object available on plugins that were loaded from the Haraka config directory's node_modules.
=> make sure server object is availabe to plugins loaded from node_modules

package.json
https://github.com/baudehlo/Haraka/pull/1147#discussion_r40035932
=> update engines to 10.36 at least due to bad certs in the older nodes

docs/Outbound.md, outbound.js
Outbound.send_email: added dot_stuffed option + doc
renamed option "dot_stuffing" to "dot_stuffed", default false. Enabling it would strip leading dots in content-lines.
added documentation for the new send_email option to enable passing already dot_stuffed content
closes #1165
=> Outbound.send_email: added dot-stuffing

config/rate_limit.ini
comments not in same line as key = value; comments must be a row above to be entered
closes #1104
=> rate_limit plugin config need default uncommented

config/outbound.bounce_message, outbound.js, tests/fixtures/util_hmailitem.js, tests/fixtures/vm_harness.js, tests/outbound_protocol.js, tests/outbound_protocol/basic_outbound_trial_test.js, tests/outbound_protocol/outbound_bounce_net_errors.js, tests/outbound_protocol/outbound_bounce_rfc3464.js
This PR adds bounce messages in RFC3464 format for outbound failures:
- config/outbound.bounce_message is used for the headers and the human-readable part
- bounce message contain original mail headers only
- re-uses dsn.js for errors before talking to remote-MTA
- uses remote-MTA codes on failures during SMTP conversation
- includes tests
- includes no docs except some lines in source
- reorganized outbound_protocol tests to reuse fixtures/vm_harness
Feedback welcome
=> Outbound Bounce messages according to RFC3464

connection.js
Had a bug when someone connected, sent a message with \r\n and immediatly disconnected
[INFO] [A317A8ED-2076-4E22-B4F6-925884DF9241] [core] HAProxy: proto=TCP4 src_ip=94.125.160.157:34982 dst_ip=149.202.52.64:587
[CRIT] [-] [core] RangeError: Maximum call stack size exceeded
[CRIT] [-] [core]     at new Uint8Array (native)
[CRIT] [-] [core]     at Buffer.subarray (native)
[CRIT] [-] [core]     at Buffer.slice (buffer.js:574:23)
[CRIT] [-] [core]     at Connection._process_data (/data/src/Haraka/connection.js:357:43)
[CRIT] [-] [core]     at Connection._process_data (/data/src/Haraka/connection.js:374:18)
Fixed the problem by applying what master smf said :o
=> Fix bug when client disconnect after sending data

docs/plugins/queue/smtp_forward.md, plugins/queue/smtp_forward.js
I didn't notice this soon enough..
In the current plugin docs and ini are these style settings:
```ini
auth_type
auth_user
auth_pass
```
And the changes as contributed use auth.type and auth.user. Since smtp_forward has per-domain routing and having auth settings per-forward is desirable, make the plugin match the docs and sample .ini.
Also, update plugin to use the `cfg` that's already defined with per-domain route information, which post-dates this PR.
=> make smtp_forward auth settings match docs/ini

plugins/rspamd.js
try harder not to send them...
[CRIT] [B5F4FF21-B2A7-4527-B689-0E3E0484B737.1] [core] Plugin rspamd failed: Error: `value` required in setHeader("Hostname", value).  at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:339:11)
=> rspamd hates empty headers

plugins.js
This prevents reading in the contents of package.json as the source code. And removes the useless "use strict" on that code path.
=> Clean up plugin loading a tiny bit

.travis.yml, plugins/connect.fcrdns.js, plugins/helo.checks.js
* ignore the 'queryAaaa ENODATA' error.
* corrects an error pointed out in the comments of #1140 
* better error handling, more DRY by reusing net_utils.get_ips_by_host (#1249)
=> ignore ENODATA DNS lookup err

outbound.js
Currently on a queue error e.g. out-of-disk space or queue directory permissions issue causes Haraka to return a DENY which is incorrect - it should be a DENYSOFT so that the messages are recoverable.
Fixes #1263
=> outbound: Return DENYSOFT and not DENY on queue error

smtp_client.js
makes it easier for folks who set `enable_tls` to figure out why it's not working for them.
=> warn if enable_tls is set and certs are missing

result_store.js, tests/result_store.js
```js
if (typeof result[key] === 'object') continue;
```
Because Array's are a type of object, that line was inadvertently suppressing the display of arrays with content. The line above makes it obvious Arrays with contents are supposed to be shown.
=> show array when it has length

docs/plugins/redis.md, plugins/redis.js, tests/plugins/redis.js
* use cfg.host (as shown in docs), with backwards compat
* the path to redis in the select call was invalid
=> redis: make plugin match docs, fix bug

connection.js
When a host is using the PIPELINING extension it will always send DATA as the last command in the pipeline sequence as it hasn't read our responses to the previous commands yet, so it will always hit the '554 No valid recipients' error, so this should not be counted as an error.
=> Fix error reporting

plugins/connect.geoip.js, plugins/connect.p0f.js
when connecting from RFC1918 space, this untidiness was shown:
````
X-Haraka-p0f: os="undefined undefined" link_type="undefined" distance=undefined total_conn=undefined shared_ip=Y
X-Haraka-GeoIP: --, , NaNkm
X-Haraka-GeoIP-Received: 
````
=> avoid logging garbage

plugins/spamassassin.js
* I had added this locally and forgot to commit it when karma was updated to get scoring info via redis pub/sub. Net result: spamassassin results for anyone not running my local spamassassin plugin weren't getting scored with karma or displayed in watch.
=> publish spamd results to result_store

docs/plugins/rspamd.md, plugins/rspamd.js
* emit a result_store error
* prevents Haraka from deferring all mail if rspamd is unavailable
* (uncovered in testing, when no rspamd was running)
````
[CRIT] [4D950DEC.1] [core] Plugin rspamd timed out on hook data_post - make sure it calls the callback
[INFO] [4D950DEC.1] [core] hook=data_post plugin=rspamd function=hook_data_post params="" retval=DENYSOFT msg="plugin timeout"
[INFO] [4D950DEC.1] [watch] watch deny saw: rspamd deny from data_post
[NOTICE] [4D950DEC.1] [core] message mid="" size=231 rcpts=1/0/0 delay=35.633 code=DENYSOFT msg="plugin timeout"
[ERROR] [4D950DEC.1] [rspamd] query failed: connect ETIMEDOUT 172.16.15.13:11333
````
=> rspamd: add timeout error handling

config/karma.ini, docs/Results.md, docs/plugins/redis.md, plugins/karma.js, plugins/redis.js, plugins/watch/index.js, tests/plugins/redis.js
Previously, the redis plugin worked well, except when the pub/sub channel was on a host other than 127.0.0.1. PR #1275 sorta fixed the karma plugin so that it could subscribe to a remote redis when the redis plugin (and by extension, result_store) could pub/sub to that remote redis host. It was not an optimal way to fix it though, because it duplicated the redis.ini parsing and connection logic.
With these changes, the redis connection and subscription functions are consolidated into the redis plugin, where they can be called by plugins that subscribe to result_store messages (currently karma & watch). Now the redis plugin has a config section for pubsub and all publishers and subscribers can use the same settings, without each subscriber having to duplicate the pubsub connection logic. …
=> permit redis pub/sub to work when host != localhost

docs/Outbound.md, outbound.js
When you create a new email using `send_email()` it creates a brand new transaction.
If you need some information in that transaction like notes filled in another hooks you cannot access to them.
This PR allows to pass a new option the `send_email()` to preserve the notes. It just adds another option to the options object that `send_email()` already receives.
Includes updated docs.
Fixes #1293
=> Allow pass notes to send_email

logger.js, tests/logger.js
* skip processing if typeof data !== object && !data
* handles `null` case
* guards against future false-like values that happen to be an object
* remove redundant typeof check
fixes #1298
=> logger: ignore empty/null/false arguments

connection.js
hook_reset_transaction is a special case as it's the only hook that isn't tied to a command and therefore the client can pipeline other commands causing other hooks to run at the same time or for the transaction to disappear whilst the hook is running.
To prevent that - we pause the socket and our line read loop until the hook completes.
=> Pause connection for hook_reset_transaction.  Fixes #1235

docs/plugins/rcpt_to.routes.md, package.json, plugins/karma.js, plugins/rcpt_to.routes.js, plugins/redis.js, tests/plugins/rcpt_to.routes.js
* inherits from plugins/redis
* rcpt_routes: removes redundant redis functions
* moves karma.init_redis_karma() -> redis.init_redis_plugin()
* moves rcpt_to.routes.redis_ping -> redis.redis_ping()
* when testing, fails fast if redis server not available (fixes #1290)
* passes tests when redis present.
fixes #1290
=> rcpt_to.routes: updated to work with redis plugin

Changes, UPGRADE, UPGRADE.md, docs/plugins/queue/qmail-queue.md, docs/plugins/queue/smtp_forward.md, docs/plugins/queue/smtp_proxy.md, plugins/queue/qmail-queue.js, plugins/queue/smtp_forward.js, plugins/queue/smtp_proxy.js
This is my answer to #1307, reflecting the way I think it ought to be.
Since this would change the default behavior of the smtp_proxy plugin, it may not be proper to make the code do this right away, and until a future version bump, perhaps smtp_proxy.enable_outbound should still default default to false?
=> add queue_outbound config option

outbound.js, tests/outbound_protocol/outbound_bounce_rfc3464.js
This fixes the "Final-Recipient" header in bounce messages sent by Haraka's outbound module by adding the missing dash ('-').   The standard specifies the header name with the dash (e.g., https://tools.ietf.org/html/rfc3798).  
(The missing dash was causing automated bounce message handling code to fail to properly handle bounces produced by Haraka's outbound module.)
=> Add missing dash to 'Final-Recipient' header name

plugins/spf.js
return_results was incorrectly being passed the scope 'mail' instead of 'mfrom', so the configuration checks all returned undefined.
=> spf: honour configuration for mfrom scope

messagestream.js
There is a bug in `get-data` of `messagestram`.
Currently if you pass the options parameter they are ignored. 
You can confirm it here, and test the pruposed fix https://repl.it/BgLr/0
So this PR fixes it. Tested for passing just the callback and the options and callback.
=> Now passing options parameter to MessageStream get_data

plugins/dkim_verify.js
Fixes #1163.  Patch from @baudehlo.
With the way the plugin was written before, it was possible that a later plugin would also call connection.transaction.message_stream.pipe() before dkim_verify's pipe had ended, leading to an error.  This moves the next() call out of the DKIM callback and into the end handler on the stream to ensure that'll never happen.
I've been running this patch for a while and it does seem to fix the crash, but I haven't had time to dig in and verify it's behaving correctly everywhere.
=> Call next only after message_stream ended

mailbody.js, tests/mailbody.js
We're seeing these occasionally in production logs:
RangeError: out of range index
at RangeError (native)
at insert_banner (mailbody.js:189:13)
It looks like an empty html part results in an insert-at index of -1, which
won't work with buf.copy. So fix it by returning 0 in that case.
That means that an empty html part will now be just the banner. That's the
current behavior for the text part though. And if the only thing we have is an
html part, I think we want to show the banner.
=> fix out-of-range errors from banner insertion

config/outbound.bounce_message, outbound.js
Add the original email's Subject to the set of values that can be used in the config/outbound.bounce_message template, for more informative bounce messages.
=> Allow original email's Subject to be included in bounce message

configfile.js, docs/Config.md, tests/config.js, tests/config/test.ini, tests/configfile.js
msimerson commented in a pull request https://github.com/haraka/Haraka/pull/1333#issuecomment-184313920
One thing that might be worth changing is the way the host pool is
configured. A method that already has widespread use is to specify an array
for the host value instead of a string. This would necessitate extending our
ini parser to recognize the array syntax.
The syntax looks like this. There is no "official" .ini syntax for arrays, but
this seems to be common.
hosts[] = first_host
hosts[] = second_host
hosts[] = third_host
This is PR #1342 , rebased and squashed. Closes #1342
=> handle arrays in .ini files

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml
version bump node.js 4.2 -> 4.3 (LTS)
* add 5.6 testing (Stable)
* maintain 4.x (LTS) testing
* drop node 0.12 (LTS) testing, as its covered by 0.10
* maintain 0.10 (Maintenance)
This is [tracking the upstream](https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/) node.js releases, where version 4.2 is dropped due to openssl updates included in 4.3.
Test drive the GitHub repo templates feature.
=> version bump node.js 4.2 -> 4.3 (LTS)

plugins/karma.js, tests/plugins/karma.js
Not used since PR #1277, which switched to inheriting from the redis plugin
=> remove redis loading from karma

docs/Outbound.md, docs/plugins/queue/smtp_forward.md, docs/plugins/queue/smtp_proxy.md, docs/plugins/tls.md, outbound.js, plugins/tls.js, smtp_client.js
- Let's tls.ini have separate [inbound] and [outbound] sections for 'ciphers', 'requestCert', 'rejectUnauthorized' options
=> Allow for override for inbound/outbound

haraka.js
This fixes a pretty serious bug.
Currently when running under 'cluster' (as everybody should be) and a plugin crashes the Haraka worker, the child will not be respawned by the master like it should be as the master thinks the child exited cleanly.
This patch passes back the original exit code so that the child is correctly respawned.
=> Fix on exit handlers

dkim.js
Fixes #989
Headers specified multiple times in the h= field were being incorrectly added twice and in the wrong order if multiple header fields were present.
=> Fix DKIM verifier header handling

connection.js
Otherwise we end up with DSN object in msg and not with a string.
=> if rcpt_to returns DSN in msg, log it properly.

config/dnsbl.ini, config/dnsbl.zones
We need to think about the optimal default configuration for this plugin.
As it stands, if someone configures the plugin like this:
```sh
echo 'zones=b.barracudacentral.org, truncate.gbudb.net' >> config/dnsbl.ini
```
They'll also have zen.spamhaus.org configured as well, because it will be enabled in the invisible (to the user) config directory. This seems a POLA violation.
This PR isn't much better, in that if someone were to do this:
```sh
echo 'b.barracudacentral.org' > config/dnsbl.zones
```
They'd once again be surprised to find that zen.spamhaus.org is active. 
Remove the docs for dnsbl.zones and encourage everyone to use dnsbl.ini.
Now that we can have empty values in our .ini files, we could also deprecate both methods and replace them with an INI section:
```ini
[zones] …
```
=> remove dnsbl.zones, so overrides are better

plugins/rspamd.js
Fixes:
`````
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core] TypeError: Cannot read property 'score' of undefined
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core]     at Plugin.exports.add_headers (/usr/lib/node_modules/Haraka/plugins/rspamd.js:261:19)
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core]     at no_reject (/usr/lib/node_modules/Haraka/plugins/rspamd.js:147:32)
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core]     at IncomingMessage.<anonymous> (/usr/lib/node_modules/Haraka/plugins/rspamd.js:152:54)
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core]     at emitNone (events.js:72:20)
Mar 30 07:43:51 mail1-ewh haraka[25622]: [CRIT] [-] [core]     at IncomingMessage.emit (events.js:163:7)
Mar 30 07:43:51 mail1-ewh haraka[25622]: …
```
=> rspamd: Fix undefined variable

haraka.js, logger.js, package.json, server.js
Remove the exit module as it's caused me multiple nasty issues.
The latest issue I've had was extremely hard to diagnose (it required strace) which caused the cluster master to be unable to respawn a crashed child process:
````
write(2, "events.js:141
throw er; // Unhandled 'error' event            
Error: This socket is closed.
at Socket._writeGeneric (net.js:625:19)
at Socket._write (net.js:678:8)
at doWrite (_stream_writable.js:291:12)
at writeOrBuffer (_stream_writable.js:278:5)
at Socket.Writable.write (_stream_writable.js:206:11)
at Socket.write (net.js:603:40)
at /usr/lib/node_modules/Haraka/node_modules/exit/lib/exit.js:25:14
at Array.forEach (native)
at exit (/usr/lib/node_modules/Haraka/node_modules/exit/lib/exit.js:20:11)
at process.<anonymous> …
```
=> Remove exit module

plugins/auth/auth_proxy.js
[SendGrid](https://sendgrid.com/) seems to always include `STARTTLS` in capabilities (even when the connection is already secure), which causes an `auth_proxy` plugin's upgrade loop:
```
[DEBUG] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] attempting connection to host=smtp.sendgrid.net port=587
[PROTOCOL] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] S: 220 SG ESMTP service ready at ismtpd0003p1lon1.sendgrid.net\r\n
[DEBUG] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] command state: connect
[PROTOCOL] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] C: EHLO localhost
[PROTOCOL] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] S: 250-smtp.sendgrid.net\r\n
[PROTOCOL] [2D9395D9-B82F-4D85-8259-106A7CE2EBED] [auth/auth_bridge] S: …
```
=> Fix: auth_proxy upgrade loop if the server always includes STARTTLS

smtp_client.js
workaround for #1372 
- this fixes the crashing problem but...
- this is a bandaid, until someone has the time to investigate 1372 and determines why client.socket.remoteAddress is undefined.
=> bandaid for client.socket.remoteAddress undefined in node 5+

docs/plugins/bounce.md, plugins/bounce.js
Skip the single recipient check for relays or hosts with a private IP.
This is because Microsoft Exchange will send messages with a null return-path to distribution list members in certain circumstances (yes, really....).
=> bounce: skip single_recipient check for relays/private_ips

plugins/auth/auth_proxy.js
* use early exits instead of compound conditionals
* sheds a couple indention levels (see git diff -b below, easier to read vs github diff).
* replace a couple match without value tests with //.test()
Please review but don't merge. When it's merge-ready, I'll squash the commits.
```diff
diff --git a/plugins/auth/auth_proxy.js b/plugins/auth/auth_proxy.js
index 3d5cfbf..5356986 100644
--- a/plugins/auth/auth_proxy.js
+++ b/plugins/auth/auth_proxy.js
@@ -88,14 +88,22 @@ exports.try_auth_proxy = function (connection, hosts, user, passwd, cb) {
response = [];
};
socket.on('line', function (line) {
-        var matches;
connection.logprotocol(self, "S: " + line);
-        if (matches = smtp_regexp.exec(line)) {
+        var matches = smtp_regexp.exec(line);
+        if (!matches) return;
+
var …
```
=> refactor: auth_proxy

docs/plugins/xclient.md, plugins/xclient.js
- Only offer XCLIENT in capabilities for hosts that are allowed to use it.  This is to workaround a bug in some software called 'CoreMail' which is Chinese.  It always tries to use XCLIENT if it is offered, we returns a 'Not authorized' and it sends the mail successfully, then generates a bounce to the sender with the XCLIENT rejection in it :8ball: 
- Fix documentation
- Implicitly allow localhost
- Speed-up lookups
=> xclient plugin improvements

mailheader.js, tests/mailheader.js
Fixes #1378  .
- Folds continuations into a single space in decoded headers
Checklist:
=> Fix continuations being folded on get_decoded

plugins/greylist.js, plugins/queue/rabbitmq.js, tests/connection.js, tests/spf.js, tests/transaction.js
- removes a couple unused variable lint errors
- ignores SPF permerror for aexp.com (happens from time to time)
Checklist:
=> ignore SPF permerror when aexp.com fsck their SPF record

net_utils.js
Caching of the public IP was only implemented if the value was manually set in smtp.ini (which has limited value being as it is cached itself by the configuration loader).
This caches the STUN result (or lack of result), so that the STUN server is not endlessly queried for the same result.
I noticed the issue when I ran this up on a host which STUN failed to traverse the firewall - it caused connect.geoip to get a STUN timeout on every connection.
=> Fix caching of STUN results

tls_socket.js
This prevents clients from using SSLv2 (for the DROWN attack) *and*
SSLv3 (for the POODLE attack) when they issue STARTTLS.  See
<https://poodle.io/>, <https://drownattack.com/>, and
<http://disablessl3.com/#nodejs>.
The only way I know to test is a bit odd--you need an openssl version compiled with SSLv2 support.  This can be hard to find on modern systems; for example: the openssl that comes with Ubuntu 14.04 will say `unknown option -ssl2` even though later in the usage docs it has `-ssl2 - just use SSLv2`).  Run haraka, then:
openssl s_client -ssl2 -starttls smtp -connect localhost:25
(Replace `localhost`/`25` with the hostname and port of haraka.)  If you get an error that includes a line like:
140690032785224:error:1406D0B8:SSL routines:GET_SERVER_HELLO:no cipher list:s2_clnt.c:452: …
=> Disable SSLv2 (for DROWN)

plugins/data.headers.js
Fixes 1.
- Removal of incorrect log error from list detection code 
Checklist:
- [N/A] docs updated
- [N/A] tests updated
(Unless I'm overlooking something! ...) This removes an incorrect 
connection.logerror() from the (currently rudimentary) email
list detection code in the data.headers plugin.  As currently coded,
it would record an error to the log file for any email with a "Sender"
header that didn't start with "owner-".
=> Remove stray log error from list detection code

config/early_talker.ini, docs/plugins/early_talker.md, plugins/early_talker.js, tests/plugins/early_talker.js
The early_talker plugin currently causes delays even when submitting from localhost, which is quite unnecessary. The additional delay at DATA makes things even worse.
This change adds an ip_whitelist to the early talker plugin, based on the pattern used by the greylisting and xclient plugins. By default it includes 127.0.0.1 and ::1.
Includes tests and docs.
=> Add IP whitelisting to early_talker

host_pool.js, plugins/queue/smtp_forward.js, plugins/queue/smtp_proxy.js, smtp_client.js, tests/configfile.js, tests/host_pool.js
The original config for Haraka took a single host and port in the
smtp_forward.ini config to connect to. If that host was a CNAME with a
bunch of possible hosts it could resolve to, Haraka would have no way of
knowing if say just one of the hosts was down.
Now we can have the pool listed explicitly in the config like this:
forwarding_host_pool=1.1.1.1:1111, 2.2.2.2:2222, 3.3.3.3.:3333....
If that's not in the config, then smtp_client will continue to use the
old host and port settings.
When a host in the pool goes down, we remove it from the pool of available
hosts and we set a timer to check it periodically to see if it looks like
it's come back online.
The first attempted delivery to a failed backend will result in the mail
being rejected back to the originating MTA, who is responsible …
=> Haraka now takes a list of backend hosts to forward to

plugins/test_queue.js, transaction.js
Fixes #1386 .
- Use util.isRegExp instead - apparently instanceof doesn't always work.
=> Fix regexp use in filters

Changes, package.json
See included Changes.
There are several SIGNIFICANT changes merged in this release. To make this easier to test, an alpha version has been published to npm. You must specify the version specifically to get it like this:
`npm install -g  Haraka@2.8.0-alpha.4`
* config loading. haraka -i no longer fully populates config/*, instead loading config settings from the npm install dir and then applying local overrides found in config/*. See #1341
* The public-suffix and config/tld-* files have been removed to haraka/haraka-tld. It Works For Me but broader testing is welcome.
* Outbound TLS and `queue/smtp_*` plugins now honor tls.ini. This needs broader testing.
1. [x] config/plugins not installed (#1360)
2. [x] config/dkim/dkim_gen_key.sh not installed
3. [x] merge #1355
4. [x] merge #1357
5. …
=> haraka release 2.8.0

plugins/rcpt_to.ldap.js
- rcpt_to.ldap: handle connection error:  without this haraka crashes if ldap server is down
- ~~ldapjs is a required dependacy: ldapjs is in package.json~~ (removed since it is an optional dep)
- pick up domain specific config correctly: code incorrectly uses setting based on host_list file
- soft deny on ldap client and search errors: code incorrectly allows rcpt to's if the ldap server is down or generated an error.
Checklist:
- [X ] docs updated
- [X ] tests updated
=> rcpt_to_ldap fixes

Dockerfile
Allow ssh to Docker container for dev testing.  
> rm -f /etc/service/sshd/down
is required per https://github.com/phusion/baseimage-docker#enabling-ssh
=> Allow SSH for dev when using Docker

config.js
=> Fix config overriding for core modules

haraka.js
Fixes #845 .
- console.warn when running without `process.env.HARAKA` set.
=> Simple fix for #845

docs/plugins/queue/lmtp.md, outbound.js, plugins/queue/lmtp.js
Fixes #1215 .
- Allows lmtp.ini to set path= to use unix domain sockets
Checklist:
=> Support for unix domain sockets in lmtp

mailbody.js, utils.js
Fixes #1477  .
- Allows encode_qp to take a buffer, and encodes it as bytes
- Use bytes when re-encoding a banner
=> Fix encoding when banners are used

bin/haraka, configfile.js, connection.js, docs/Plugins.md, haraka.js, logger.js, outbound.js, plugins.js, plugins/connect.p0f.js, plugins/dns_list_base.js, plugins/greylist.js, plugins/process_title.js, plugins/rate_limit.js, plugins/redis.js, server.js, timer_queue.js
Fixes (probably a number of tickets somewhere deep in the unknown)
- Adds bin/haraka --graceful to reload child processes gracefully
- On SIGINT, will shutdown gracefully
- Adds plugin.shutdown() method so plugins can clearInterval() any timers they have setup
Will add docs in another commit.
Checklist:
=> Graceful shutdown and restart

plugins/auth/auth_base.js, plugins/auth/auth_vpopmaild.js, plugins/auth/flat_file.js, tests/plugins/auth/auth_base.js
Replaces and closes #1447
- Passes connection object when the function expects it, not if it doesn't
- Maintains parameter ordering with callback last
Checklist:
=> Pass connection object to get_plain_password better

docs/Outbound.md, outbound.js, server.js, tests/outbound_protocol/basic_outbound_trial_test.js, tests/outbound_protocol/outbound_bounce_rfc3464.js
I'd probably suggest holding off merging this until after 2.8.1, but I'd also like it to be well examined, since it has a huge impact on anyone using outbound.
Please read the code and comment.
- Uses generic-pool much like smtp_client does
Checklist:
=> Outbound pool support

package.json
Fixes #1490 
- Bind to maxmind 0.6 - we can fix it to the new API later.
=> Bind maxmind version to ignore API change

haraka.js, server.js
Fixes #1498 (hopefully)
- Runs quit routines when not running under nodes=
- Waits 5s when done, as we have no other reliable way to stop node
Checklist:
=> Fix quit when running without nodes=

plugins/redis.js
Fixes # 1498
- Properly shut down redis by calling quit() instead of end()
- Also quit server.notes.redis
=> Shut down redis properly.  Closes GH-1498

config/smtp.ini, configfile.js, server.js
Fixes no direct issues, but more cleanly shuts down everything.
- unref all the servers (smtp and http)
- Adds an unref'd timer to full shutdown so we don't need to forcefully process.exit()
- Further cleanup of watched config
Checklist:
=> More graceful shutdown

plugins/rcpt_to.ldap.js, tests/plugins/rcpt_to.ldap.js
- Instead of performing an LDAP lookup on the e-mail address specified by the client in the RCPT TO command, look at the value in the rcpt_to array which may have been modified by the aliases plugin.
=> Make rcpt_to.ldap work with aliases plugin

net_utils.js, tests/net_utils.js
- This check is per section 4.1.3 Address Literals of RFC 2821
Checklist:
- [X ] tests updated
=> Match IPv6 literals in ehlo

host_pool.js, tests/host_pool.js
Fixes failing tests
- Waits for at least 10s for host_pool timer to fire.
- Also fixes a tiny memory leak in large host pools by deleting from the hash instead of setting false
Checklist:
=> Fix for host_pool test under high load

dkim.js
Pass in a copy of header_idx to DKIMObject instead of header_idx directly.
Since DKIMObject mutates header_idx by using pop(), therefore, if the email has more than 1 DKIM-Signature, then the first DKIMObject will verify but then the later DKIMObject will not verify since there are no header_idx.
=> DKIM: DKIMObject needs to have a copy of header_idx

tests/plugins/connect.geoip.js
- GeoIP test appears to be continually failing because the coordinates in the test file are for Kansas
=> Michigan is not in Kansas

plugins.js
Fixes #1513 
- load the file contents of plugins-as-npm-package same as plugin.js file
=> read file contents of plugin when plugin is a package

server.js
Fixes #1520 .
- Don't unref the wss object - the socket is already unref'd
=> Don't unref wss server - it's already unref'd

docs/Plugins.md, outbound.js, plugins/dkim_sign.js
Fixes #336
- Implements dkim_sign with mail sent via outbound.send_email()
- Adds new hook: `hook_pre_send_trans_email`.
Checklist:
=> Support dkim_sign with outbound.send_email()

plugins/spf.js
Fixes #1329
- Display the IP used for lookup in the SPF results
- Always check the connected IP first and only check the public IP is the result !== Pass.   This is because a relay might be sending mail from a non-local domain, currently this scenario would return an incorrect SPF result.  This gracefully handles those cases and handles better the case when the public_ip cannot be determined.
=> spf: context=myself fixes

docs/plugins/aliases.md, plugins/aliases.js, tests/plugins/aliases.js
- Support for '+' in wildcard notation
- Make wildcard notation work when host is provided
Checklist:
- [X ] docs updated
- [ X] tests updated
=> Support '+' wildcard in aliases plugin

.travis.yml, outbound.js
transaction.results is used widely by many plugins to store results.
The code in connection.js creates this property in init_transaction
but similar logic is missing in outbound code.
In the future, results property should move to the transaction constructor.
But this is complicated by the fact that ResultStore requres a connection
object and doing this properly requires a (risky) refactor.
(The specific crash here was that the dkim plugin tries to sign a bounce
mail and crashes when doing a txn.results.add)
=> outbound: Add results property to transaction

plugins/process_title.js
- Allows haraka to shutdown cleanly when using process_title in single process mode
=> Allow process_title to shut down when not cluster

config/rspamd.ini, docs/plugins/rspamd.md, plugins/rspamd.js
- Oops! We had some [bad documentation](https://github.com/vstakhov/rspamd/pull/836/files) RE: use of `task:set_rmilter_reply` and consequently Haraka plugin was expecting data in a wrong format. :(
- Also add `never_add_headers` option, which could be useful if you want to use custom headers from Rspamd, or just don't want to add headers for whatever reason.
Checklist:
=> Fix adding/removing headers in rspamd plugin; add never_add_headers

docs/plugins/delay_deny.md, plugins/delay_deny.js
Currently, this plugin delay denies everything unless listed in the
config file. This can be a little risky when experimenting this plugin
when a lot of other plugins are already in use.
In such cases, it's easier to use an included mode (a whitelist mode)
where one can add plugins to bypass one by one.
=> delay_deny: add included mode

plugins/dkim_verify.js
Fixes #1553 
- Call `next()` in the callback, not at stream end.
=> Don't call next() at stream end

connection.js, plugins/auth/auth_base.js, tests/plugins/auth/auth_base.js
Fixes #1366 .
- AUTH PLAIN divided in two lines: Server should respond with 334 code.
Checklist:
Now also additional email clients can connect to Haraka, such as Gnome geary.
=> AUTH PLAIN splitted into two lines

docs/Outbound.md, outbound.js
This is just a belt and braces attempt to stop Haraka shutting down from the error @ricardopolo reported here: https://github.com/haraka/Haraka/issues/1570
If it works: Fixes #1570
=> Attempt to fix outbound shutdown error

docs/plugins/rcpt_to.routes.md, package.json, plugins/rcpt_to.routes.js
- Allow rcpt_to.routes to use URI-formatted destinations so ```lmtp://``` vs ```smtp://``` can be specified
Existing tests pass, but I'm not sure they are thorough enough.  I'm a bit lost in the rcpt_to.routes.js test file, so I haven't written specific tests for my changes yet.
=> rcpt_to.routes URI format w/ LMTP support

line_socket.js, outbound.js, utils.js
Fixes #1549  .
- Allow send_email to use a stream in the `contents` object
Checklist:
=> Allow streams in outbound.send_email contents

plugins/watch/index.js
Fixes #1540
background: when watch.ini is missing, no [wss] section exists in watch.ini file
- check for [wss] section. avoids `TypeError: Cannot read property 'url' of undefined`
=> missing watch config

plugins/queue/rabbitmq.js
Fixes a bug rendering rabbitmq plugin unusable.
- Define the deliveryMode variable globally.
- Actually use the deliveryMode variable.
Checklist:
The variable wasn't defined globally. It wasn't being used when initializing the queue.
=> Fixed the deliveryMode bug.

plugins.js
Fixes [#1586](https://github.com/haraka/Haraka/issues/1586)
- Add third argument `params`.
=> Add third arguments params

outbound.js
Fixes #1576 and possibly others
- Mostly belt and braces around the pool code
- There still appears to be an issue with the pool getting locked up, but I'll continue working on that in another branch
Checklist:
=> Advanced pool

mailheader.js
Fixes #1596 .
- Catch errors from decodeURIcomponent()
Checklist:
=> Catch errors on header decode in rfc2231

Dockerfile
Fixes #1607
- change 'setuser root' for 'sudo' in Dockerfile
-
-
Checklist:
Use setuser within phusion/baseimage and avoid the "sudo command
not found" error.
=> Switch 'setuser root' for sudo in Dockerfile

messagestream.js
Fixes message stream piping issue.
When trying to pipe the message stream into a transforming stream (gzip in my case) the returning value is undefined.
This is because the short circuiting return statement lacks the necessary return value.
=> Returning undefined instead of piping destination

connection.js
Fixes # .
- Hiding version was not hiding version in SMTP response.
Checklist:
header_hide_version config setting did not hide version number from SMTP greeting.
=> Hiding version from SMTP greeting

outbound.js
This might improve outbound pool issues but it needs live testing as replicating them seems to be impossible.
=> Don't do a normal release on errors

plugins/watch/html/client.js
- makes the UUID in watch tables clickable
works with my log.reader plugin
=> change UUID to a URL

plugins/connect.p0f.js
- check for `os_name`, not `os` property
=> fix a spurious error emitted by p0f

docs/plugins/log.elasticsearch.md, plugins/connect.geoip.js, plugins/log.elasticsearch.js
- adds a geo property to the result store for geoip plugin
- send the more explicit geo property to ES
Checklist:
see caution note here: [https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html](https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html)
=> update geoip for compat with newer ES

plugins/rspamd.js, tests/plugins/rspamd.js
Fixes a warning about an unused variable that points at a bug: negative scores weren't processed correctly.
Also avoid adding an empty spambar when score is > -1 and < 1 (make this neutral instead).
=> Rspamd plugin: Fix spambar for negative scores

connection.js, tests/connection.js
this is a prequel to #1547 
It includes just the changes in connection.js, as shrewdly suggested by @smfreegard, as well as using .set() more often as commented by @baudehlo.
- converts connection.remote_* to connection.remote.*
- converts connection.local_* to connection.local.*
- converts connection.using_tls -> connection.tls.enabled
- maintains previous names, providing backwards compatibility
=> normalized connection properties

package.json, plugins/dkim_sign.js
- update async to version 2
- see [caolan/async/CHANGELOG](https://github.com/caolan/async/blob/master/CHANGELOG.md)
=> update async to v2

plugins/spf.js
Fixes a bug introduced in #1547
- remove unused spf.hello_host
=> remove incorrect and unused spf.hello_host

bin/haraka
Fixes #1628 .
- if existing, don't overwrite `host_list`
- when directories already existing, don't attempt to create and emit harmless error message
=> updates to bin/haraka

plugins/tls.js
Fixes #1534
- when plugin.timeout =0, don't set a tls timer
This essentially does what one expects (after reading the docs) and setting plugin.timeout=0. However, it might be better to instead use a default (30s) timer. Thoughts?
=> do not set timer if timeout=0

plugins/access.js
Fixes crash observed running Haraka directly from repo:
`````
[CRIT] [ED90CD6F-BDA8-4E8D-B0D4-370F45CDE561.1] [core] Plugin access failed: TypeError: Cannot read property 'host' of undefined
at Plugin.exports.data_any (/home/smf/git/Haraka/plugins/access.js:394:58)
at Object.plugins.run_next_hook (/home/smf/git/Haraka/plugins.js:486:28)
at Object.plugins.run_hooks (/home/smf/git/Haraka/plugins.js:402:13)
at MessageStream.end_callback (/home/smf/git/Haraka/connection.js:1618:17)
at MessageStream._write (/home/smf/git/Haraka/messagestream.js:138:37)
at ChunkEmitter.<anonymous> (/home/smf/git/Haraka/messagestream.js:64:18)
at emitOne (events.js:96:13)
at ChunkEmitter.emit (events.js:188:7)
at ChunkEmitter.end (/home/smf/git/Haraka/chunkemitter.js:92:14)
at MessageStream.add_line_end …
```
=> Fix access plugin crash

plugins/data.headers.js
Fixes:
`````
[CRIT] [ED90CD6F-BDA8-4E8D-B0D4-370F45CDE561.1] [core] Plugin data.headers failed: TypeError: Cannot read property 'address' of undefined
at Plugin.exports.from_match (/home/smf/git/Haraka/plugins/data.headers.js:289:54)
at Object.plugins.run_next_hook (/home/smf/git/Haraka/plugins.js:486:28)
at callback (/home/smf/git/Haraka/plugins.js:442:32)
at Plugin.exports.direct_to_mx (/home/smf/git/Haraka/plugins/data.headers.js:259:16)
at Object.plugins.run_next_hook (/home/smf/git/Haraka/plugins.js:486:28)
at callback (/home/smf/git/Haraka/plugins.js:442:32)
at Plugin.exports.user_agent (/home/smf/git/Haraka/plugins/data.headers.js:231:12)
at Object.plugins.run_next_hook (/home/smf/git/Haraka/plugins.js:486:28)
at callback (/home/smf/git/Haraka/plugins.js:442:32)
at …
```
=> Fix data.headers plugin crash

plugins.js
- permit specifying haraka plugins w/o `haraka-plugin-` prefix
- in config/plugins
- in resultstore
=> permit specifying haraka plugins w/o haraka-plugin- prefix

docs/plugins/tls.md, plugins/tls.js
Added quite some important TLS security options.
- select location of key and cert
- enable cipher order based on server list
- add options for dhparam and EC curve selection
- allow selection of the OpenSSL "method"
[x] docs updated
[x] no tests needed updating
=> More tls opts

connection.js, docs/Connection.md, tests/connection.js
Do the same for proxy properties as #1098 did for the rest of the connection properties.
- c.haproxy_ip -> c.proxy.ip
- c.proxy -> c.proxy.allowed
- c.proxy_time -> c.proxy.timer
- new property: c.proxy.type  (null, haproxy, someFutureProxy)
Checklist:
=> normalize proxy properties

tls_socket.js
This change properly registers honorCipherOrder as a boolean configuration option, i.e. one can actually set it to 'false' properly. Before that fix, either 'true' or 'false' would be strings, not honoring the boolean type and result.
Note that, from a security perspective, this flag should always be true, i.e. the server should choose the best available cipher and not the client. However, most TLS libraries take false as default and require manual override to true, so I kept with this system.
Checklist:
=> Make the new tls option honorCipherOrder actually a boolean

docs/plugins/tls.md, plugins/tls.js
Allows multiple file locations to specify for key and cert parameters in tls.
This allows multiple different key types to use which is required for RSA+ECDSA setups.
The patch fixes also a small documentation bug about the location of relative files, ```config/``` is automatically prepended.
Checklist:
=> Allow multiple key and cert parameters for RSA+ECDSA setups

tests/plugins/log.elasticsearch.js
Not calling that callback was causing AppVeyor CI testing to hang.
- call the setup callback after plugin load failure
Checklist:
=> fix ES test setup when plugin cannot load

tls_socket.js
While this change looks like cosmetics, it is needed for advanced TLSSocket operations like OCSP Stapling. This also fixes long-lasting #1099.
Checklist:
=> haraka/Haraka#1099 use TLSSocket instead of createSecurePair

tls_socket.js
The TLS client connect code broke miserably through the introduction of TLSSocket into the server code. We still need the old `pipe()` code before the client gets updated for TLSSocket, too.
Checklist:
=> fixed TLS client after server TLSSocket rework

configfile.js, docs/plugins/queue/smtp_forward.md, plugins/queue/smtp_forward.js, tests/config/smtp_forward.ini, tests/plugins/queue/smtp_forward.js
Fixes #1679 
- correctly compare destination hosts for multiple recipients
- add test coverage
- add config file wildcard boolean support
- so arbitrary ini sections names like `example.com` can have boolean properties like `enable_tls`
- update tests to use haraka-test-fixtures.transaction()
Checklist:
=> correct smtp_forward cfg for multiple rcpts

plugins/tls.js, server.js, tls_socket.js
Fixes #1667
- for port 465 to work, plugin tls has to be enabled.
- tls.ini config is properly included in SMTPS server setup
- session security is included in Received header
Note:
- PR is based on #1682.
Checklist:
=> #1667 bring port 465 SMTPS TLS config support on par with standard STARTTLS

outbound.js, smtp_client.js, tls_socket.js
Fixes #1678
[ ] add tests for config
=> use tls.connect for client

outbound.js
Fixes haraka/Haraka#1690
I’m getting `TypeError: Path must be a string.` as reported by others. The attached PR fixes the bug introduced by refactoring in #1690, with that change we don’t need to read the key inside the STARTTLS routine because it was already loaded.
=> haraka/Haraka#1690 fix outbound to avoid recursive reading key/cert after refactoring

.travis.yml, connection.js, host_pool.js, package.json, plugins/auth/auth_vpopmaild.js, plugins/avg.js, plugins/connect.fcrdns.js, plugins/data.headers.js, plugins/data.rfc5322_header_checks.js, plugins/karma.js, plugins/spamassassin.js, plugins/tarpit.js, tests/configfile.js, tests/plugins/tls.js, tests/result_store.js, utils.js
* do not toString() when null
* avoids a CRIT error when plain_pass is null/undefined.
* reduce log severity of failed pass
* lint fixes (whitespace)
=> auth/vpopmail: do not toString() when null

plugins/rspamd.js, tests/plugins/rspamd.js
Fixes #1563
Maybe I should just PR this. I planned to try make this header look better but I've not gotten round to that (nor other things in mind for Haraka & rspamd plugin) yet. @msimerson doesn't like having stuff nested under `default` and well, it is strange, but the idea is to really have the raw response from rspamd which makes this necessary evil. :)
- Restore spam report header
- Round down scores for spambar
- Restore untampered rspamd JSON
- Logs should be unaffected
Checklist:
- [N/A] docs updated
- [YEBO] tests updated
=> Rspamd plugin: restore spam report header

plugins/dkim_sign.js, tests/plugins/dkim_sign.js
Fixes #1705 
closes #1706
- use path.* instead of / delimited string (cross-platform compat)
- set haraka_dir to empty string when process.env.HARAKA is unset (for testing)
- switch from fs.exists (deprecated) to fs.stat for directory detection
- switch from async.filter to async.detectSeries (b/c results order matters)
- improved test coverage for get_key_dir 
Checklist:
=> misc dkim_sign updates

connection.js
The legacy property connection.remote_host was broken by https://github.com/haraka/Haraka/commit/8e412b10f2a3e646165801d6e519028f7e212563 and was undefined if the DNS lookup returned an error.
Additionally, `dns.NXDOMAIN` was incorrect - as per the Node docs, this should be `dns.NOTFOUND`, so it would appear this has been broken since day one.
=> Fix connection.remote_host and NXDOMAIN result

connection.js
`cmd_data` has yet to receive any headers...
Correct place would be once the headers (or the full data) is fully collected, hence `data_done`.
It also doesn't affect the message size, just like before.
=> Correct Auth-Results cleaning

smtp_client.js
Seems I made a typo. The given hostname should be stored in `servername` to be recognized as the SNI hostname when acting as a SMTP client. For some reason I added the feature correctly to `outbound.js` but not to `smtp_client.js`. See [here](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback).
=> fix tls option servername (not hostname)

plugins/redis.js, tests/plugins/rcpt_to.routes.js, tests/plugins/redis.js
- add redis client.on('end') event handler
- user newer redis client options.retry_strategy instead of legacy timeout
Checklist:
(This PR is mainly to give up on Redis faster and fail fewer tests when redis is not running, like on a dev workstation)
=> redis connection error handling

outbound.js, plugins/rspamd.js
- rspamd: fix the path for default
- outbound: check for defined-ness before calling function
Fixes #1731 
Fixes #1730
=> outbound & rspamd crit fixes

config/tls.ini
Fixes # [N/A]
- Fixed misleading entries in provided config/tls.ini file
Checklist:
- [N/A] docs updated
- [N/A] tests updated
The previous entries for the key and cert entries in config/tls.ini have
the form:
key: tls_key.pem
cert: tls_cert.pem
This was incorrect. This commit fixes the provided sample config/tls.ini
file with the correct syntax:
key=tls_key.pem
cert=tls_cert.pem
=> Fixed misleading entries in config/tls.ini

configfile.js, connection.js, docs/tutorials/Migrating_from_v1_to_v2.md, fsync_writestream.js, messagestream.js, plugins.js, plugins/dns_list_base.js, plugins/graph.js, plugins/toobusy.js, server.js, tests/fixtures/util_hmailitem.js
- Fixed bug in config cache that was causing non-existent files to be checked on every call.
- As we've dropped support for earlier versions of Node, replace all calls to process.nextTick() with setImmediate() and expose setImmediate() in the plugin sandbox.
- Fix toobusy plugin, it was completely broken and not working correctly.
- Set backlog to zero on all listen() calls as it was found to improve connection handling under heavy loads (>30 connections/sec).
=> Misc. performance improvements

tls_socket.js
Fixes #1739 
- create a top level scoped secureContext (maybe store it in Redis eventually)
- consolidate 2x secureContext creations into `_getSecureContext()`
- set the context's sessionIdContext (this is the FIX)
- remove options.secureProtocol default 'SSLv23_method' (that's the node.js default since iojs)
- remove `secureOptions | constants.SSL_OP_NO_SSLv2 | constants.SSL_OP_NO_SSLv3`
- SSL v2 and v3 were removed from node.js in since io.js
- remove crypto.createCredentials (deprecated)
Checklist:
=> set tls.sessionIdContext property

config/spamassassin.ini, plugins/spamassassin.js
- possibility not to merge SpamAssassin headers' into the message
Checklist:
=> Added option to bypass SpamAssassin headers' merge

contrib/bsd-rc.d/haraka, contrib/bsd-rc.d/p0f
A couple things have made this necessary: node depending on a shared libuv, and FreeBSD 11 having more async rc.d behavior. Without this change, the Haraka startup script can get called before ldconfig, resulting in this error:
`Shared object "libuv.so.1" not found, required by "node"`
=> updated BSD rc.d REQUIRE targets

appveyor.yml, configfile.js, outbound.js, plugins.js, tests/config.js, tests/installation/node_modules/test-plugin/package.json, tests/plugins.js, tests/plugins/access.js
This PR (and already published updates to haraka-test-fixtures) fixes all but two [test failures of Haraka running on Windows](https://ci.appveyor.com/project/msimerson/haraka-pa8a5). The two failing tests are failing (see error below) when npm attempts to require a package.json's `main` property. It seems to be treating the `\` characters in the path as escape sequences, and thus fails to properly load the target file. I've run out of time to determine why that's happening.
* remove grunt from appveyor
* get redis up and running on appveyor
* get access config overrides working on windows
* clear env.HARAKA by setting to empty string
* plugins.get_timeout: DRY refactor
* use path.basename for package.json filename detection (vs regex)
````
plugins
✔ plugin - new Plugin() object
✔ …
```
=> fixes for file paths on Windows

plugins/spf.js, tests/plugins/spf.js
which has been broken since #1528
the money shot is line 210: spf = new SPF();
- fixes many of the tests, which have been broken since `if (!host) return next();`
- adds a mock transaction, restoring functionality to even more tests
- adds transaction.results, enabling them newly running tests to complete
- loads a default config, which sets up the cfg object completely, so that more tests can succeed
- merged a bunch of redundant new Address() calls into a variable
- adds a new test, for context=myself, relaying=true, and connection.remote.is_private=true
- set the mock plugin's timeout property, as without it, tests timeout before evaluation can complete
- re-initialize the SPF library before second evaluation, fixing the `context=myself` feature. …
=> spf fix for relaying & context=myself

plugins/connect.p0f.js
For loopback IPs, haraka currently logs:
````
[ERROR] [connect.p0f] no p0f results
[ERROR] [1] [connect.p0f] no p0f note
````
Because there is no p0f data. Don't bother attempting p0f on private IP space.
Checklist:
=> skip p0f on private IPs

plugins/rspamd.js
Fixes issue reported by 'last1' on rspamd IRC channel.
- Don't crash if response from rspamd couldn't be parsed
Checklist:
=> Handle unparseable responses from rspamd

plugins/spf.js
=> Skip SPF check for outbound mail when context is not 'myself'

config/dkim/dkim_key_gen.sh
Fixes #1767 
- add a BIND compatible folded DKIM key 
- remove deprecated DomainKeys instructions
````
$ ./dkim_key_gen.sh example.com
Generating RSA private key, 2048 bit long modulus
.+++
........................................................+++
e is 65537 (0x10001)
writing RSA key
$ cat example.com/dns 
Add this TXT record to the example.com DNS zone.
jan2017._domainkey    IN   TXT   v=DKIM1;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6zHpE5XCsmePfOuBHs871yUgNu+gTMytJ+55HipUl7Uem6uD4zcZAgflSrP7lgJKgrZC1WNJn5hlv7t3NiyurEGRrhCy/V2k4Xm87mGO00ZMFHd5Zq/EFshmtFIX9dOPc4am12Mdmyri7tpc2ap961EGBOR8w8HCWZCh7fjX2zV5IM7DP2eNnXM6uOBYwGsYDIGp8ul0i3z9aKoMvzDbv/9yauFDKsQrsAFi5opkf99XDki2DP4qNTog+LG1a7ixpZHTiuS44KkSkz5P4GVSfzgJ+DUJaxyki5pIPaKYWS/faOO3B0uu0uaXlXD …
```
=> add a BIND compatible folded key syntax

config/rate_limit.ini, config/tls.ini, docs/plugins/rate_limit.md, docs/plugins/redis.md, plugins/greylist.js, plugins/rate_limit.js, plugins/rcpt_to.routes.js, plugins/redis.js, tests/plugins/rcpt_to.routes.js, tests/plugins/redis.js
The redis plugin has three personalities:
1. add `redis` to config/plugins and at startup, the redis plugin connects to the redis server and leaves a shared db handle at `server.notes.redis`. This shared redis handle is used by the results store, the tls plugin, and any plugins that `inherit('redis')` without specifying a DB ID in their config.
2. As a base class for other plugins to inherit. This is how it has been used by rcpt_to.routes and the karma plugin. The redis plugin exports `merge_redis_ini()` and `init_redis_plugin()` which are used solely by plugins to populate their redis connection settings and establish the redis connection when Haraka starts up.
3. As a pub/sub agent helper. The result_store publishes all results as plugins emit them. Other plugins can subscribe to those …
=> Redis consistency

plugins/rate_limit.js
Updated logic to address case where Redis deletes record between get and incr.  If incr creates a new record, make sure it also has a TTL.
Fixes #1757 
Checklist:
=> Rate_limit_fix

package.json, tests/plugins/access.js, tests/plugins/bounce.js, tests/plugins/clamd.js, tests/plugins/data.headers.js, tests/plugins/deprecated/relay_acl.js, tests/plugins/greylist.js, tests/plugins/mail_from.is_resolvable.js, tests/plugins/rcpt_to.host_list_base.js, tests/plugins/rcpt_to.in_host_list.js, tests/plugins/rcpt_to.ldap.js, tests/plugins/rcpt_to.qmail_deliverable.js, tests/plugins/rcpt_to.routes.js, tests/plugins/relay.js, tests/plugins/spf.js
- a finger friendlier way to handle tests
- that happens to mirror the way we use it in the code base (results, not result_store).
=> use shorter results path

tls_socket.js
This causes problems because the secureContext ends up being used by
Haraka in server and client mode. Currently, the server mode loads
TLS keys as part of the context in (plugins/tls_socket). The client
mode does not load keys (in smtp_client.js). This discrepancy causes
tls connections to fail when there is an incoming mail immediately
followed by an outgoing mail.
=> Do not create a top level secureContext

plugins/dnswl.js
Fix a transposed pair of lines in `plugins/dnswl.js`
```javascript
plugin.load_dnswl_ini();
plugin.inherits('dns_list_base');
```
`plugin.load_dnswl_ini()` attempts to use inherited methods, which aren't yet present.  A line swap fixes it.
=> swap lines to fix missing inherited methods

bin/haraka, plugins/limit.js, plugins/redis.js, server.js
- now that we're using a comparison operator `e.errno == 2`, it reveals that the correct errno is -2 
- remove a bit of debugging code that missed getting purged
- more verbose error logging when copyFile/Dir fails
- remove redis & limit stubs (they take precedence over the npm packaged plugins)
Checklist:
=> fixing one bug hilighted another

config/auth_flat_file.ini
With the new config loading feature, whereby local config files are merged onto the included config files, having valid sample credentials in that config file has the potential to turn Haraka instances into open relays when the admin enables the `auth_flat_file` plugin.
- comment out the example entry
=> comment out working test sample auth user

package.json
closes #1801
(nodemailer-3-requires-node-6)
=> add nodemailer to greenkeeper ignore

attachment_stream.js, mailbody.js, transaction.js
This is basically some belt and braces around short attachments sent in one TCP packet.
It has been running on emailitin.com for a month or so, with no adverse effects, I just don't have feedback on whether it fixed the issue or not - I was unable to replicate it (it requires major full control of the sending SMTP client library at the TCP level), and the customer who had the problem left the service. But I think we should merge it anyway.
=> This may or may not fix issues with short attachments.

.travis.yml
This just makes Travis faster. Newer modules update the cache so it's pretty safe.
=> Cache the node_modules folder

connection.js, plugins/dkim_verify.js, plugins/rspamd.js, plugins/tls.js
- populate additional results params
- required for the next version of watch, which gets all its data via redis pub-sub.
- it cannot traverse the connection/transaction objects to collect details
- normalizing the connection properties (local, remote, tls, hello) helped make this really clean
Checklist:
=> more results

docs/plugins/rspamd.md
The documentation says that the `check.authenticated` setting should be set to `false` if you want to check the authenticated messages. However, this is the exact opposite of what the plugin does. The setting should be set to `true` if authenticated messages need to be checked.
- Fixed documentation error for the 'check.authenticated' setting in the Rspamd plugin
Checklist:
=> Fixed documentation error for the 'check.authenticated' setting in the Rspamd plugin

config/helo.checks.ini, docs/plugins/helo.checks.md, plugins/helo.checks.js, tests/plugins/helo.checks.js
* rename config setting mismatch to host_mismatch
* there are 3 mismatch functions
* with a backwards compat config shim
* comment out boolean config settings
* their defaults are already defined in the plugin
* build the config.booleans from the global `checks` array
* removes bunch of redundant tokens
Fixes #1832 
Fixes msimerson/Mail-Toaster-6#202
Checklist:
=> helo.checks: bring plugin into alignment with docs

plugins/rspamd.js, tests/plugins/rspamd.js
* added `wants_headers_added()`
=> rspamd: refactor complex condition into function

smtp_client.js
it prevents zillions of "SMTP connection timed out" errors in the logs
fixes msimerson/Mail-Toaster-6#205
* s/this/client/ for readability
* reduce indent
* only reset arguments with defaults when undefined (vs setting to themselves from a ternary when defined)
=> smtp_client: set idleTimeout to 1s < pool_timeout

smtp_client.js
similar to #239, but in this case remoteAddress is frequently undefined even when the connection is healthy and proceeding normally. This just removes the unsightly error message I added in #1397.
fixes #1835
=> ignore undefined socket.remoteAddress

README.md
which has links to:
- the Plugins doc in the manual
- the how to write a plugin wiki page
- the plugin template.
=> URL to Plugins is 404, point to newer Plugins.md

config/rcpt_to.qmail_deliverable.ini, docs/plugins/queue/smtp_forward.md, outbound.js, plugins/queue/smtp_forward.js, plugins/rcpt_to.qmail_deliverable.js, tests/plugins/queue/smtp_forward.js, tests/plugins/rcpt_to.routes.js
This is progress on #1472 and it improves upon a longstanding mail routing issue that affects users of per-domain mail forwarding.
I have a bunch of `[domain.com]` blocks in smtp_forward.ini and most domains have differing forward hosts. When a transaction has recipients in domains with different forward hosts, then those subsequent recipients are sent to the wrong destination host. The `one_message_per_rcpt` option in smtp_forward just does an `RSET` between transactions to the forward host of the first recipient.
The previous workaround was to forward transactions with multiple destination hosts to the default forward host and let the smart host sort it out. See #573 and #671. That works reasonably well the vast majority of the time. The edge case is split transactions with …
=> smtp forward dest split routing

spf.js
Fixes:
``````
ip=85.9.45.137 domain=champollion.ro mail_from=postmaster@champollion.ro
found SPF record for domain champollion.ro: v=spf1 include:myhost.ro -all
found mechanism: include:myhost.ro,+,include,:myhost.ro
found mechanism: -all,-,all
SPF record for 'champollion.ro' validated OK
running mechanism: include args=+,:myhost.ro domain=champollion.ro
ip=85.9.45.137 domain=myhost.ro mail_from=postmaster@champollion.ro
discarding TXT record: google-site-verification=ikrCSa_5Gl7n9D0s0Ix8VskWko7TXFMqavE2RCmVYFI
found SPF record for domain myhost.ro: v=spf1 ip4:85.9.45.129/25 ip4:46.102.236.32/28 ip4:85.9.53.122 ip4:185.72.242.16/28 include:spf.sendmachine.info ?include:netblocks.zooku.ro -all ra=postmaster rp=10 rr=e:f exp=info.myhost.ro
found mechanism: …
=> SPF: Fix modifier regexp

docs/plugins/queue/rabbitmq_amqplib.md
Actual this is typo in plugin source - it uses "ini" file from another plugin called rabbitmq . So, in fact, no one of the plugins uses config file with name "rabbitmq_amqplib.ini" . This cause error (default values for the plugin) if you trying use the official documentation.
Fixes #
- fix typo in documentation
- 
- 
Checklist:
=> Typo in config file name

attachment_stream.js, chunkemitter.js, contrib/haraka.service, dkim.js, line_socket.js, mailbody.js, messagestream.js, outbound.js, outbound/fsync_writestream.js, plugins.js, plugins/dkim_sign.js, smtp_client.js, tests/fixtures/line_socket.js, tls_socket.js
* replace the discouraged util.inherits with `class Foo extends Bar` syntax
* this change **looks** bigger than it is, due to an additional level of indention
* chunkemitter: remove Buffer.concat shim for node < 0.7.11
* fsync_writesteam: moved into ./outbound (only required once)
* tls_socket.createServer: always set `isServer=true` (a recent merge made it conditional)
* removed test for cleartext.getCipher, it *should* always be present
Checklist:
=> replace util.inherits with class .. extends

server.js, tls_socket.js
- server/tls upgrade: remove interim TLS vars
- only emit OCSP not loaded error at startup (vs every connection)
- remove unused _controlReleased
=> tls: remove interim variables

Changes, plugins/queue/smtp_forward.js, plugins/rcpt_to.qmail_deliverable.js
- updates smtp_forward split routing from #1847
- don't require remote to split when relaying=true
- as that's harmful to MSA traffic
=> Split delivery relay

mailheader.js, tests/mailheader.js
fixes #1874
- adds a test with parens in a header
- disables naïve comment stripping
- at least until it can be implemented better (with a proper header parser)
Checklist:
=> disable naïve comment stripping

tls_socket.js
this likely fixes #1855
- if we don't get a URI from ocsp.getOCSPURI, bail out
- see indutny/ocsp#10
=> handle case where OCSP server is unavailable

plugins/clamd.js
don't emit binary characters into the logs.
- I intend to self merge and close this issue, unless someone has a good reason why binary data in the log files is actually useful.
- I'm also going to address the original issue at the other end, and tell grep to always assume the log file is ascii (`grep --text`). 
- done. [haraka/haraka-plugin-log-reader#11]
closes #1861
=> 1861 binary log

configfile.js, haraka.js, server.js, tls_socket.js
Fixes #1926
- Still allow haraka -c <path> --graceful
- Also sets graceful shutdown to shutdown in max 2xChildren amount of time it sets to shutdown.
- Shutdown gracefully now requires smtp.ini to contain `graceful_shutdown=true`.
Checklist:
=> Set graceful shutdown off by default

logger.js, outbound/config.js
Fixes #1914 
- In dump_logs() run that dumping through plugins
Checklist:
=> Run dumped logs through plugins not console

plugins/clamd.js
Fixes #1924
- If multiple hosts are listed for clamd and an "unknown result" is returned or a socket error occurs after connection, then attempt to try remaining hosts before returning DENYSOFT.
=> Allow "Unknown Result" and Socket Error to Try Next Host

outbound/hmail.js, outbound/index.js, outbound/queue.js
I don't really understand why this stuff broke.
It seems to be a bug in node's require() caching, frankly.
When loading modules they would return {} before actually
being loaded. This appears to be due to recursive requires.
This might fix #1933
Please test
Fixes #1933 - maybe
- 
- 
- 
Checklist:
=> Fixes loading outbound under cluster.

server.js
Because `sunset` is the keyword we'll grep for (if we follow our instructions) when doing a semver major release.
=> Use the  sunset keyword in version specific code blocks

logger.js
=> Remove intermediate \n chars from protocol level logs

configfile.js
Fixes #1839 
- Load logger in a setImmedate call to resolve circular deps issues
Hopefully this is a simpler fix than the one in #1839.
Checklist:
=> Load logger in a setImmediate call

outbound/hmail.js
This is the obvious fix to using an undefined var FsyncWriteStream in `split_to_new_recipients`.  If you'd prefer some other refactoring fix, then let me know.
=> Fix undefined FsyncWriteStream var

mailbody.js, tests/mailbody.js
This copes with filename="d'euvre"
Fixes #1956 
- Drop support for filename='foo' which isn't RFC compliant anyway
Checklist:
=> Be more strict in attachment filename matching

connection.js, outbound/hmail.js, package.json, plugins/queue/smtp_forward.js, plugins/queue/smtp_proxy.js, smtp_client.js, transaction.js
Fixes #1864 
- Uses a flag in the new (unreleased as of today) address-rfc2821 which allows you to ask for the punycode domain if it's there. 
- I should probably also just enable SMTPUTF8 capabilities with this PR. Thoughts?
Checklist:
=> Use punycode domain

package.json, plugins/dkim_sign.js, tests/plugins/dkim_sign.js
New module supports Groups, which have no host method
Fixes #1969
=> Support the new address-rfc2822

plugins/queue/rabbitmq_amqplib.js
When connecting to RabbitMQ with username or password
containing special characters connection was refused.
- wrap `username` and `password` in connection string with `encodeURIComponent()`
=> RabbitMQ: fix encoding of user and password when creating connection

.travis.yml, appveyor.yml, package.json
- drop node.js v4 support
- add node.js v6 testing
- add node.js v7 testing
=> require node LTS version (6+)

plugins.js
the prefix is not required in config/plugins as the message states, but it is required for an NPM packaged plugin that requires another NPM packaged plugin. It is then spurious.
=> remove logging line

docs/plugins/queue/smtp_forward.md
=> doc: add note that smtp_forward only supports STARTTLS

outbound/hmail.js, outbound/index.js, package.json
Fixes #2008 
- in `outbound/*`, drop import of `constants` from node
- in favor of declaring WRITE_EXCL in `haraka-constants`
- An alternative solution to #2009 
- Closes #2009 
- Fixes #2008
Checklist:
=> use WRITE_EXCL from haraka-constants

outbound/hmail.js
Fixes a crash when handling an email for a non-existing user. This came up after getting over the first crash related to this case: https://github.com/haraka/Haraka/pull/2011
Not entirely sure if this is the correct fix, as it was not clear to me what the "todo" item would be.
=> build_todo() is part of the outbound/index.js api

.travis.yml
now that node 8.2+ is on Travis
=> require node 8 tests to pass

plugins/auth/auth_base.js, tests/plugins/auth/auth_base.js
When sending the following sequence of commands, the auth plugin fails
since it tries to decode an undefined value as base64:
AUTH LOGIN Z2lyaXNo
334 UGFzc3dvcmQ6
AUTH LOGIN
500 Unrecognized command # at this point plugin has failed
Fixes #1999
Fixes #
- 
- 
- 
Checklist:
=> Fix auth plugin failure when re-selecting auth method

outbound/hmail.js
Create logging methods in Outbound similar to Connection so that UUID is reported in log and it is easier to isolate and track outbound e-mails during high concurrency.  
Helps with debugging #1954
=> Improve logging UUID tracking in Outbound

docs/tutorials/SettingUpOutbound.md
The swaks test command in the tutorial for outbound email has the to and from addresses reversed.  I'm creating this pull request so nobody else wonders why their server is timing out trying to reach example.com's ip
Checklist:
=> Fixed swaks test command

plugins/auth/auth_base.js, tests/plugins/auth/auth_base.js
A successful login leaves the connection.notes.auth_login_*
properties set. When an AUTH LOGIN command is sent again, the state
of those variables confuses the code.
The fix is to reset the state variables after an AUTH LOGIN flow.
Fixes #2038
Checklist:
=> Fix crash when 'AUTH LOGIN' is sent after a successful auth

config/log.ini, logger.js, tests/logger.js
- support INFO *and* LOGINFO as config settings
- switch default log level to INFO
=> support INFO *and* LOGINFO as config settings

Changes.md, plugins/tls.js, server.js
- plugins/tls needs to call load_tls_ini from tls_socket (not net_utils)
- related to haraka/haraka-net-utils#23
Checklist:
=> Use tls socket ini

tls_socket.js
- when generating a dhparams.pem file, assure filePath is set
=> dhparams: use filePath, b/c cfg unset

docs/Plugins.md, haraka.js
An alternative to #2025. Per @baudehlo suggestion in #2024, this just disables graceful for SIGTERM. That way a `kill $PID` does what admins expect (kill it!) and a `kill -s INT` will do a graceful shutdown.
Fixes #2025 revert additions of graceful code
Fixes #2024 Remove or rework graceful shutdown code
- add comment referencing #2024
- disable graceful shutdown for SIGTERM.
Checklist:
=> disable graceful for SIGTERM

.travis.yml, outbound/client_pool.js, outbound/fsync_writestream.js, outbound/hmail.js, outbound/index.js, outbound/queue.js, outbound/timer_queue.js, outbound/tls.js, package.json
- enable lint for outbound/*.js
- whitespace fixes
- remove redundant module loads
- move ./timer_queue to outbound/timer_queue
- remove nodemailer from greenkeeper ignore (we already upgraded to nodemailer latest)
=> outbound cleanups

outbound/client_pool.js
an extra space was introduced in #2063 that can cause this error:
````
Sep  3 00:00:13 haraka haraka[34459]: [NOTICE] [EDC25C6E-06CC-4C99-91E1-5B556B6B6800.1.1] [outbound]  delivered file=1504422013493_1504422013493_0_34459_t5u025_2_haraka domain=vmware.imac27.simerson.net host=172.16.15.15 ip=172.16.15.15 port=24 mode=LMTP tls=Y auth=N response="<postmaster@vmware.imac27.simerson.net> 8OLqHn2oq1mjhwAAkzG9Ng Saved" delay=0.255 fails=0 rcpts=1/0/0
Sep  3 00:00:13 haraka haraka[34459]: [CRIT] [-] [core] [outbound] Releasing a pool (outbound:: 24:172.16.15.15:undefined:50) that doesn't exist!
Sep  3 00:00:43 haraka haraka[34459]: [INFO] [-] [core] [outbound] [outbound::24:172.16.15.15:undefined:50] dispense() clients=0 available=0
Sep  3 00:00:43 haraka haraka[34459]: [ERROR] [-] [core] …
```
=> outbound: remove inadvertent space

Changes.md, config/lmtp.ini, docs/plugins/queue/lmtp.md, docs/plugins/queue/quarantine.md, outbound/index.js, plugins/queue/discard.js, plugins/queue/lmtp.js, plugins/queue/qmail-queue.js, plugins/queue/quarantine.js, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js, transaction.js
**Background:** the smtp_forward plugin has support for selective forwarding. During the recipient phase, if the smtp_forward plugin acknowledges a recipient, it also specifies which forward path (smtp_forward or outbound) the transaction should take by setting transaction.notes.queue = [outbound | smtp_forward]. (See also #1472)  This works well for me. I smtp_forward a subset of mail to various servers and deliver the rest via outbound.
**Hopes:** Now I want to deliver a portion of that forwarded mail directly to dovecot via LMTP. Since dovecot doesn't know about legacy aliases, forwards, autoresponders, and lists, only a subset of messages can get routed via LMTP.  My qmd plugin knows the difference and can make the determination.
**The Problem:** There are two confounding factors:
1. …
=> transaction.notes.queue

Changes.md, plugins/queue/discard.js, plugins/queue/lmtp.js, plugins/queue/qmail-queue.js, plugins/queue/quarantine.js, plugins/queue/smtp_forward.js
- moves the "desired queue" location from queue to queue.wants
- use notes.get() and notes.set()
Checklist:
=> notes.queue -> notes.queue.wants w/get&set

mailheader.js, tests/mailbody.js, tests/mailheader.js
Fixes a bug found by an emailitin.com user.
Basically this header:
```
Content-Disposition: attachment; \r
filename*0="marketron_lbasubmission_FTA Cricket Brentwood 3006445\r
Jackso"; filename*1="n TN_08282017.xlsx"\r
```
Would cause Haraka to fail to properly process the header.
Checklist:
=> Fix rfc2231 parsing code to cope with continuation

Changes.md, tls_socket.js
Fixes #2108
- only apply default tls key/cert paths when undefined in tls.ini
- permit dhparams.pem file to be in a directory
=> only apply default tls key/cert paths when undefined

.travis.yml
Yay, we don't need these any more. This will speed up builds by quite a bit.
=> Travis ubuntu now has new enough gcc

connection.js, package.json, plugins.js, tests/outbound.js, tests/plugins.js, tests/server.js
- move connection states into haraka-constants
- use shorthand version of states
- after tests run, delete the process.env.* they manipulate
I moved the connection state constants into haraka-constants because they created race conditions in the test suite. Especially [right here](https://github.com/haraka/Haraka/blob/afd53239fb76e8818791e8f7cdb273ffa45b4865/plugins.js#L14). The symptom was: `./run_tests tests/server.js` would work fine on its own, but when run after other tests, blow up upon disconnect because `states` in plugin.js wasn't defined.
I also discovered a little bug in plugins.js that this fixes:
`if (object.state >= states.DISCONNECTING)`
That may not have worked as intended because `states.DISCONNECTING` didn't exist. In connection.js …
=> move connection states into haraka-constants

plugins/auth/auth_base.js
#2129 -  Replace all string concatenations to template literals on auth_base.js
file.
Fixes #2129 
- 
- 
Checklist:
=>  #2129 -  Replace all string concatenations to template literals on auth_base.js

plugins/data.rfc5322_header_checks.js
Replace all string concaternation with template literals on plugins/data.frc533_header_checks.js  file
Fixes #2129 
Checklist:
=>  Replace all string concaternation with template literals on plugins/data.frc533_header_checks.js  file

plugins.js
Fixes #2167
This is a really strange one - something changed in core between 2.8.14 and 2.8.16 that broke the handling of disconnects but I'm not sure exactly what (as the code here hasn't changed for 2 years).
Currently master is so broken, that if you send a QUIT - it doesn't actually end the socket and hook_disconnect is *never* run, so this is a pretty serious bug.
I've had this running on my new trap for a few hours without issue.
=> Fix disconnect hooks

connection.js, tests/connection.js
replace 3 multiline ternaries with `get_remote()`, which does the needful.
=> connection: replace 3 ternaries with get_remote()

tls_socket.js
Changes #2133 
- ES6: Replace current classes with ES6 classes on tls_socket module
- Replaces es5 functions with fat arrow functions
Checklist:
=> tls_socket: Replaced previous classes with es6 classes

Changes.md, connection.js
Set connection.remote.is_private automatically whenever connection.remote.ip is set.
I noticed that when a host uses XCLIENT, the is_private property isn't set, so reflects the original value - rather than just settings it in xclient.js, I decided it made more sense to do it automagically so there's no way it can happen elsewhere.
Checklist:
=> Set remote.is_private automatically when remote.ip is set

dkim.js
Fixes #2133 
- Convert the current classes in dkim module to ES6
Checklist:
=> dkim: converted classes to ES6

mailbody.js, tests/mail_specimen/base64-root-part.txt, tests/transaction.js
Fixes #2180 
- Fixes issue when base64 is passed as a mutliline string to the decode function (when a `text/*` part is encoded as base64)
Checklist:
=> Base64 encoding

Changes.md, docs/Outbound.md, docs/Transaction.md
Fixes #2220
- Link references to `Address` objects to the node module behind them.
Checklist:
=> Fix docs for `Address` objects

connection.js, tests/connection.js
- ~~default to os.hostname() when config/me does not exist~~
- previously, if config/me didn't exist: `220 null ESMTP Haraka 2.8.16 ready`
- replace most concat strings with template literals
- replace some anon callbacks with arrow functions
Checklist:
=> connection: set this.local properties

plugins/clamd.js
Fixes #2129 
- Replace string concatenations with template literals in clamd.js
Checklist:
=> Replace string concatenations with template literals in clamd.js

connection.js
Fixes #2129 
- Use template literals for connection.js
- Use `string += another` instead of `string = string + another`
Checklist:
=> Use template literals for connection.js

outbound/index.js
#2129 
- Replace string concatenations with template literals in outbound/index.js
Checklist:
=> Use template literals in outbound/index.js

outbound/hmail.js
There's one thing I wasn't sure about - long strings that were split into multiple lines. I joined them into one line since leaving string concatenation in seemed to defeat the purpose. Let me know if you'd prefer me to split them. 
Checklist:
=> Use template literals in outbound/hmail.js

plugins/spamassassin.js
Replace string concatenations with template literals in spamassassin.js
=> Replace string concatenations with template literals in spamassassin.js

docs/CoreConfig.md, server.js, tests/server.js
Fixes #2268
- SMTPS port is now configurable using the `smtps_port` option in smtp.ini
- Fix get_smtp_server test (it is incorrectly passing now)
Checklist:
- [ X ] docs updated
- [ X ] tests updated
- [ X ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated
=> SMTPS port

logger.js
Fixes #
- Refactor logger.js to change all string concatenations to template literals.
Checklist:
=> replaces string concaternation with template literals on logger.js

bin/dkimverify
updates #2129 
- Use template literals in bin/dkimverify
Checklist:
=> Replace string concatenations with template literals in bin/dkimverify

mailbody.js
updates #2129 
- Replaces string concatenations with template literals in mailbody.js
Checklist:
=> Replaces concatenations with template literals in mailbody.js

connection.js, dkim.js
- correct a crasher due to destructuring assignment's lack of null handling
- add missing `${}` around a string literal
fixes #2286
=> dkim: revert destructuring assignment, it handles null badly

plugins/data.headers.js
Fixes #
This plugin was logging errors for valid Mailing-list emails.
- added googlegroups
- changed logerror to logdebug for "mlm start miss". Emails from a yahoogroups list would be logged as an error.
Checklist:
=> Changed logerror to logdebug

tls_socket.js
- restore SNI functionality by always calling get_certs_dir()
- emit a count of TLS certs found in config/tls
Checklist:
=> restore SNI functionality, emit count of TLS certs

plugins/greylist.js
Fixes #
- Resolve unnecessary log entries. This plugin was creating a log entry for every greylist DB key that was promoted to white, even when err2 was equal to null.
Checklist:
=> fixed issue with logging redis DB errors

outbound/index.js
- minor change to append tx uuid to outbound queued message to behave same as other queuing plugins
Checklist:
=> Adding tx UUID to "250 Message Queued"

docs/plugins/queue/smtp_forward.md
Fixes #
- corrected spelling of config/host_list
=> Corrected config file name in docs

outbound/mx_lookup.js
I've found problem when working with Docker DNS system - please see https://github.com/docker/libnetwork/issues/2026 
Since docker implements only basic records, it responds to any MX request with NXDOMAIN (ENOTFOUND at node) so it is basicaly impossible to create two communicating containers with haraka. It is bug of Docker only (I have not seen any other DNS servers doing same thing) so please close if you think Haraka should remain strict at this...
Checklist:
=> Adding ENOTFOUND to also check A record

server.js, tls_socket.js
Currently, if dhparam.pem is missing, it is autogenerated. If Haraka is started in cluster mode, each process generates the file.
* This change restricts the autogeneration to the master process so it's only performed once.
* and arranges a few deps in source/alpha order
=> only generate dhparam.pem once

Changes.md, docs/Outbound.md, outbound/hmail.js, outbound/index.js
Right now when bounce is generated there is no easy way to connect newly generated transaction with original so I've added new option to send_email that will be passed to log calls.
- new "origin" option at outbound.send_email
- updated HMailItem to generate bounce with this option
Checklist:
=> Add "origin" option to outbound.send_mail for better bounce tracking

smtp_client.js
I found this issue when tracing a problem in some code where I was using smtp_client.
I had a case of an SMTP host that was down, but my `smtp_client.on('error')` code block was not being called and therefore `next()` wasn't being called, so the plugin always timed out instead of being correctly trapped.
The issue was that the `switch()` block would always call `client.destroy()` which would in turn set the state to `STATE.DESTROYED` so the `if (client.state === STATE.ACTIVE)` would never ever be true.
I've therefore re-ordered the statements and removed the return as calling `client.destroy()` should not do any other harm.
This fixed my issue.
Checklist:
=> Fix smtp_client error handling

package.json, tls_socket.js
- used in tls_socket.js. Required by the TLS cert dir that extracts cert data from the .pem files.
- it should have come over with the TLS consolidation to tls_socket.js
- syntax cleanups in tls_socket.js
=> add openssl-wrapper as dependency

smtp_client.js
introduced in #2323 
A bunch of `function () {` statements were updated to arrow functions. Because arrow functions alter the meaning of `this` within an arrow function (usually for the better), it interferes with smtp_* plugins ability to call `next()`.
=> revert a conversion to arrow function

Changes.md, docs/plugins/queue/smtp_forward.md, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js
Fixes #
enable_outbound can be set per domain
When haraka is managing multiple domains, it is sometimes desirable to use the mail relay only for specific domains. By making the enable_outbound flag per domain, we can disable the relay and use Haraka's internal MX based delivery.
Checklist:
[X] docs updated
[X] tests updated
[X ] Changes updated
=> smtp_forward: enable_outbound can be set per domain

config/me, connection.js
- default to os.hostname() when config/me does not exist
=> connection: assure hostname is set

line_socket.js
should be reviewed by @baudehlo
- Near as I can tell, despite this function being attached to the socket object, it is never called from outside `setup_line_processor()`. If my cursory check is representative, exporting those functions has served only one purpose over the years: unnecessary function calls on the stack.
- Note: there are functions with exactly the same names in connection.js and outbound/index.js. However, those are independently defined and accessed. A secondary use of these intermediate functions has been an additional namespace collision. I have therefore renamed them.
=> line_socket: remove superfluous function

docs/CoreConfig.md
This adds documentation for [`force_shutdown_timeout`](https://github.com/haraka/Haraka/blob/master/server.js#L45) as well as [`graceful_shutdown`](https://github.com/haraka/Haraka/blob/master/server.js#L116) found in the code, but not in the config. Please let me know if I got the meaning of those settings wrong.
=> document force_shutdown_timeout and graceful_shutdown

Changes.md, docs/plugins/queue/smtp_forward.md, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js
this config variable can be set to rcpt_to or mail_from to decide how the domain configuration is chosen
Fixes #2346
- add domain_selector config variable that chooses domain configuration based on mail_from or rcpt_to domain
Checklist:
- [ X ] docs updated
- [ X ] tests updated
- [ X ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated
=> smtp_forward: add domain_selector

plugins/auth/auth_base.js
Just fixes a simple typo. VXNlcm5hbWU6 decodes to Username: and not UserLogin:
=> Fix typo in comment

connection.js, plugins/max_unrecognized_commands.js
Plugins expect the last parameter cmd/params to be an array and not a string.
If an empty command is passed, tls plugin fails because it expects the argument
to be an array:
[CRIT] [3DD21EB3-057C-445B-9345-CDA7552D6BE0] [core] Plugin tls failed: TypeError: Cannot read property 'toUpperCase' of undefined
at Plugin.exports.upgrade_connection (/app/haraka/plugins/tls.js:93:18)
at Object.plugins.run_next_hook (/app/haraka/plugins.js:506:28)
at callback (/app/haraka/plugins.js:464:32)
at Plugin.exports.hook_unrecognized_command (/app/haraka/plugins/max_unrecognized_commands.js:27:12)
=> Ensure unrecognized_command hooks are invoked with params as an array

outbound/hmail.js
As per IRC channel.  This fixes any MX list where a socket path is specified (e.g. LMTP).
=> Fix handling of LMTP sockets

docs/CoreConfig.md
The link to "cluster" on http://haraka.github.io/manual/CoreConfig.html currently links to `http://learnboost.github.com/cluster/%20or%20node%20version%20%3E=%200.8`. This makes it link only to `http://learnboost.github.com/cluster/` as originally intended.
=> fix link to cluster in coreconfig docs

plugins/queue/qmail-queue.js
I noticed eslint barking about `err` being undefined, and that's because it was. This fixes it.
=> qmail-queue: fix undefined err variable

Changes.md, connection.js, tests/connection.js
This is an alternative implementation of Steve's excellent idea in #2387, which is making sure that when relaying is set in a transaction, that it's automatically unset when the transaction ends.
Checklist:
=> connection: make setting relaying in a transaction safe

outbound/index.js, outbound/queue.js
On non-win platforms, dotfiles begin with `__tmp__` (per qfile.js). This was not matched by the regexp.
=> Fix dotfile cleanup to consider platform-based prefix.

Changes.md, docs/Outbound.md, outbound/index.js
closes #2409
fixes #2406
- outbound: support received_header=disabled
Checklist:
=> outbound: support received_header=disabled

mailbody.js, outbound/client_pool.js
- lower log level on invalid CTE (seems like foreign spam likes it)
- outbound/client_pool.js: include outbound client ID into quit logstring, otherwise you can't know what client from the pool sent the QUIT.
=> lower log level on invalid CTE, outbound client ID

Changes.md, bin/haraka, docs/CoreConfig.md, plugins/auth/auth_base.js, plugins/auth/auth_proxy.js, plugins/spf.js, smtp_client.js
closes #2380 
- create config/me if not present
- use platform dependent os.EOL instead of \n (in config/me and config/host_list)
- grammar fixes in docs/CoreConfig.md
- use config.local.host when connection in scope
Checklist:
=> create config/me if not present

Changes.md, plugins/auth/auth_base.js, tests/plugins/auth/auth_base.js
Allow supplying custom message and status codes to passcheck callback routine. We "hijack" `message` param for that, maintaining backwards compatibility in case it's a plain string message.
Checklist:
=> mods to auth_base plugin

plugins/tls.js
=> lower log level for inbound TLS timeout: way too common occurrance

connection.js, transaction.js
* Basically, this patch adds more info to notes object, like:
* `connection.notes.proxy` , for remotes that use PROXY proto
* `transaction.msg_status.(rejected|tempfailed|accepted) = true`, for ex., for consequent logging into ES 
* Don't add anything to queue results if queue hook returned CONT (that probably means we want next queue hook to fire, which will populate the results with delivery info)
* Fix "queued" messages, so that we don't get ($uuid)($uuid) duplicates and such
* fixes #2403 , where we don't just ignore denysoftdisconnect on unrecognized_command
Checklist:
=> mods to transaction.js & connection.js

connection.js, outbound/hmail.js
To get the ball rolling in #2434 , here are a couple of commits.
=> Lowering log levels

plugins/relay.js, tests/plugins/relay.js
Since relay plugin uses `connect` hook and is last due `next(OK)` if relaying there is no easy way to know that IP is relayed before communication begins.
I have moved `acl` method to connect_init hook to just make relaying flag accessible earlier and created `pass_relaying` hooked to `connect` so it will work same as before. 
Checklist:
=> Divide relay.acl() between two hooks 

connection.js, docs/CoreConfig.md, mailbody.js, transaction.js
Fixes a privately disclosed security vulnerability
- Limit mime parts to 1000 max.
Checklist:
=> Attempt to mitigate mime part explosion attack

outbound/hmail.js
Fixes:
- "hidden" rcpt_tos in html bounce due < brackets >
- XSS via email is AFAIK impossible (clients will parse out scripts) but bounce content can be damaged with some chars
- move bounce values to top and for html template replace with escaped variables
Checklist:
=> Escape values in html bounce properly

Changes.md, plugins/dkim_sign.js, tests/plugins/dkim_sign.js
fixes #2450
- improve debug log results
- wrap address-rfc2822.parse in a try to catch exceptions
- add test coverage
Checklist:
=> dkim_sign: handle exception when address-rfc8222 fails to parse

Changes.md, config/tls.ini, outbound/hmail.js, outbound/queue.js, outbound/tls.js, plugins/tls.js, tests/outbound/index.js, tls_socket.js
* outbound: TLS NO-GO feature that "downgrades" to unsecure when remote host is misbehaving during TLS session
Checklist:
=> add outbound TLS NO-GO feature

outbound/hmail.js
Fixes #2469 
- when LMTP delivery fails with 4* or 5* and `ok_recips.length === 0` no delivered hook should be called (success=false)
Checklist:
=> Don't run delivered hook on LMTP fail

Changes.md, plugins/dns_list_base.js, tests/plugins/dns_list_base.js
- introduce global plugin.lookback_is_rejected flag that allows dnsbls that answer on silence testpoint to function.
Some dnsbl (hostkarma.junkemailfilter.com) return so-called blocked status on queries to 127.0.0.1. This change allows such zones to continue functioning.
In your dnsbl plugin:
```js
plugin.inherits('dns_list_base');
plugin.load_config();
plugin.lookback_is_rejected = plugin.cfg.main.lookback_is_rejected;
```
This will need a proper per-zone solution some day.
Checklist:
=> mods to dns_list_base plugin

plugins.js
Finally tracked down a long standing annoyance that I've had with TLS.   If the client drops the connection after TLS negotiation fails, then the hook timer is never cancelled and you end up with a load of 'plugin tls timed out on hook unrecognized_command' messages in the logs.
=> Clear timeout on cancel

Changes.md, plugins/dkim_sign.js, tests/plugins/dkim_sign.js
Log messages before:
````
[ERROR] [-] [dkim_sign] skipped: no dkim private key
[INFO] [BDE4364C-CB43-4A13-9E1C-EC8E4E6176A3.1] [dkim_sign] signed for simerson.net
[INFO] [CB12CF81-2224-433B-B327-68DA69F3D2C7.1] [dkim_sign] signed for tnpi.net
[INFO] [-] [dkim_sign] signed for tnpi.net
[ERROR] [-] [dkim_sign] skipped: no dkim private key
````
After:
````
[NOTICE] [-] [dkim_sign] skipped: no private key for id.apple.com
[INFO] [CEDF1642-90A0-41BB-8CE7-962CFA37E5C5.1] [dkim_sign] signed for tnpi.net
[NOTICE] [-] [dkim_sign] skipped: no private key for sapres.org
[INFO] [25916E16-8E53-44E1-A860-18C2EF84E5B5.1] [dkim_sign] signed for tnpi.net
[NOTICE] [-] [dkim_sign] skipped: no private key for e.qvcemail.com
[NOTICE] [-] [dkim_sign] skipped: no private key for hellomerch.com
[NOTICE] [-] …
```
=> dkim_sign: reduce log severity, improve log messages

outbound/queue.js
Fixes #2494 
- Init obtls elsewhere
Checklist:
=> Init tls when we send email, not when an old queue file is loaded

Changes.md, connection.js
Possibility to hide Haraka is at your service from HELO/EHLO for security reasons.
Added the option to just hide it instead of adding your own message because this might break more than it solves. 
Excluding the "Haraka is at your service" message from HELO/EHLO message is as easy as creating a file config/ehlo_hello_exclude_haraka with the value "true" which is a standard method in this file.
Fixes #
- #1532 
Checklist:
- [na] docs updated
- [na] tests updated
=> #1532 Possibility to hide Haraka is at your service from HELO/EHLO for security reasons.

docs/plugins/queue/rabbitmq_amqplib.md, plugins/queue/rabbitmq_amqplib.js
This PR adds a new config option to `rabbitmq_amqplib`, allowing the default URI Scheme of `amqp` to optionally be replaced with `amqps` in the connection string.
- adds a new configuration option `protocol` to the `rabbitmq_amqplib` plugin
Checklist:
=> enable tls/ssl for rabbitmq amqplib plugin

Changes.md, connection.js, docs/Connection.md, package.json, tests/connection.js
- add  connection.remote.is_local flag for detecting loopback and link_local addresses
Checklist:
=> Add connection.remote.is_local

plugins/data.headers.js, plugins/data.uribl.js, plugins/messagesniffer.js, tests/mailheader.js
Fixes this graceless error:
````
Nov 13 15:26:39 haraka haraka: [CRIT] [742245BE-0DAA-40A9-A556-BF93BC9B2C8F.1] [core] Plugin access failed: Error: No results     
at Object.parse (/root/Haraka/node_modules/address-rfc2822/index.js:20:22)     
at Plugin.exports.data_any (/root/Haraka/node_modules/haraka-plugin-access/index.js:401:28)     
at Object.plugins.run_next_hook (/root/Haraka/plugins.js:508:28)     
at Object.plugins.run_hooks (/root/Haraka/plugins.js:422:13)     
at MessageStream.end_callback (/root/Haraka/connection.js:1650:21)     
at MessageStream._write (/root/Haraka/messagestream.js:137:41)     
at ChunkEmitter.<anonymous> (/root/Haraka/messagestream.js:63:22)     
at emitOne (events.js:116:13)     at ChunkEmitter.emit (events.js:211:7)     
at ChunkEmitter.end …
```
=> use get_decoded on headers that may be encoded

Changes.md, outbound/hmail.js
I've experienced "Error: We are already running hooks! Fatal error!" and "Shuting down" due haraka sending "RSET" to dovecot with specialy formatted email. It also causes infinity delivery if haraka is autorestarted (cluster maybe affected too).
```
[INFO] [-] [core] [outbound] acquired socket D954D55A-11AB-4AE4-A3EF-39ABC7550010 for outbound::24:127.0.0.1:undefined:50
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 220 mail.server Dovecot ready.\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: LHLO mail.server
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250-mail.server\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250-8BITMIME\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] …
```
=> don't send RSET to LMTP

Changes.md, docs/plugins/clamd.md, plugins/clamd.js, tests/plugins/clamd.js
- added check.authenticated, check.private_ip, check.local_ip for ability to skip some connections (same as rspamd plugin)
- depends on https://github.com/haraka/Haraka/pull/2532
Checklist:
=> add clamd check options for skipping

config/mail_from.is_resolvable.ini, plugins/mail_from.is_resolvable.js
fixes #2448
- reduce default timeout by one second (so < plugin.timeout)
- reduce timeout if its >= plugin.timeout
=> mf.resolvable: reduce timeout by one second (so < plugin.timeout)

Changes.md, haraka.js
Related: https://blog.ghaiklor.com/avoid-running-nodejs-as-pid-1-under-docker-images-when-running-them-on-mesosphere-kubernetes-or-b7bd505657f9
Like in the blog described node has some signal issues if it runs as pid 1 (usually inside a container).
Currently on docker stop docker sends SIGTERM to node which will be ignored because not handled somewhere.
Haraka on docker or even on kubernetes has to be killed unless you use workarounds like `tini`. I would prefer that haraka initiate a graceful shutdown on docker stop.
- Implement SIGTERM graceful shutdown if pid is 1
Checklist:
=> Implement SIGTERM graceful shutdown if pid is 1

Changes.md, config/plugins, plugins/early_talker.js, tests/plugins/early_talker.js
- move karma plugin to the top of config to be able to read results of karma at early talker plugin
- added code to skip connections with results karma.good > 0
Checklist:
=> skip early_talker test if sender has already good karma

Changes.md, plugins/dkim_sign.js, tests/plugins/dkim_signer.js
Fixes #2410
calculate hash from CRLF when empty body per RFC6376
Checklist:
=> Fix DKIM for empty body + test

Changes.md, config/tls.ini, docs/plugins/tls.md, plugins/queue/discard.js, server.js, smtp_client.js, tests/config/tls.ini, tests/server.js, tests/tls_socket.js, tls_socket.js
Fixes #2543 
This is largely the same as #2543 except:
- includes tests (which surfaced a couple issues)
- config setting named `requireAuthorized` instead of `authorizationRequired`
- no boolean option (simpler, easier to document)
- has support for SMTPS server (was only for STARTTLS)
- more GFM formatting in tls.ini
Checklist:
=> support requiring verified TLS certs on specific ports

Changes.md, outbound/hmail.js
Fixes #2556
There is question with this PR: do we need to send RSET after finished email? Most servers I've tested have no problem with that, RFC is clear about using it, LMTP doesn't have rset at all. But still there is maybe corner case which I don't know.
- RSET is not sent when SMTP|LMTP delivery is finished with success and we release client immediately
- if delivery ends without success then we send QUIT to LMTP and RSET to SMTP
Checklist:
=> release client when successfully finished delivery

Changes.md, tls_socket.js
Fixes #2509
- .on to .once at secureConnect event listener
Checklist:
=> prevent running secureConnect callback multiple times

Changes.md, config/spamassassin.ini, plugins/clamd.js, plugins/early_talker.js, plugins/spamassassin.js, tests/plugins/early_talker.js
I need a mechanism to skip spamassassin checks for IP based relaying clients. Haraka already has similar mechanisms for this in rspamd and clamd via their `check` config settings and the `should_check()` function. This PR (and [rspamd #13](haraka/haraka-plugin-rspamd#13)) extends `should_check()` to support relay clients.
Aside: auth clients **are** relaying clients, but relay might also be set by other plugins, such as IP lists in the `relay` plugin.
- adjust should_check logic to be flow-through
- easier to read/parse/grok and extend
- shows if a connection was skipped for more than one reason
- copy `should_check()` to spamassassin
- early_talker had similar inline checks which I refactored into `should_check()`
related to #2551  (skip …
=> adjust should_check logic, extend to spamassassin

plugins/dkim_sign.js
same as when retrieving from From header. 
related to / continuation of #2537 and #2540 and #2381
=> dkim: when extracting sender, get decoded header

Changes.md, outbound/index.js, outbound/queue.js, outbound/timer_queue.js, tests/outbound/index.js
Currently there is no way to see what is inside temp_fail_queue or delivery_queue. And even if we access content there is no way how to list TimerQueue and get some usefull info (callback variables are sadly not accessible). Future idea is to have ability to list/push/discard emails on waiting list through plugin.
- export temp_fail_queue, delivery_queue from outbound
- add id(=filename) to TimerQueue items to see what is inside temp_fail_queue
- add discard method on TimerQueue
Checklist:
=> Make outbound temp_fail_queue and delivery_queue accessible

Changes.md, tls_socket.js
permits specifying the path to a local CA root file (likely ca_root_nss, the Mozilla CA list), but could be user generated.
When not specified, the CA roots that node.js bundles is the default.
Checklist:
=> tls: support local CA list

Changes.md, server.js, tests/config/smtp.ini
Fixes #2388 
- server: warn when nodes=undefined
- default to nodes=1
Checklist:
=> server: warn when nodes=undefined

Changes.md, smtp_client.js
- when not using RE match, use test
- a slight change in functionality is passing the pool_timeout argument to SMTPClient. This permits overriding the default 300s, which kind of answers the question "are there any pool settings to close the active connection after a certain period" from #2321 
Checklist:
=> smtp_client little cleanups

Changes.md, tests/server.js
Fixes #2578
- replace `localhost` with `127.0.0.1` so nodemailer DNS resolver change doesn't break tests 
Checklist:
=> nodemailer 5 changed dns resolver, use IPv4 addr

outbound/hmail.js
Fixes bug introduced with my pull #2569 where adding to temp_fail_queue is missing filename parameter
Checklist:
=> add missing id when adding to temp_fail_queue

plugins/spf.js
- This extends the use of the skip flags in the ehlo hook
=> spf: use the skip config for helo/ehlo checks

plugins/status.js
Fixes problem where pushed emails are not actually processed due waiting items earlier at queue, see https://github.com/haraka/Haraka/blob/e9128d6dea02f3509abcb5104f796e3a9a73313e/outbound/timer_queue.js#L60-L69
Checklist:
=> Status plugin: use queued item's callback instead of setting fire_time to -1

plugins/spf.js
patch suggested by matt in PR 2590
- avoid 2nd EHLO evaluation if EHLO host is identical
=> spf: avoid 2nd EHLO evaluation if EHLO host is identical

plugins/dkim_sign.js
- plugin.logerror(...) -> connection.logerror(plugin, ...)
Checklist:
=> Log dkim_sign parse errors with connection ID

contrib/haraka.service
`systemctl start hakara.service` was hanging, but the service was started ok. This is because the process wasn't forking and does not appear to have an option to do so. 
https://superuser.com/a/1274913/117296
> a) If the service starts and keeps running, and the prompt does not return until you press Control-C or stop the service in some other way: then Type = simple is the right choice.
> b) If the prompt returns but the service keeps running in the background (i.e. the service daemonizes itself on its own), then Type = forking is the right choice.
Fixes #
Changes proposed in this pull request: none 
Checklist:
=> haraka.service: Type=simple

bin/haraka
Fixes #2617
- removing new keywoard
Checklist:
=> Connection.createConnection is not a constructor

connection.js
When I run a command like `haraka -c /data --qunstick example.com` I get back an error telling me I'm not allowed to run INTERNALCMD remotely. Combined with haraka/haraka-net-utils#40, this fixes that by extending the `is_local_ip` checks to include IPs bound to local interfaces.
Related to haraka/haraka-net-utils#40
Checklist:
=> conn: use is_local instead of localhost addr tests

package.json
in preparation for EOL on 2019-04-30
=> drop node.js v6

Changes.md, docs/plugins/spf.md, plugins/spf.js, tests/plugins/spf.js
- spf: Add config option to deny mail when no SPF record exists. This is the behaviour adopted by GMail and others.
Checklist:
=> spf: add config option to fail on NONE

connection.js
Right now you can issue `INTERNALCMD` SMTP commands without a key – even when the `internalcmd_key` file exists. This renders having an `internalcmd_key` file moot.
This pull requests rejects `INTERNALCMD` commands without a key when a key is configured.
=> Actually enforce using key for INTERNALCMD

plugins/spamassassin.js
`[spamassassin] status=No, score=-7.7, required=5.0, reject=0, tests="BAYES_99,BAYES_999,DCC_CHECK,DKIMWL_WL_HIGH,DKIM_SIGNED,\r 	DKIM_VALID,DKIM_VALID_AU,HTML_MESSAGE,LOW_PRICE,RCVD_IN_DNSWL_NONE,\r 	SPF_PASS,URI_HEX,USER_IN_DEF_DKIM_WL,USER_IN_DEF_SPF_WL"`
note the silly "\r       " plus invisible whitespace which doesn't wrap in the console/logs anyway.
`[spamassassin] status=No, score=-4.4, required=5.0, reject=0, tests="BAYES_00,DCC_CHECK,DKIMWL_WL_HIGH,DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,FROM_EXCESS_BASE64,HTML_IMAGE_RATIO_04,HTML_MESSAGE,RCVD_IN_DNSWL_NONE,RCVD_IN_RP_CERTIFIED,RCVD_IN_RP_SAFE,SPF_PASS"`
=> spamassassin: strip useless WS from tests

connection.js, logger.js, outbound/hmail.js, plugins/queue/discard.js
Fixes #2634
- conn: remove TLS version from header
- conn: suppress verify message when =FAIL (it is confusing)
- ws: clean up a few log messages
Checklist:
=> tls socket peer info

Changes.md, mailbody.js, mailheader.js, tests/mailbody.js, tests/mailheader.js
Fixes #2675 
- if body is in utf-8 then don't decode it as binary
- multiline headers are decoded after merge, not before
Checklist:
=> Fix problems with multiline encoded headers and UTF body

plugins/dkim_sign.js
goes along with #2649 
necessary update surfaced in deployment testing.
=> dkim_sign: always return props (validated later)

plugins/dkim_sign.js
Fixes #2668 
- rename property 'domain' to 'domain_name' because it is an internal reserved property name of  Stream/EventEmitter object.
Checklist:
=> Renaming reserved kw/property of 'domain' to 'domain_name'

outbound/hmail.js
Fixes #
Debug output. Currently it prints `Got an MX from Plugin: cloudron.ml => 0 [object Object]`
=> Fix debug of MX result

plugins/queue/smtp_forward.js
-  Register the mx_hook in smtp_forward plugin
- Get the domain config based on the `domain_selector` setting
=> Fix mx hook in smtp_forward

.github/workflows/ci-test-win.yml, mailheader.js
- mailheader: avoid two variable assignments
- mailheader: convert a few + concats with interpolated es6 strings
- disable github actions/workflows testing on windows node 8 & 10 (currently broken)
=> mailheader: avoid variable assignments, es6 interp. strings

Changes.md, connection.js, plugins/tls.js, server.js, tls_socket.js
Related to: #2634, #2648, and #2708 
- add cipher version back to header
- this time, use the current connections version, not the minimum supported
Checklist:
=> restore TLS version, correctly

Changes.md, package.json, spf.js, tests/spf.js, tls_socket.js
- package.json: use npx in scripts (works everywhere- locally, GitHub Actions, Travis, AppVeyor)
- tls_socket: process all entries in `config/tls dir`. Uses async.map so previous versions would abort after the first error in a TLS cert was encountered. This surfaced in Windows test where initial err aborted processing of tls dir contents.
- ignore an SPF error (when DNS lookup fails) when testing on Windows
=> use npx in package.json scripts

.eslintrc.yaml, .github/workflows/ci-test.yml, .travis.yml, appveyor.yml, package.json, tests/plugins/dns_list_base.js, tests/spf.js, tls_socket.js
- node 8 maintenance ends soon, drop it from testing
- add eslint ecmaVersion: 8 (2017), to add async/await support
- ignore a couple frequent DNS failures in tests (on GitHub Actions & AppVeyor)
Checklist:
=> add ES2017 support, drop node 8

Changes.md, docs/Logging.md, logger.js, tests/logger.js
Fixes #?
- Add a JSON format for logging
About the tests, I've basically copied what was there for `logfmt`, if some more comprehensive testing is needed, please let me know and I'll improve them.
Checklist:
=> Add the JSON logging format

config/plugins
It was subsumed into the [limit](https://github.com/haraka/haraka-plugin-limit) plugin.
Related to #2746
=> remove max_unrecognized_commands from config

plugins/queue/quarantine.js
Fixing error caused by upgrade to latest mkdirp:
```
Plugin queue/quarantine failed: TypeError: invalid options argument
2020-02-11 10:40:58.367367500      at optsArg (/usr/lib/node_modules/Haraka/node_modules/mkdirp/lib/opts-arg.js:13:11)
2020-02-11 10:40:58.367368500      at mkdirp (/usr/lib/node_modules/Haraka/node_modules/mkdirp/index.js:11:10)
2020-02-11 10:40:58.367369500      at Plugin.exports.init_quarantine_dir (/usr/lib/node_modules/Haraka/plugins/queue/quarantine.js:75:5)
2020-02-11 10:40:58.367370500      at Plugin.exports.hook_init_master (/usr/lib/node_modules/Haraka/plugins/queue/quarantine.js:17:10)
2020-02-11 10:40:58.367370500      at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:535:28)
2020-02-11 10:40:58.367371500      at callback …
```
=> Fix mkdirp to use promise api

Changes.md, config/http.ini, endpoint.js, package.json, server.js, tests/endpoint.js, tests/server.js
To better support embedded use of Haraka, this change adds support for specifying listener addresses as /path/to/some.sock[:mode], where `mode` is an optional octal permissions spec for chmod.  Removal of an existing socket is handled automatically.
This change also consolidates listening-endpoint address parsing and formatting to a single class, removing duplicated code and simplifying the setup of servers.
Checklist:
=> Allow web interface to be bound to a unix socket

Changes.md, smtp_client.js, tests/smtp_client/auth.js, tests/smtp_client/basic.js
Fixes #2788
- As discussed in the issue, the usage of the account user will now be used as well to identify a pool.
Checklist:
=> Fix connection pool not being unique when hosts and ports were equal between domains

Changes.md, config/tls.ini, docs/plugins/tls.md, outbound/tls.js, plugins/tls.js
Right now, when there's a STARTTLS failure, we note the host in redis. It connects again and we skip the STARTTLS capability in addition to clearing the `no_tls` flag in redis. Which means next time it connects, STARTTLS is advertised again and the process repeats. 
There are 2 downsides to this:
* client on win7 (tlsv1.0) connecting to nodejs >11 (min tlsv1.2 unless passed a CLI flag) will get a failure, then no STARTTLS cap (and essentially an error on the client because of missing STARTTLS cap), then rinse and repeat...
* the `no_tls|1.2.3.4` flag in redis never expires and this has potential to clash with outbound's TLS NO-GO feature where we mark remote host as TLS NO-GO for `tls.ini/redis.disable_expiry` secs. 
My proposal is to align STARTTLS with Outbound TLS blackout code. …
=> STARTTLS "TLS NO-GO" improvements

Changes.md, plugins/queue/smtp_forward.js
Fixes #2795
Fixes #
- Remove the redundant use of outbound hook
Checklist:
- [X ] docs updated
- [X ] tests updated
=> smtp_forward: remove redundant outbound hook

bin/haraka, package.json, plugins/queue/quarantine.js
Just a suggestion.
- use node v10's `fs.mkdir` rather than dependening on `mkdirp`
Checklist:
- **N/A** [ ] docs updated
- **N/A** [ ] tests updated
=> use node v10's mkdir instead of mkdirp

docs/plugins/tls.md
Fixes url of letsencrypt script in tls plugin doc
=> Fix letsencrypt url in tls.md

Changes.md, connection.js, outbound/hmail.js, outbound/index.js
Fixes #2757 
- outbound: add default for config.me in HELO
- connection: also use get_primary_host_name
Checklist:
=> outbound: default 'me'

Changes.md, bin/haraka_grep
perl version in the repo has no help and I couldn't easily deduce what it's expecting. This handy shell version works with modern Haraka logs, especially syslog, and doesn't require perl
=> replace perl haraka_grep with shell version

Changes.md, plugins/queue/smtp_forward.js, plugins/spamassassin.js
In two places it has been seen frequently, grab a ref to the connection and/or transaction, to assure it'll still be there when the plugin continues later.
Use shortened names (conn/txn) to distinguish between local ref and source (connection/connection.transaction).
Related to #2732 
Checklist:
=> connections: grab a ref, to assure it still exists later

transaction.js
- assure smtp.ini [headers] section exists for upgrades (legacy smtp.ini config w/o it). Goes with #2855
=> assure cfg.headers section exists

Changes.md, config/smtp.ini, connection.js, docs/CoreConfig.md
=> Configurable smtputf8

Changes.md, plugins.js
Fixes #2870
closes #2867
related to #2846
- plugin: strip haraka-plugin- prefix from entries in plugin config
Checklist:
=> plugin: strip haraka-plugin- prefix from entries in plugin config

Changes.md, config/smtp.ini, connection.js, docs/CoreConfig.md, plugins/mail_from.is_resolvable.js, rfc1869.js, server.js, tests/connection.js, transaction.js
Fixes #2871
- consolidate smtp.ini parsing to server.js
- passes config into connections and transactions
- move strict_rfc1869 setting into smtp.ini
Checklist:
=> consolidate smtp.ini parsing to server.js

Changes.md, plugins/tls.js
Fixes #2874
- constrain TLS no-go to port 25
Checklist:
=> exclude port 587 from TLS no-go

Changes.md, package.json
related to #2861
- require h-net-utils >= 1.2.2 with updated get_mx that doesn't return implicit MXes
- the calling functions already have handling for implicit MXes
=> require newer h-net-utils

Changes.md, connection.js, server.js, transaction.js
continues #2872
- assure config setting parses as integer
- reference the config setting consistently in conn & txn
- shed MAX_HEADER_LINES because identical config is now available in conn & txn
Checklist:
=> headers.max_lines: init as integer at startup

outbound/hmail.js
- Pass original hmail notes to new recipients split copies
=> Propagate hmail notes to split copies

.github/workflows/ci-test-win.yml, .github/workflows/ci-test.yml, .gitignore, Changes.md, package.json
- drop support for node.js 10
- use address-rfc2821 2.0.0
Checklist:
=> drop node 10 support

outbound/hmail.js
* fix bounced_rcpt parameter passed to bounce hook
See also #2899
=> fix fail_recips for bounce hook

Changes.md, config/tls.ini, tests/tls_socket.js, tls_socket.js
fixes #2693
fixes #2893
- turn off sending TLS client certificates (by default)
- add a config option to turn them back on
- add granular settings for [en|dis]abling client certs for particular hosts
Checklist:
=> tls: default to not sending TLS client cert

mailheader.js
It's too dangerous to return the header_list object without cloning it, this object should never be modified outside of this class
we could even freeze it to make sure people know what they are doing wrong
=> clone the header_list

tls_socket.js
- Remove raw certificate PEM dumping in DEBUG log level, because that also includes the private key which is highly sensitive information
Checklist:
=> Don't log TLS private keys

smtp_client.js
The space after "MAIL FROM:" and before "<" is not allowed by the syntax of RFC-5321.
Fixes #
- 
- 
Checklist:
=> The space after "MAIL FROM:" and before "<" is not allowed

Changes.md, docs/plugins/tls.md, outbound/hmail.js, outbound/tls.js, package.json, tests/config/tls.ini, tests/outbound/index.js, tests/tls_socket.js, tls_socket.js
Implemented using an ini array instead of like the [no_tls_hosts] section, so
that it can be different for outbound and inbound, for future use.
Currently does not accept wildcards like "*.example.org".
Also fixes a small bug in the "delivered" notice, where a previously TLS
upgraded socket from the pool would be logged as tls=N
- New feature: forced TLS for selected hosts
- Configuration in tls.ini outbound.no_tls_hosts[], prepared for adding inbound.no_tls_hosts[] later (and both can then take from main.no_tls_hosts[] of course)
- Bug fix: tls=N in log should be tls=Y for re-used upgraded socket from pool
- Debug feature: indicate in debug log message that a re-used socket is a TLS socket
- Bug fix: invalid SMTP codes were not treated as fatal …
=> Implement forced TLS: outbound.force_tls_hosts[] in tls.ini

Changes.md, connection.js, tests/connection.js, tls_socket.js
Fixes #2914
In the case of binding to a specific existing address, client.localAddress
should be the same as the bind address and this commit doesn't change that.
In the case of binding to a non-existing address, no client will exist until
the address does exist, and this commit doesn't change that.
Finally, in the case of binding to INADDR_ANY, the bind address is useless
information (that is: I can't think of any use case where this fact would be
useful during handling an incoming connection), and this commit changes the
value from :: or 0.0.0.0 to a value that is actually useful: the IP address on
which the incoming connection was actually accepted.
Checklist:
=> Get local_ip from getsockname() instead of server properties

Changes.md, connection.js
Fixes #2921
- connection errors logged in `connection.js` should use key-value pairs rather than stringifying data into the message
Checklist:
=> Log connection errors with logfrmt key/value pairs

plugins/dkim_verify.js
Sadly, opendmarc can't decipher "header.i" and needs "header.d" in order to work. Make it so.
Checklist:
=> put more data in AR header so that opendmarc check actually works

messagestream.js
Add a `skip_headers` option to output message body only.
This is needed for [my milter plugin](https://github.com/celesteking/haraka-plugin-milter) to work correctly without additional hacks.
Checklist:
=> messagestream header skip

plugins/spamassassin.js
Fixes:
```
TypeError: Cannot read property 'results' of null
at Plugin.exports.log_results (/code/nodejs/Haraka/plugins/spamassassin.js:353:22)
at Socket.<anonymous> (/code/nodejs/Haraka/plugins/spamassassin.js:135:16)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1223:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Checklist:
=> SA: stop processing when client is gone

Changes.md, docs/Outbound.md, outbound/config.js, outbound/mx_lookup.js
Fixes #2809
- keep target mx only if its IP is not a local IP
Checklist:
=> fix(localhost-loop): fix outbound loop when target mx is localhost

Changes.md, docs/Outbound.md, outbound/config.js, outbound/hmail.js, tests/outbound/index.js
- Add a new config option in outbound to allow configuration of delay times
- The configuration would look something like (see the docs for specifics):
`temp_fail_intervals` = `1m, 5m, 9m, 15m*3, 30m*10, 1h*6, 2h*6` 
Checklist:
=> User configurable temporary fail delay times

Changes.md, config/spamassassin.ini, docs/plugins/spamassassin.md, plugins/spamassassin.js
- Allow spamassassin to return DENYSOFT on connection errors, connection timeouts, and scan timeouts
- New configuration options added for each scenario, defaulting to false (honoring existing behavior)
Checklist:
=> Allow spamassassin to return DENYSOFT on errors/timeouts

Plugins.md
Adds [haraka-plugin-queue-rails](https://github.com/mailprotector/haraka-plugin-queue-rails) to the community plugins list.
- Update the plugins.md to include the [haraka-plugin-queue-rails](https://github.com/mailprotector/haraka-plugin-queue-rails) plugin 
Checklist:
- [ x] docs updated
=> Adds haraka-plugin-queue-rails to the community plugins list

outbound/mx_lookup.js, package.json
Fixes #2809 also for host names (#2952 solved it for IPs only). Requires merge of [haraka-net-utils#63](https://github.com/haraka/haraka-net-utils/pull/63) first.
- new function `net_utils.is_local_host` is used instead of `net_utils.is_local_ip` to check if the exchange is localhost.
Checklist:
=> prevent local delivery loop when target exchange resolves to a local hostname

.eslintrc.yaml, .github/workflows/ci-test-win.yml, .github/workflows/ci-test.yml, package.json, plugins/helo.checks.js, tests/plugins/mail_from.is_resolvable.js
iconv won't build on Windows right now, unless it's Windows 2019 and node.js 14. Windows-latest fails with every version. I'm giving up on that.
- [bump a couple versions](https://github.com/haraka/Haraka/commit/1f80e506d41fc2ee41efa66710097473dd77d6ba)
- [drop node 12, add node 16 tests](https://github.com/haraka/Haraka/commit/00d25eb97ea8ff1bbfb15e03d4b60bad5f04f783)
-  [remove 3 failing DNS tests](https://github.com/haraka/Haraka/commit/5a2a7915bea40365829dad5f1fb8ce1005458d46)
Checklist:
=> restore CI tests to working order

Changes.md, plugins/dkim_sign.js
- don't emit an error after deciding not to skip signing a message and logging why
````
Apr  2 07:48:29 [INFO] [] [dkim_verify] identity="@online.costco.com" domain="online.costco.com" selector="key1" result=pass
Apr  2 07:48:29 [NOTICE] [-] [dkim_sign] skipped: no private key for online.costco.com
Apr  2 07:48:29 [ERROR] [-] [core] missing key data for undefined.online.costco.com
Apr  2 07:48:30 [NOTICE] [] [core] disconnect ip=67.90.142.249 rdns=mta16v7.online.costco.com helo=mta16v7.online.costco.com relay=N early=N esmtp=Y tls=Y pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=211031 lr="" time=8.286
````
Checklist:
=> remove not-an-error error message

config/outbound.ini, docs/Outbound.md, outbound/client_pool.js, outbound/config.js
Fixes #
With the lates generic-pool (version 3.8.2 at package.json) doesn't work simple queue delivery
It is repeatedly creating new pool entry until JavaScript heap is over and process is terminated by low memory reason
Checklist:
=> bugfix queue/dilivery with latest generic-pool

.github/workflows/ci-test-win.yml, tests/server.js
=> Windows node-gyp workaround testing

Changes.md, docs/Outbound.md, outbound/hmail.js, outbound/todo.js
- Add a force_tls option to the ToDo object to allow forcing TLS for outbound from a hook
Checklist:
- [-] tests updated
=> Add force_tls option to ToDo object to require outbound TLS

outbound/hmail.js
it's easier to read the logs with the hostname instead of just the IP address.
=> hmail: output the bind_helo when attempting delivery

outbound/client_pool.js
Currently, the messages look like this:
```
[DEBUG] [02189A5C-54DC-4B51-AEB1-C3BE81488DB0] [core] [outbound] created
[DEBUG] [ED283FFA-B342-4F14-9976-64AA653F6CF9] [core] [outbound] created
[DEBUG] [CD8A5DD9-ECF1-47B4-9909-ACC0C986BB7D] [core] [outbound] created
[DEBUG] [771DEF11-85D6-4B4A-9850-23AF523DA624] [core] [outbound] created
```
=> client_pool: fix debug message

outbound/queue.js
Makes it easy to correlate logs with the actual queue file.
=> queue: add the filename in log output

Changes.md, outbound/hmail.js
- do not assume authorization identity rather let destination server derive itself (see https://www.rfc-editor.org/rfc/rfc4616.html#section-2), smtp_forward.js works the same
Checklist:
=> Removed AUTH PLAIN authorization identity

Changes.md, outbound/client_pool.js
...to prevent constant reconnect to unreachable servers
The generic-pool module is built on the assumption that acquire always succeeds. It is implemented as a busy loop of calling create() non-stop and there is no way to make acquire() return an error.
As a mitigation error, we make acquire() fail after 10 seconds. Note that it will still busy loop for 10 seconds. We have to fix upstream module or replace generic-pool to really fix the problem.
see #3100
Fixes #
Checklist:
=> outbound: set acquireTimeoutMillis

transaction.js
https://nodejs.org/api/util.html#utiltypesisregexpvalue
util.isRegExp is deprecated since node v4.
=> update util.isRegExp to util.types.isRegExp

Changes.md, config/smtp_forward.ini, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js
- partly reverts #2795. See also #1472
switches smtp_forward on outbound to off-by-default. Enabled only when asked for in config file.
Checklist:
=> smtp_forward: restore queue_outbound when config asks for it

dkim.js, logger.js, plugins/auth/auth_proxy.js, plugins/avg.js, plugins/clamd.js, plugins/delay_deny.js, plugins/esets.js, plugins/greylist.js, plugins/messagesniffer.js, plugins/prevent_credential_leaks.js, plugins/process_title.js, plugins/queue/quarantine.js, plugins/queue/smtp_forward.js, plugins/rcpt_to.host_list_base.js, plugins/spamassassin.js, plugins/xclient.js, smtp_client.js, tests/plugins/dns_list_base.js, tests/plugins/spamassassin.js, tls_socket.js
- coerce some results to boolean with not not (!!) operator
- remove useless returns
- more early returns
- test: cbl.abuseat.org -> xbl.spamhaus.org
- use empty string instead of false to type consistency
- regex: replace `[0-9]` with `\d`
- shed a few indirect variables
- refactor: do assignments outside of conditional test
=> lint changes, cherry picked from #3135

bin/haraka
Fixed error messages for help options
- changed "**qlist** option requires config path" to "**qstat** option requires config path"
- changed "**qlist** option requires config path" to "**qempty** option requires config path"
- changed "**order** option requires config path" to "**test** option requires config path"
=> Fixed error messages for help options

Changes.md, connection.js
- fixes #3176
- closes #3177
Differences:
- don't return unsanitized network input (its a vulnerability vector)
- don't log unsanitized network input as it enables log injection vulnerabilities
Checklist:
=> don't leak addr parsing errors into SMTP conversation

Changes.md, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js
=> q(forward): correct path to next_hop

Changes.md, docs/plugins/queue/smtp_forward.md, docs/plugins/queue/smtp_proxy.md, plugins/queue/smtp_forward.js, tests/plugins/queue/smtp_forward.js
- smtp_forward: tighten up queue.wants routing
- doc(smtp_forward): improve markdown formatting
Checklist:
=> smtp_forward: tighten up queue.wants routing

plugins/helo.checks.js
Suppress extra log messages like this (introduced in #3191)
````
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: proto_mismatch
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: match_re
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: bare_ip
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: dynamic
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: big_company
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: valid_hostname
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: rdns_match
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: forward_dns
Jun 15 17:58:07 haraka: [INFO] [3EF8DFC4] [helo.checks] SKIPPING: host_mismatch
Jun 15 17:58:07 haraka: [INFO] …
```
=> helo.checks: reduce noisy logging

docs/plugins/queue/smtp_forward.md, plugins/queue/smtp_forward.js
=> q/smtp_forward: always register get_mx hook

Plugins.md, README.md, config/access.domains, docs/Connection.md, docs/Outbound.md, docs/Transaction.md, docs/plugins/connect.rdns_access.md, docs/plugins/mail_from.access.md, docs/plugins/rcpt_to.access.md, docs/plugins/relay.md
Updated links to documentation.
=> Update links in documentation

outbound/hmail.js
Fixes #3236
- Added empty string as a parameter of .join().
Checklist:
=> Fixed incorrect use of .join() on bounce.

Changes.md, config/rabbitmq_amqplib.ini, docs/plugins/queue/rabbitmq_amqplib.md, plugins/queue/rabbitmq_amqplib.js
Fixes #
- Allow configuring optional queue arguments in queue/rabbitmq_amqplib plugin
Checklist:
=> allow configuring optional queue arguments

.gitignore, Changes.md, docs/Outbound.md
The docs a few paragraphs above tell users NOT to set the note manually and to use `get_mx`.  Perfect. Don't follow that with an example of manually setting `outbound_ip`.
closes #2911
Checklist:
=> docs(outbound): remove example of outbound_ip

config/helo.checks.ini, plugins/helo.checks.js
Fixes #
- Reduced DNS timeout from 30 seconds to 28 seconds to prevent Haraka crash.
Checklist:
=> Reduced DNS timeout to prevent Haraka crash.

Changes.md, outbound/hmail.js, outbound/queue.js
Fixes #
- Add filename to the 'Didn't find right amount of data in todo!' error for easy debugging
- Ignore error. prefixed files in the queue because are corrupted
Checklist:
=> Fixes and improvements

Changes.md, config/auth_flat_file.ini, config/auth_vpopmaild.ini, docs/plugins/auth/auth_vpopmaild.md, docs/plugins/auth/flat_file.md, plugins/auth/auth_base.js, plugins/auth/auth_vpopmaild.js, plugins/auth/flat_file.js
- auth_base (flat & vpopmaild): when user auths (outbound), assure the MAIL FROM (envelope) domain matches the domain of the email address they authenticated with.
- shed some useless returns
related to haraka/haraka-plugin-limit#28
Checklist:
=> feat: if AUTH, assure Env From dom matches AUTH dom

Changes.md, outbound/hmail.js
Fixes #3278 
- add `LHLO` to the allowed commands if TLS is enforced
Checklist:
=> fix(outbound): allow LHLO over insecure socket if TLS is forced (#3278)

Changes.md, outbound/queue.js
if user/group specified in smtp.ini
Fixes #2773 
Checklist:
=> outbound: chown queue dir after creation

Changes.md, outbound/hmail.js, outbound/mx_lookup.js, outbound/tls.js, package.json, tests/outbound/index.js, tests/outbound/mx_lookup.js
- outbound: move local_mx_ok test into try_deliver, where a log entry can be emitted telling why a MX is rejected
- related to changes in #2952
- probably the issue in #3211
- outbound/mx_lookup: make it async/await, so it hurts the brain less to read it
- outbound/tls: don't set servername (SNI) for IP addresses, fixes #3275 
- outbound/mx_lookup: add several tests
Checklist:
=> outbound: log message when ignoring local MX

docs/plugins/queue/smtp_proxy.md, plugins/queue/smtp_forward.js, plugins/queue/smtp_proxy.js
This might fix #3023
- q/proxy: check client is alive b4 sending cmd
Checklist:
=> smtp_proxy: handle dead sender more gracefully

Changes.md, outbound/hmail.js
when required. fixes #2711
[3.4](https://www.rfc-editor.org/rfc/rfc6531#section-3.4).  MAIL Command Parameter Usage
If the envelope or message being sent requires the capabilities of
the SMTPUTF8 extension, the SMTPUTF8-aware SMTP client MUST supply
the SMTPUTF8 parameter with the MAIL command.  If this parameter is
provided, it MUST not accept a value.  If the SMTPUTF8-aware SMTP
client is aware that neither the envelope nor the message being sent
requires any of the SMTPUTF8 extension capabilities, it SHOULD NOT
supply the SMTPUTF8 parameter with the MAIL command.
Checklist:
=> outbound: include SMTPUTF8 param in return path

Changes.md, plugins/auth/auth_base.js
When an auth plugin is loaded, if `constrain_sender` is false, then the hook doesn't get registered and is never called. If `constrain_sender` is true, then the hook is registered and is called every time that hook is run. If the config file is then set to `false`, the hook is still run. This adds a run-time check.
Checklist:
=> auth_base: return if setting switches to false at runtime

.github/dependabot.yml, Changes.md, outbound/hmail.js, outbound/mx_lookup.js, package.json
Fixes #3299
- bump version of all deps to latest
- remove eslint from devDeps (installs if/when needed via npx)
- outbound: fix error handling in mx_lookup
Checklist:
=> dependencies: bump versions

.github/workflows/coverage.yml, Changes.md, bin/haraka, package.json
Fixes #3272, Fixes #3212
- bin/haraka:
- get plugin hooks from doc/Plugins
- remove a dead link
- es6 updates (forEach -> for...of, strings)
- chore: refactor duplicated code into setupRequire()
Checklist:
=> fix: get plugin hooks from doc/Plugins

Changes.md, outbound/hmail.js
github somehow broke the #3300 PR - still showing me "processing updates" and refusing to accept changes, so this is a second attempt to update cfg.local_mx_ok functionality
It only checks local mx if it falls through to the default route - so any plugin's mx is excluded.
=> check for local_mx only when default route is used

Changes.md, bin/haraka
When running `haraka -l`, also list NPM installed plugins.
related to haraka/haraka-plugin-access#25
=> bin/haraka: also list installed NPM plugins

Changes.md, connection.js, outbound/index.js, package.json, plugins.js, tests/connection.js, tests/fixtures/util_hmailitem.js, tests/plugins/queue/smtp_forward.js, tests/plugins/spamassassin.js, tests/transaction.js, transaction.js
- transaction: init with conn.init_transaction, always pass in cfg #3315
- NOTE: remove a handful of 3.0 sunset property names #3315
- outbound: pass in config when initiating txn
- outbound: minor es6 updates
Checklist:
=> transaction init consistency

plugins/greylist.js
Fixes #3284 
- greylist: update redis call names to v4
- 
Checklist:
=> greylist: update redis call names to v4

docs/CoreConfig.md
Linked to https://github.com/haraka/haraka-config/pull/77
The doc seems to suggest you can't override log.ini in smtp.json as it would be loaded after it. Doesn't seem to be true in reality :)
=> Improve JSON override doc

Changes.md, outbound/hmail.js, outbound/index.js, outbound/queue.js, outbound/timer_queue.js, plugins/status.js, server.js, test/fixtures/util_hmailitem.js, test/server.js, tls_socket.js
- es6(async/promise): pre_send_trans_email_respond, process_delivery
- server:
- es6(async) _graceful, get_smtp_server, setup_smtp_listeners
- replace async.eachLimit with Promise.all batches
- status: replace async.map with Promise.allSettled
Checklist:
=> style: more async/await

Changes.md, endpoint.js, server.js, test/endpoint.js
Fixes #3366
- making endpoint.bind() to async and awaiting in server.js
Checklist:
=> Fix startup race condition

Changes.md, outbound/hmail.js
First idea how to fix #3375
- slight rewrite of code around get_mx and making get_mx_respond async
Checklist:
=> Fix DNS error crash

Changes.md, config/tls.ini, docs/plugins/tls.md, test/config/tls.ini, test/outbound/index.js, test/tls_socket.js
- Add tests for `no_tls_hosts` config entry
- Improve docs for `no_tls_hosts` so that it's less surprising
Checklist:
I am new to Haraka and may be slow to respond, so please feel free to make any necessary modifications. Thanks for your awesome work!
=> Fix `no_tls_hosts` related docs & tests

Changes.md, package.json
Fixes https://github.com/haraka/email-message/issues/12.
- Update haraka-email-message to 1.2.4, which correcly recognizes attachment filenames containing semicolons.
With this update, emails containing attachments named e.g. "aaa@bbb.com; ccc@ddd.com.zip" won't be rejected anymore due to the combination of the filename being incorrectly read as "aaa@bbb.com" and the [attachment](https://github.com/haraka/haraka-plugin-attachment) Haraka plugin rejecting the com extension.
Checklist:
To the maintainer: I'm not entirely sure I'm following the right contribution process here (https://github.com/haraka/email-message/pull/13 not being merged yet), feel free to discard this PR for another one if appropriate.
=> dep(haraka-email-message): 1.2.3 -> 1.2.4

Changes.md, bin/haraka
=> fix(haraka): for haraka -o, use path.resolve & parsed.configs

Changes.md, outbound/hmail.js
check mx.from_dns and if hostname is there, use that.
Checklist:
=> fix(outbound): hook_delivered may contain an IP, so..

Changes.md, connection.js
Fixes #3445
Changed logic for the initial greeting to use a copy of the custom greeting array in connections.ini to build the greeting message so that it doesn't keep infinitely expanding for every connection.  The fix is slightly different than that discussed in #3445 to properly handle cases when the custom greeting is not set in connections.ini.
Checklist:
=> Fix cumulative greeting message for custom greetings

logger.js
When stopping the server, I'm getting the following deprecation warning
```
^C(node:69460) [DEP0049] DeprecationWarning: The `util.isFunction` API is deprecated.  Please use `typeof arg === "function"` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
https://nodejs.org/api/deprecations.html#DEP0049
=> Fix util.isFunction deprecation warning

Changes.md, outbound/client_pool.js
In node 22 atleast, network code has started returning AggregateError. This means that when socket connection fails, err.message is an empty string. The on('error') handler as a result invoked callback('', null) . Since error is falsy, code assumes socket is valid and crashes.
Code is changed to always return a error string.
Fixes #3455
- Code is changed to always return a error string on a socket error
Checklist:
=> Fix crash when outbound connection fails
