haraka/Haraka

plugins/dns_list_base.js
tests/plugins/dns_list_base.js

Fixes issue with IPv6 lookups reported by Inferno on IRC.

Add missing return's in dns_list_base and add regression test

---

configfile.js

configfile: update other cache calls to use option

---

docs/Logging_API.md
docs/plugins/auth/auth_vpopmaild.md

Trivial issues nonetheless, but quite annoying.

Fixes 2 docs issues

---

connection.js

Belt and braces check after investigating #821.

Add transaction guard as a precaution

---

tests/plugins/connect.geoip.js

(seems to be a change in data availability)

make failing connect.geoip test conditional

---

plugins.js
tests/plugins.js

moves @martin1yness plugin path code into a function and adds test coverage.

added plugins._get_plugin_path and tests

---

README.md

* increase readability
* preserve the content
* reduce the words.
* add useful links

README: wordsmithing

---

configfile.js

* replace cfreader.config_path with cp (5x)
* early exit of functions permit removing of extra indention

configfile: shed some excess indention

---

.travis.yml
plugins/log.syslog.js
tests/plugins/log.syslog.js

* log.syslog: gracefully handle inability to load node-syslog
* skip tests when loading fails
* enables iojs testing

log.syslog: handle inability to load node-syslog

---

docs/plugins/queue/discard.md

make queue/discard usage clearer

---

.travis.yml
README.md
appveyor.yml
package.json
plugins.js
tests/plugins.js

* add appveyor.yml
* remove ./ from run_tests
* make plugins test Windows compatible.
* permit build failures on node 0.8

add Windows build status badge

---

plugins/rcpt_to.qmail_deliverable.js

@msimerson can you just check this PR out? It broke my upgrade because I didn't have the config file.

Fix the default port to match the docs and default .ini

---

tests/utils.js
utils.js

utils: added .extend(), copy props onto objects

---

config/plugins

* makes it easier to enable features
* provides information about available plugins
* makes it likely that they'll be enabled in the right order
* (en | dis)able plugins with sed

populate config/plugins with disabled plugins

---

configfile.js
plugins.js
tests/plugins.js

* adds test coverage to timeout handling
* disables config cache when WITHOUT_CONFIG_CACHE is set so it's possible to test that the timeout is read properly when config files are and aren't present)

plugins: improved timeout handling

---

config/public-suffix-list

yeah, should have done that *before* release

updated Public Suffix List

---

net_utils.js
tests/net_utils.js

* is_ip_in_str, invert IPv4 detection and exit early
* test/net_utils: lint updates
* removes a duplicated is_public_suffix test

refactor octets_in_string from is_ip_in_str

---

outbound.js

outbound: wrap long lines

---

plugins/mail_from.is_resolvable.js

Steve's branch, rebased (git rebase -i) to get rid of the extra commits.
closes #873
closes #874

Fix for issue #873

---

docs/plugins/access.md

correct name of domains config file in access

---

docs/plugins/access.md
docs/plugins/attachment.md
docs/plugins/avg.md
docs/plugins/block_me.md
docs/plugins/bounces.md
docs/plugins/clamd.md
docs/plugins/connect.fcrdns.md
docs/plugins/connect.p0f.md
docs/plugins/karma.md
docs/plugins/rcpt_to.in_host_list.md
docs/plugins/rcpt_to.qmail_deliverable.md
docs/plugins/xclient.md

The majority of this PR is fixing formatting errors in haraka.github.io.
Most of the changes are due to the current markdown -> html process doing things quite a bit differently than GitHub Flavored Markdown.

formatting and wordsmithing of docs/plugins/*.md

---

result_store.js

used by: (watch, log.elasticsearch, and @smfreegard's ES)

result_store: add get_all function

---

.travis.yml

.travis.yml: disable testing, always fails

---

config/data.headers.ini
docs/plugins/rate_limit.md
logger.js
plugins/access.js
plugins/attachment.js
plugins/connect.rdns_access.js
plugins/rdns.regexp.js
plugins/spf.js
plugins/tls.js
plugins/xclient.js
tls_socket.js

* line shortening
* data.headers.ini are all defined as booleans in plugin, so no need to have them defined in ini too (we can't *know* if someone intended that, or just accepted default)

noop (mostly line shortening) changes

---

connection.js

instead of 452/552 'insufficient system storage'
looks like a copy/paste error, as there are two cases where a 452 in connection remains, for disk space errors.

connection: return 450/550 for plugin DENY*

---

tests/utils.js
utils.js

running node is at least the specified version. Much tastier than wrapping
node built-ins with try blocks.

utils: added node_min(), for checking if

---

plugins/access.js

access: provide a debug level msg for empty re

---

server.js

This is so that plugins can create listeners on cluster events which are necessary for things like cluster IPC.

Fork child workers after init_master hook has run

---

.gitignore
TODO
config/graph.ini
config/http.ini
http/Gruntfile.js
http/bower.json
http/html/index.html
http/package.json
plugins/graph.js
server.js

* allows multiple plugins to serve on the same HTTP(S) port
* provides an index/landing page
* closes #433 
* the basis for facilities to manage the outbound queue (@baudehlo in #443)
* ~~the html/* directory is not included. Yet.~~ (installed with bower)
* ~~how to install web dependencies and avoid test failures re: them? (optionalDeps isn't ideal)~~ (bower)
* ~~docroot handling for haraka and per-plugin~~ (each plugin registers a route)
* populate plugin tabs dynamically (based on plugins that register routes)
* auth via any SMTP-AUTH provider
* provide a consistent UI via standardised views/templates (@baudehlo in #443)

Http server

---

plugins/auth/auth_base.js

so that auth puts this into ES output:
````
"auth/auth_vpopmaild": {
"pass": [
"PLAIN"
]
},
````
drive-by:
* wrap long lines
* remove trailing whitespace

auth_base: save auth result to Results

---

plugins/tls.js

Fix TLS timer on error

---

transaction.js

fix 8-bit msg not displayed properly in gmail

---

connection.js

that counts a bunch of errors that unrecognized doesn't

connection: add an errors counter

---

config/karma.ini
plugins/karma.js

to control how long MSA (port 465/587) connections are tarpitted

karma: added config option: [tarpit]max_msa

---

plugins.js
tests/plugins.js

This change makes this possible:
```diff
@@config/plugins
-watch/server
+watch
```
````
ls plugins/watch
index.js
html
````

permit plugins to be directories

---

.travis.yml
config/limit.ini
docs/Plugins.md
docs/plugins/limit.md
package.json
plugins/limit.js
tests/plugins/limit.js

new plugin: limit

---

connection.js

* switch/case use a single level of indention (as is the case nearly everywhere else)
* wrap long lines

connection: whitespace consistency

---

tests/utils.js
utils.js

returns elapsed seconds since the provided date object, formatted for
presentation
and some driveby whitespace repair (4 space indention)

add utils.elapsed()

---

config/karma.ini
docs/plugins/karma.md
plugins/karma.js
tests/plugins/karma.js

* remove concurrency checks
* remove max recipient checks
* add ability to select redis index
* remove penalty feature, more humorous than helpful, and doesn't fit future plans

karma: prune features moved to limit plugin and

---

config/watch.ini
docs/plugins/watch.md
plugins/watch/html/client.js
plugins/watch/html/index.html
plugins/watch/html/jquery.tipsy.css
plugins/watch/html/jquery.tipsy.js
plugins/watch/html/watch.css
plugins/watch/index.js

* watch/client: display transactions in new rows
* watch/server: get results via get_all
instead of checking based on list of plugins
* watch: prune connections > 100
* watch/server: don't sent data if same as last sent

watch SMTP connections in browser

---

docs/plugins/bounces.md
plugins/bounce.js

* adds reject.non_local_msgid config option (default=false)
* enables check.non_local_msgid by default (it's safe now)

bounce: make it safe to check non_local_msgid

---

plugins/limit.js

as might be the case for upgrades

limits: set defaults in case limit.ini missing

---

config/access.domains

Provide an empty access.domains file with basic usage comments and the url for more details

Create an access.domains files with some tips

---

plugins/clamd.js

primarily shortening long lines

clamd: lint / ws changes only (noop)

---

connection.js

- Change this.pipelining and this.early_talker into booleans
- Change error message returned at DATA if no recipients were accepted but the client was pipelining as per RFC2920.

Pipelining: Address #538 and #970 partially

---

plugins/rate_limit.js

make rate_limit redis keys expire whatever would happen

---

connection.js
tests/connection.js

replace 14 of these constructs:
```js
msg || "Message denied"
```
with 6 of these:
```js
if (!msg) msg = queue_msg(...)
```

consolidate queue message default into function

---

plugins/queue/smtp_forward.js

replace 5 of these
if (smtp_client.is_dead_sender(plugin, connection)) {
return;
}
with 5 of these:
if (dead_sender()) return;

smtp_forward: avoid repeated code (DRY)

---

dsn.js
tests/dsn.js

* Export DSN constructor and allow custom codes
* Change create() function signature slightly
closes #985

DSN: Add new create() and RFC4954 support

---

plugins.js

* lint happiness
* consolidated 3x checks info client_disconnected()
* wrap long lines
* refactored log_run_item() out of ginormous run_next_hook()
* replaced utils.in_array() with faster switch/case in new fn is_deny_retval()
* invert logic in loop in run_next_hook(): less indention and early exit makes it easier to extend the conditionals (coming soon to a PR near you).

plugins: noop

---

bin/haraka
plugins.js

This is designed to make testing and debugging Haraka and the plugins much easier by allowing them to be tested individually and without requiring an SMTP connection or requiring the plugin to be put 'live'.
`````
[smf@mail1-ec2 Haraka]$ bin/haraka
Error: Undefined or erroneous arguments
Haraka.js — A Node.js Email Server project
Usage: haraka [options] [path]
Options:
-v, --version 		Outputs version number
-h, --help    		Outputs this help message
-h NAME       		Shows help for NAME
-c, --configs 		Path to your config directory
-i, --install 		Copies the default configs to a specified dir
-l, --list    		List the plugins bundled with Haraka
-p, --plugin  		Generate a new plugin with the given name
-f, --force   		Force overwriting of old files
--qlist       		List the outbound queue …
```

Plugin test mode

---

bin/haraka
docs/Plugins.md
logger.js
package.json
plugins.js

This commit adds support for overriding the plugin hook run order, by explicitly registering a hook and specifying a `priority` between -100 (highest priority) and 100 (lowest priority) with the default priority being 0 (zero).
Additionally it improves the `bin/haraka -o` output by showing the plugin priorities and now only shows hooks with plugins actually registered on them:
`````
Hook: connect ------------------------------------------------------------------
Plugin                                Method                                Prio
--------------------------------------------------------------------------------
access                                rdns_access                              0
access                                any                                      0
dnsbl …
```

Plugin ordering

---

plugins/watch/html/client.js
plugins/watch/html/watch.css
plugins/watch/index.js

* sometimes classes weren't updated correctly
* better reporting of queue (particularly smtp_forward) results
* show more lines of results
* reduce fadeout time of rows off bottom of display (kinder to CPU)
* includes updates for karma changes in #996

watch: correct class display colors

---

connection.js
docs/Plugins.md
plugins.js
plugins/karma.js
plugins/limit.js
plugins/process_title.js
plugins/profile.js
plugins/rate_limit.js

plugins: ignore retval for connect_init

add connect_init hook

---

docs/plugins/backscatterer.md
plugins/backscatterer.js

Useful little plugin; has a fairly high crossover with Zen/Spamcop at times, but generally works pretty well and I've found it pretty safe to reject outright with.
`````
msg="Host DNSERROR [202.56.255.50] is blacklisted by ips.backscatterer.org"
msg="Host c-73-132-35-70.hsd1.va.comcast.net [73.132.35.70] is blacklisted by ips.backscatterer.org"
msg="Host 135-13.alba.dp.ua [193.151.13.135] is blacklisted by ips.backscatterer.org"
msg="Host bas5-toronto01-1177868522.dsl.bell.ca [70.52.216.234] is blacklisted by ips.backscatterer.org"
msg="Host dsl-201-114-84-32-dyn.prod-infinitum.com.mx [201.114.84.32] is blacklisted by ips.backscatterer.org"
msg="Host bba598780.alshamil.net.ae [86.98.78.102] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [77.67.227.244] is blacklisted by …
```

New backscatterer plugin

---

plugins/xclient.js

Add LOGIN support to XCLIENT

---

docs/plugins/dcc.md
plugins/dcc.js

I wrote this ages ago and it's been running on my test box without issue.   
I currently have no time to improve it (e.g. add support for DCC greylisting or the commercial DCC Reputations), so I'm committing it for other interested parties that might want to improve it.
It is best run in conjunction with a scoring system (e.g. like karma) and when combined with other rules.

DCC plugin (incomplete)

---

plugins/toobusy.js

toobusy.js isn't in the package.json dependencies, so handle the `not installed` error and
log a useful error message if it can't be loaded.
Only run hook if the lib loaded.

make toobusy safer

---

plugins/attachment.js

attach: don't register data hooks unless require

---

connection.js

Same fix as #1024 but for queue_ok_respond

Fix queue_ok logging

---

plugins/attachment.js

Now the extension loading get gets run once at register() and once per time
the config file changes.
Previously, the config wrangling was done on every connection.

attach: consolidate config handling into load_ini()

---

plugins/graph.js
plugins/watch/index.js

watch & graph updates for compatibility with #1015

---

connection.js

except for null sender.
* angle brackets aren't terribly useful (why have address.format() include them?)
* rename the result properties to be more clear (especially since recipients
are objects):
* mail_from.sender    -> mail_from.address
* recipient.recipient -> recipient.address
* instead of sender being an object, make it just the sender address and when the sender is rejected, save the results In The Usual Way (fail: ...).

conn results: trim <> off sender and recip addrs

---

plugins/rspamd.js

when transaction no longer present

rspamd: fix a haraka crashing bug

---

result_store.js
tests/result_store.js

results: add support for bool & num matching with

---

plugins/dnsbl.js

this is another of those, "now that I can **see** those results in Elasticsearch, lets make 'em better."

dnsbl: improve reported result error

---

plugins/limit.js

limit: pass default when history missing

---

configfile.js

I hit an issue with my app yesterday whereby all configuration is loaded from a single smtp.json file using overrides.
Since the overrides pre-dates the boolean options added to .ini options and since all of the plugins were changed to start using this I found that because I'm loading from smtp.json, the boolean defaults for .ini files were not being honoured (e.g. because we already had the file in the config cache) and that caused a lot of the plugins to blow up with exceptions because many plugins now load into [reject], [check] etc. sections, but the code to check these values does not check to see if they exist e.g. if (cfg.check.foo) ... vs. if (cfg.check && cfg.check.foo) ...
This patch fixes that issue and ensures that any specified defaults are loaded if they are not already set …

Fix .ini file booleans on overriden values

---

config/karma.ini
docs/plugins/karma.md
plugins/karma.js
tests/plugins/karma.js

* abstracted and tested check_results_* fns
* karma: added asn handling
* make karma reject message configurable
* updated "new format" karma.ini
* apply award just once
* auth plugins can score more than once (every auth failure..)
* simplify disconnect (remove history)
* karma: updated docs

karma2: real time results from redis pub/sub

---

result_store.js

Fixes a couple of annoyances:
1) Error logging
There's a bunch of plugins that do:
`if (err) connection.results.add(plugin, {err: err});` where `err` is actually a proper Error object.   This causes ResultStore to log:
`Jul 23 12:38:12 localhost haraka[25434]: [ERROR] [546435EB-BDF0-44F3-89C4-46A53351A8A6] [Error]`
Which is clearly wrong.   So rather than fixing all of the various plugins, I figured it was likely a fairly common mistake that could be easily handling the case and logging `err.message` instead which then results in the following output:
`Jul 23 13:20:17 localhost haraka[26832]: [ERROR] [42496B88-A3C2-4427-AF05-4DE835E10840] [defendermx/dnswl] IPv6 not supported`
2)  Logging of objects
It seems pretty commonplace for some plugins to build an object, then stuff it into …

Tidy-up some ResultStore logging

---

config/karma.ini
plugins/karma.js
tests/plugins/early_talker.js

as there's no connection.results to work with

karma: skip deny on outbound hooks

---

docs/Outbound.md
outbound.js

Fix HELO/rDNS issue while using multiple outbound ip #1114

---

docs/plugins/dkim_sign.md

If docs okay, merge and close #659.

Add Infos based on issue https://github.com/baudehlo/Haraka/issues/659

---

plugins.js

Fix so constants are imported when plugin is loaded from node_modules.

---

plugins/data.headers.js
tests/plugins/data.headers.js

add checks for X-Yahoo-Newman-Property (Yahoo) and X-MS-Has-Attach: (Outlook 15)

improve MUA detection

---

plugins/connect.asn.js

if asn lookup errs, save that error to results_store.

asn: add results store

---

plugins/data.uribl.js

and a more informative results fail message.

uribl: prevent calling next() more than 1x

---

config/tls.ini
plugins/tls.js

fixes #770 
* disabled by default
* progressive enhancement: does nothing if redis unavailable.

tls: tmp disable for hosts that fail STARTTLS

---

plugins/connect.geoip.js

`````
[core] Plugin connect.geoip failed: TypeError: Cannot read property 'continentCode' of null
at Plugin.exports.get_geoip (/usr/lib/node_modules/Haraka/plugins/connect.geoip.js:203:12)
at Plugin.exports.received_headers (/usr/lib/node_modules/Haraka/plugins/connect.geoip.js:360:25)
at Plugin.exports.add_headers (/usr/lib/node_modules/Haraka/plugins/connect.geoip.js:268:21)
at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:400:28)
at callback (/usr/lib/node_modules/Haraka/plugins.js:356:32)
at Plugin.exports.hook_data_post (/usr/lib/node_modules/Haraka/plugins/defendermx/check_syntax.js:82:12)
at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:400:28)
at callback (/usr/lib/node_modules/Haraka/plugins.js:356:32)
at …
```

Fix connect.geoip bug

---

docs/plugins/aliases.md
plugins/aliases.js
tests/plugins/aliases.js

- added support for "user@host" alias, "@host" alias
- before check the "user" alias.

Fix for #542

---

plugins/data.uribl.js

* only randomize if list has contents
* consolidate 3x code into exit_if_done
* shed a couple indent levels
* make flow control a little easier to grok
(this is really a very small PR with two large left-shift indentions)

uribl: flow control readability

---

net_utils.js
plugins/connect.fcrdns.js
plugins/lookup_rdns.strict.js
plugins/mail_from.is_resolvable.js
tests/net_utils.js

This PR takes the 4x repeated code in #1154 and consolidates it into a tested net_utils function.

Net utils.get ips by host

---

package.json

Add license clause

---

docs/plugins/rcpt_to.in_host_list.md
plugins/rcpt_to.host_list_base.js
tests/plugins/rcpt_to.host_list_base.js
tests/plugins/rcpt_to.in_host_list.js

Thanks to @smfreegard for build Anti spoof.
I have done the test working by load config to the tests.
closes #952

Fix anti_spoof by use config

---

.eslintrc
haraka.js
mailheader.js
net_utils.js
outbound.js
plugins/auth/auth_base.js
plugins/dcc.js
plugins/delay_deny.js
plugins/helo.checks.js
plugins/log.syslog.js
plugins/lookup_rdns.strict.js
plugins/queue/rabbitmq_amqplib.js
plugins/rcpt_to.ldap.js
plugins/rcpt_to.qmail_deliverable.js
plugins/relay.js
plugins/relay_acl.js
plugins/watch/html/jquery.tipsy.js
plugins/watch/index.js
plugins/xclient.js
spf.js
tests/net_utils.js

per [style
conventions](https://github.com/baudehlo/Haraka/wiki/Contributing)

lint: use space after keywords/operators

---

appveyor.yml
package.json

* install grunt-cli
* avoid CLI magic in npm commands

appveyor: repair Windows build status

---

config/attachment.filename.regex

https://support.google.com/mail/answer/6590?hl=en
closes #1184

block more attachment file types

---

docs/Plugins.md

* adds docs for init_http and init_wss
* grammar improvements
closes #1115

plugins.md updates, http_init hook

---

Dockerfile
README.md
config/plugins
docs/Logging_API.md
docs/Plugins.md
docs/plugins/connect.geoip.md
docs/plugins/queue/smtp_forward.md
docs/plugins/tls.md
package.json

Changes docs to haraka/Haraka

---

tests/config.js
tests/config/test.ini
tests/configfile.js

adds missing tests for PR #1207

added tests for : in ini config key

---

plugins/queue/smtp_forward.js
smtp_client.js

This is PR #1213 rebased against HEAD.
Closes #1213

Smtp forward auth

---

config/greylist.ini
docs/plugins/greylist.md
plugins/greylist.js
tests/plugins/greylist.js

close #1110 orgin: celesteking/Haraka/pull/1
Plugin seems to consider only IPv4. IPv6 review shall be conducted.
* clean up
* one config file and not 4...
* remove "special-sender"
* greylist is greylist and dont need reject/learn actions
*Fix IPv6 incompatibility
* Update docs / config info for action "learn".
* rework: remove Q deps
* rework: async - done
* set "return" to prevent double callbacks
* fix bug cb not a function

greylisting - finished - running live test

---

mailheader.js
transaction.js

this is PR #1231 rebased.
closes #1231

Improve handling of broken messages

---

haraka.sh

PR #1239  rebased
closes #1239

[DOCKER] Direct stdout/err to console, not file

---

.gitignore
.travis.yml
README.md
package.json

This fixes the broken coverage reporting.

switch to codecov.io for coverage reporting

---

plugins/dkim_sign.js
tests/plugins/dkim_sign.js

make dkim keydir case insensitive

---

plugins/auth/auth_vpopmaild.js
plugins/auth/flat_file.js

Fix "passwd" check crash that only "numerical".

---

contrib/debian-init.d/haraka

like red hat but with LSB functions

add debian init.d file

---

plugins.js

Revert "Clean up plugin loading a tiny bit"

---

plugins/karma.js

Previously, karma only connected to redis on the default host (localhost). Now karma can subscribe to redis on other hosts to obtain ResultStore publish messages.

karma: for sub conn, use same params as results pub

---

plugins/watch/html/client.js
plugins/watch/index.js

correctly display early_talker (needs update due to switch to redis pub/sub updates)
* also clean up some whitespace

fix early talker display

---

plugins/queue/smtp_forward.js

use correct path to auth settings

---

mailbody.js
tests/mailbody.js

* shed some indention
* early exit, 2x
* refactor iconv block into mailbody.try_iconv
* lint updates

refactor mailbody.parse_end, noop

---

Changes

1. [x] Start a N-week quiet period
1. [x] Update [Changes](Changes)
1. [x] Update Public Suffix List
1. [x] Update TLDs files (for URIBL plugin and utils.split_hostname)
1. [x] Bump version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
1. [x] Check if any dependencies should be updated with `grunt versioncheck`
1. [x] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes)
1. [x] git tag v<release_number>; git push --tags
1. [ ] npm publish
1. [ ] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
1. [ ] Email the mailing list
1. [ ] Publish a blog post

update Changes for 2.7.3 release

---

outbound.js

remove type check from pid match

---

.eslintrc
UPGRADE.md
outbound.js
package.json

for developers, see the UPGRADING.md comment.

update for eslint 2 compat

---

config.js
configfile.js
docs/Config.md
docs/Plugins.md
plugins.js
tests/config.js
tests/installation/config/test-plugin-flat
tests/installation/config/test-plugin.ini
tests/installation/node_modules/test-plugin/config/test-plugin-flat
tests/installation/node_modules/test-plugin/config/test-plugin.ini
tests/plugins.js

Let me know what you think of these changes.

Load plugin config from own folder and merge

---

docs/Outbound.md

Document HMail and TODO items

---

mailheader.js
tests/mailbody.js

Closes #1166
Will figure out some tests soon.

rfc2231 support

---

config/outbound.ini
outbound.js
plugins/tls.js
smtp_client.js
tls_socket.js

Outbound load tls.ini

---

bin/haraka

This implements and closes #1339

Copy only minimal config on install

---

config/smtp_bridge.ini
docs/plugins/auth/auth_bridge.md
docs/plugins/queue/smtp_bridge.md
plugins/auth/auth_bridge.js
plugins/queue/smtp_bridge.js

This is PR #1326, rebased and squashed.
Closes #1326

add smtp bridge

---

plugins/data.uribl.js

* the top_level_tlds object was moved to haraka-tld in PR #1301. These calls were missed.

update to uribl due to #1301

---

config/smtp_forward.ini

smtp_forward.ini: replace 1 with true

---

smtp_client.js

Fix remote_ip in smtp_client

---

bin/haraka

Copy config/plugins too

---

plugins.js

* I imported swaths of plugins.js into haraka-test-fixtures
* required to improve the "find the plugin path" logic
* in the course of doing that I ..
* wrapped some long lines
* removed some unnecessary indent
* refactored _get_code out of _compile
* optimization: don't read the file when hasPackageJson

plugins.js: small refactoring

---

connection.js

always log recipient acceptance state.

add action var to rcpt_to results

---

docs/plugins/rspamd.md

Clarify usage of check.private_ip

---

.gitignore
plugins/connect.fcrdns.js
tests/plugins/connect.fcrdns.js

Fixes #1390
- rename variable err -> err2

fcrdns: corrected err variable name

---

tls_socket.js

Fixes outbound tls not requesting a the certificate or rejecting unauthorized tls.

Fix outbound requesting cert and rejecting unauth

---

mailheader.js
tests/mailheader.js

Fixes #1245
Replaces #1245
Closes #1245

Encode high-bit headers with continuations.

---

connection.js
docs/Outbound.md
docs/plugins/max_unrecognized_commands.md
mailbody.js
outbound.js
plugins/auth/auth_proxy.js
plugins/avg.js
smtp_client.js

standardize on oxford spelling

---

mailheader.js
tests/mailheader.js
tests/utils.js
utils.js

Re-submitting this.
Now fixed the major bugs in the code, with tests.

Fix mail header parsing/decoding and adding

---

plugins/spf.js

correct log_debug syntax

---

config/data.uribl.ini
tests/plugins/connect.asn.js

Fixes #1420 .
- Fix 1420 on 4/20. 🎉

Remove spameatingmonkey as it's down and failing

---

mailbody.js

Use utf8 encoding now for QP not binary

---

package.json

version deps bumped in the 2.8.0 branch. merging into master now (rather than waiting for 2.8.0 general release).

bump dependency versions

---

smtp_client.js

Small fix for references to "config" that should now be "c"

Using the wrong argument/variable name in smtp_client.js

---

outbound.js

Fixes #1411 .
- This fixes dot-stuffing when sending email via outbound using new contents
I've reviewed any problems that are raised in the original ticket and can't find any.
I thought about writing tests, but it's a lot of work - requires too much monkey patching for my current laziness.

Fix dot stuffing for a single dot

---

tests/plugins/bounce.js

Adding conn.remote_ip = 127.0.0.1 to haraka-test-fixtures broke this test

Bounce plugin tests were broken

---

plugins/bounce.js
tests/plugins/bounce.js

Doesn't really fix the issues listed in #978, but fixes the lack of using regexp in that ticket.

Fix the regexp bug listed in #978

---

dkim.js
net_utils.js
outbound.js
plugins/connect.fcrdns.js
plugins/data.uribl.js
plugins/dns_list_base.js
plugins/helo.checks.js
plugins/lookup_rdns.strict.js
plugins/mail_from.is_resolvable.js
spf.js
tests/plugins/connect.fcrdns.js
tests/plugins/mail_from.is_resolvable.js

Fixes #1381
- change ERROR strings to dns error constants

Change net_utils.get_ips_by_host error handling.

---

mailbody.js

Make sure we return the line with _empty_filter

---

plugins/auth/auth_ldap.js

- Fix crash when ldap client cannot connect to ldap server

auth_ldap: handle ldap client connection error

---

bin/haraka

Last checklist item on releasing 2.8

Install dkim config scripts

---

package.json

bump version number to 2.8.0

---

bin/haraka
outbound.js

Makes bin/haraka --qlist output number of recipients at which domain

Make qlist work better

---

fsync_writestream.js

- Removes node v0.8 stream support
Checklist:

Remove node <= v0.8 support

---

.travis.yml

Add Node v6

---

bin/haraka
connection.js
outbound.js
server.js
timer_queue.js

- adds a --qunstick <domain> to bin/haraka
- adds an internalcmd SMTP verb that is only available on localhost, preferably with a key
- Adds server master/child communication
Still a bit of a WIP, but I wanted people to be able to take a look at it.
Checklist:

First hack at qunstick

---

connection.js

Fixes # 1448
- If a file exists in the config directory 'header_hide_version', do not put the Haraka version number into the received headers.
Checklist:

Add ability to hide (Haraka/x.x.x) in headers.  Closes GH-1448.

---

Changes
package.json

Release v2.8.1

---

Changes
package.json

- ~~Start a N-week quiet period~~
- ~~Update [haraka-tld](https://github.com/haraka/haraka-tld)~~ (recently completed)

Changes for 2.8.3 and bump version

---

config.js
plugins.js
tests/installation/config/tls.ini
tests/plugins.js

Fixes #1471  .
- Fixes config loading and merging in installed mode
Checklist:

Fix plugin loading override when installed

---

Changes
package.json

Release 2.8.4

---

logger.js

Fixes #846 
- Simply log at logwarn when loglevel is invalid

Warn on invalid loglevel

---

plugins/queue/rabbitmq_amqplib.js

Fixes #1457 (potentially) .
- Basically adds better error handling. Should be a no-brainer.

Belt and braces for amqplib plugin

---

Changes
package.json

Release 2.8.5

---

Changes
package.json

Start the 2.8.6 release

---

docs/plugins/aliases.md
plugins/aliases.js
tests/plugins/aliases.js

- Allow aliases to be 'exploded' to an array of recipients in addition to a single recipient

Explode aliases

---

Changes
package.json

2.8.7 release

---

.travis.yml
plugins/watch/index.js

- when http.ini exists without a wss section, avoid crashing

handle no http.ini wss section properly

---

docs/plugins/rspamd.md
plugins/rspamd.js

Checklist:
- docs updated [YES]
- tests updated [NO: no tests for this plugin so far]
Feedback/incongruous demands/etc welcome.

Rspamd: support for soft rejections, adding/removing headers & DKIM

---

docs/Outbound.md
outbound.js
timer_queue.js

A few attempts to fix darkpixel's problems with outbound.

Outbound pool bugfix

---

plugins/dkim_sign.js

Fixes #1557
- Don't put the private key in the logs, duh!

Don't put private key in logs

---

smtp_client.js

This is @jjshoe's #1555 PR with the typo fixed.
closes #1555

import abandoned #1555

---

config/outbound.ini

pool_timeout setting example

---

plugins/dkim_sign.js

Fixes #1575 .
- adds defensive code to prevent exceptions when addr.host() is null or undefined

1575 lower case undefined

---

plugins/dkim_sign.js

Fixes intermittent TypeError in console, with no meaningful debug info.

Fix TypeError with null mail_from.host

---

plugins/spf.js

Fixes #1413  .
- Moves scope of logdebug to right place
Checklist:

Fix scope of logdebug

---

docs/plugins/attachment.md
plugins/attachment.js

- Fixes security vulnerability
- Adds wildcard filename support
- Adds allow_encrypted_archives option
Checklist:
- [ * ] docs updated

Attachment plugin updates

---

docs/plugins/aliases.md

Update docs for aliases plugin

---

docs/plugins/log.syslog.md

Fixes # .
- Just some additional text to make it more dummy proof.
Checklist:
Took me some time to figure this out.

Dummy proof manual

---

outbound.js

Fixes something discussed on #1535

Keep results if it exists

---

fsync_writestream.js
plugins/rate_limit.js
plugins/rspamd.js
plugins/watch/html/client.js
tests/config.js
tests/outbound_protocol/basic_outbound_trial_test.js
tests/outbound_protocol/outbound_bounce_net_errors.js
tests/outbound_protocol/outbound_bounce_rfc3464.js

- eslint no-unused-vars errors

fixup eslint no-unused-vars errors

---

Gruntfile.js

- update the grunt syntax for compat with newer versions of grunt-version-check module

update syntax for grunt-version-check

---

appveyor.yml
package.json

- drop support for node 0.10
Checklist:

Node 0.10 LTS support drops 10/1

---

Changes
package.json

Checklist:
- ~~Updated dependencies identified with `grunt versioncheck`~~
- ~~For major version releases:~~

Release v2.8.9

---

.eslintrc
.travis.yml
Gruntfile.js
bin/dkimverify
bin/haraka
bin/spf
config/log.elasticsearch.ini

Fixes # .
- use updated codecov syntax
- eslint: add missing before/after settings to keyword-spacing
- typo fix in config file doc
- lint updates in bin/*

 move noops from #1629 to this pr

---

bin/haraka

partly Fixes #1628 .
- when installing, don't overwrite host_list

do not overwrite host_list on install

---

dkim.js

Minor DKIM fix

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

- add node.js version to issue template

add node.js version to issue template

---

server.js

- Tidy-up logging and make it consistent between cluster .vs. non-cluster mode
- Fix graceful exit when not running under cluster; it was always hitting the timeouts

Tidy-up graceful shutdown and fix for non-cluster mode

---

.travis.yml
bin/haraka
package.json

Fixes #1637 
* consistent with usage npm other plugins/repos
* fix for host_list overwrite

use standard npm script syntax for lint and tests

---

connection.js
plugins/auth/flat_file.js
plugins/bounce.js
plugins/connect.asn.js
plugins/connect.fcrdns.js
plugins/dnsbl.js
plugins/greylist.js
plugins/helo.checks.js
plugins/messagesniffer.js
plugins/rspamd.js
plugins/spf.js
tests/connection.js
tests/plugins/dnsbl.js
tests/plugins/helo.checks.js
tests/plugins/spf.js

Fixes #1631 
- set connect.remote.is_private boolean
- update plugins to check that connection property
Checklist:

connection.remote.is_private

---

.github/ISSUE_TEMPLATE.md

See also, comments in #1656 
- add a shell script to collect system info for report issues
- format the data in a markdown table
Haraka | Haraka.js — Version: 2.8.9
--- | :--- 
Node | v6.7.0
| OS | FreeBSD haraka 10.3-RELEASE-p7 FreeBSD 10.3-RELEASE-p7 #0: Thu Aug 11 18:38:15 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

system info table format for issue reporting

---

tls_socket.js

Fixes #1676. Just use the proper hook.
Checklist:
~~no need to update docs~~
~~no need to update tests~~

haraka/Haraka#1676: make STARTTLS work again for server

---

Changes
package.json

Fixes #1653 
- update package.json
- update Changes

version bump and Changes update

---

docs/plugins/rcpt_to.routes.md

Massively small commit, but the bad formatting on the page has been annoying me.  ;)

Fix bad formatting in rcpt_to.routes plugin doc

---

docs/Plugins.md
plugins.js

rename core_require to haraka_require

---

config/karma.ini
tests/plugins/karma.js

- add .top TLD scoring
- add tests for check_spammy_tld
Checklist:

karma improvements

---

tests/outbound_protocol.js

- use cross-platform compatible file paths (vs unix-y paths)

replace / path seperators

---

.travis.yml
appveyor.yml
logger.js
package.json
tests/logger.js
tests/spf.js

Fixes #1712 
- require the latest node v4
Checklist:

Require node4

---

config/tls.ini
docs/plugins/tls.md
package.json
plugins/tls.js
tls_socket.js

Adds support for OCSP Stapling in the Server (Fixes #1723), reworked and rebased #1673.
Checklist:

Implement OCSP Stapling (#1723)

---

Changes

update release date

---

outbound.js

Swap lines to avoid clobbering response array

---

plugins/redis.js

redis: add redis_subscribe_pattern() to enable watch to subscribe once for every connection vs subscribing anew for every connection

redis: add redis_subscribe_pattern()

---

plugins/log.elasticsearch.js

Fix ElasticSearch index creation to use UTC dates

---

config/tls.ini

Checklist:
-  ~~tests updated~~

fix syntax of example dhparam

---

plugins/data.uribl.js
tls_socket.js

Should fix the stack trace below:
[CRIT] [3893B21C-D882-4263-BA38-A3C9378F9A92] [core] Plugin tls failed: TypeError: log.logerr is not a function
at pluggableStream.socket.upgrade (/app/haraka/tls_socket.js:260:29)

typo: logerr -> logerror

---

http/Gruntfile.js
plugins/graph.js
plugins/log.elasticsearch.js
tests/plugins/data.headers.js
tests/plugins/greylist.js
tests/result_store.js

(long since replaced by eslint)

remove the last vestigas of jshint

---

Changes
package.json

release 2.8.13

---

outbound.js
tests/outbound.js
tests/outbound_protocol/basic_outbound_trial_test.js

Fixes #1611 (hopefully)
- Changes the way we deal with FIN and some other minor issues
Checklist:

Issue 1611 v2

---

Plugins.md

- formats plugins into table
- moves URLs to footer
- adds plugin synopsis

Plugins as table

---

outbound.js

update logger calls to avoid CRITs

---

outbound.js

fix generic-pool factory creation

---

outbound.js

Fix outbound logger

---

plugins/dkim_verify.js

Emit only the current result (inside the iterator) instead of the top level one several times.

emit _the_ result, not all of them

---

config/attachment.filename.regex

block js attachments

---

Plugins.md

Plugins: add mongodb & Install instructions

---

plugins/auth/auth_proxy.js

identified by [smfreegard](https://github.com/haraka/Haraka/commit/c41422c81f655df07ab11658f1c1b02932045bb3)

auth_proxy: repair continuations

---

outbound.js
package.json
plugins/tls.js
smtp_client.js
tests/outbound.js

Fixes #1691
- use net_utils.tls_ini_section_with_defaults
- update min node ver to 4.7.3 (security)
Checklist:

use tls_ini_section_with_defaults

---

docs/plugins/relay.md

Fixes #
- Removing typo from 'relay.md'
Checklist:
- [*] docs updated

Removing typo from 'relay.md'

---

connection.js
plugins/attachment.js

Fixes #1410
- Couple of small fixes for early talking QUITers
Checklist:

Fix for issue #1410

---

plugins/auth/auth_proxy.js

Fix: https://github.com/haraka/Haraka/issues/1893

fixed auth_proxy socket error

---

smtp_client.js

Implement the missing upgrade method on SMTPClient.

---

plugins/helo.checks.js

make sure list_re is defined before access

---

bin/haraka

Fixes #1895
- Fixes logic error on Windows mentioned in #1895 
Tested that it doesn't break Linux.
I don't have a Windows box available.  Can someone else test and verify on Windows?

Check error code instead of number.  Fixes GH-1895.

---

outbound/client_pool.js
outbound/hmail.js
outbound/index.js
outbound/queue.js
outbound/tls.js

This just normalizes where the code was before the split code was merged. I think this is the only change it missed.

Bring client pool up to where we were before split

---

plugins/dkim_sign.js

Fixes #1918
- Fix path parsing bug on Windows platform

Fix path parsing bug on Windows platform

---

outbound/client_pool.js
outbound/hmail.js

Fixes #1853 
- Unset writable flag when FIN is sent
- Hopefully this prevents socket.destroy() from attempting to write
Checklist:

Attempt to add some belt and braces around FIN

---

config/outbound.ini
docs/Outbound.md
outbound/client_pool.js
outbound/config.js
outbound/hmail.js
outbound/index.js
outbound/queue.js

- Allows the outbound pooling code to be disabled and switch back to the old QUIT behaviour
- 
- 
Checklist:

Allow outbound pools to be disabled

---

outbound/queue.js

Fixes #1858 
- Call callback in setImmediate instead
Checklist:

Don't blow the stack on qstat

---

TODO

Clear off some done tasks

---

outbound/client_pool.js

Fixes #1936
- Check pool exists before deleting
Checklist:

Check pool exists before delete

---

server.js

Fixes #1933 
- Implement the cluster message support for various nodes here: https://nodejs.org/api/cluster.html#cluster_event_message_1
Checklist:

Fix cluster messaging for node v6+

---

outbound/hmail.js
outbound/index.js
outbound/qfile.js

Fixes #1942
- Refactor platformDOT variable to qfile.js and export to index.js and hmail.js

Fix undefined variable platformDOT in hmail.js

---

server.js

Fix queue not loaded for single process

---

package.json

Bump haraka-results required version

---

outbound/hmail.js

Be consistent with todo.domain

---

docs/Plugins.md

Minor typo fix

---

server.js
tests/outbound_bounce_rfc3464.js

Fix unaquired socket errors in test suite

---

docs/Logging_API.md

Fix link redirection

---

README.md

Fixes #
- Fix greenkeeper badge
Checklist:

Fix greenkeeper badge

---

Plugins.md

Fixes #
- Adding accounting_files plugin
Checklist:

Adding accounting_files plugin

---

Plugins.md

Fixes #
- Adding vmta plugin
Checklist:

Adding vmta plugin

---

.travis.yml

This just adds v8 to travis.
Currently failing due to: https://github.com/nodejs/node/issues/13325
Edit: Newer bug report: https://github.com/nodejs/node/issues/13548

Add node v8

---

Plugins.md

import Plugins.md from v3 branch

---

plugins/access.js

Fixes #1987
- rebuild blacklist upon file change
- previously just added new entries
Checklist:

rebuild blacklist upon file change

---

smtp_client.js

Remove a couple of console.log's that were driving me crazy when debugging :)

Remove spurious logs

---

docs/plugins/relay.md

correct the config file name to relay.ini

---

configfile.js

avoid crashing Haraka when invalid YAML encountered

---

Changes
Changes.md
package.json

prep release 2.8.14

---

appveyor.yml
package.json
server.js

- remove optional dep vs-stun
- require version of haraka-net-utils that includes vs-stun as optional dep
- use windows compatible syntax for npm scripts

remove stun dep to haraka-net-utils

---

messagestream.js
package.json
plugins/dkim_verify.js
server.js
tests/config/auth_flat_file.ini
tests/config/plugins
tests/server.js

Fixes #1797
Changes in this PR:
- updates nodemailer from 2 to v4
- sends authenticated message from nodemailer
- rejects invalid auth
- DKIM validates signed nodemailer message
Checklist:

add integration tests

---

package.json
server.js

Fixes #
- Use forked daemon package, see here https://github.com/silverwind/droppy/issues/324

Fix for node8, use forked daemon package

---

server.js

Revert "Fix for node8, use forked daemon package"

---

plugins/rspamd.js

saves rspamd from doing the same evaluation

pass SPF evaluation to rspamd

---

.eslintrc.json
tests/fixtures/vm_harness.js
tests/smtp_client.js

* increases cross-platform portability

no-path-concat

---

config/plugins

update name of qmd plugin in config/plugins

---

Changes.md
logger.js
tests/logger.js

- Allows the default log level to actually work
Checklist:

Fix log level setting

---

outbound/hmail.js

This patch makes the release of the client back to the pool conditional on receiving an OK response to an RSET command and prevents a race condition between the socket being returned to the pool and the connection being reset.
Requires testing to make sure this doesn't introduce any other issues.

Potential fix for #1852

---

Changes.md
connection.js
docs/Connection.md
docs/Transaction.md
outbound/hmail.js
package.json
transaction.js

use [haraka-notes](https://github.com/haraka/haraka-notes)
fixes #2081 
Checklist:

add get/set to conn/txn.notes

---

outbound/hmail.js

depends on haraka/haraka-notes#1

notes needs get/set after JSON round trip

---

Changes.md
dkim.js

Fixes #1693
- Ensure that all callbacks are async
Checklist:

DKIM: Fix for #1693

---

Changes.md
package.json

- For major version releases:
Checklist:

release 2.8.15

---

dkim.js

dkim typo fix

---

Changes.md
plugins/dkim_verify.js
plugins/queue/smtp_forward.js

- a previous string literal update missed a `' +` in the string
Checklist:

dkim: fix formatting of auth results addition

---

.eslintrc.json
bin/haraka
bin/spf
dkim.js
mailheader.js
plugins/auth/auth_vpopmaild.js
plugins/greylist.js
tests/tls_socket.js
tls_socket.js

* and remove a few useless regex escapes #2074

lint: switch no-var from warn to error

---

.eslintrc.json

depends on haraka/haraka-eslint#13

remove eslint rules to plugin

---

Changes.md
plugins/data.headers.js
plugins/greylist.js
plugins/lookup_rdns.strict.js

Fixes #2112 
this is the mergeable changes in currently empty-but-probably-not-on-purpose #2112 identified by @lnedry

updated fcrdns plugin name passed to results

---

Changes.md
configfile.js
mailbody.js
plugins.js
plugins/attachment.js
plugins/prevent_credential_leaks.js
rfc1869.js
spf.js

fixes #2074
Checklist:
- ~~docs updated~~

remove useless escapes

---

Changes.md
package.json

Release 2.8.16

---

config/plugins

since it's now an optional dependency

Access off by default

---

plugins/auth/auth_ldap.js

Replaces string concatenation to template literals on  auth_ldap.js file
Fixes #2129 
- 
- 
Checklist:

 #2129 - Replaces string concatenation to template literals on  auth_ldap.js file

---

Changes.md
plugins/xclient.js

plugins/xclient:  Replace string concatenation for string template

---

connection.js

Add class Connection respective constructor following params, a static method for setupClient, setTls, set and get methods.
Fixes #
-  
- 
Checklist:
As the file have a lot of functions to convert and this is my first PR to this Repo, i'd prefer to open and ask for review and commit the changes as i work. (Think will turn easier to review too.)
Started working today, should finish the PR tomorrow.

Add class, constructor,setupClient,setTls,set,get

---

Changes.md
plugins/relay.js

plugins/relay: Replaces string concatenation for string template

---

Changes.md
plugins/profile.js

…rofile.js
- Replaced concatenated strings with template literals in the plugins/profile.js
Checklist:

Replace concatenated strings with template literals in plugins/profile

---

Changes.md
plugins/relay_acl.js

plugins/relay_acl: Replace string concatenation with string template

---

messagestream.js

Changes #2133
- ES6: Replace current classes with ES6 classes on message stream module
Checklist:

messagestream: changes styling for es6 declaration

---

connection.js

Add process_line, process_line, process_data, _process_data, respond, fail, disconnect, disconnect_respond, get_capabilities,  tran_uuid, reset_transaction, init_transaction, loop_responide, pause, resume, SMT Responses module.
Resuming #2166
Fixes #
- 
- 
Checklist:

Add process, transaction, SMT Response, respond..

---

plugins/greylist.js

Fixes #2129 
- Refactor plugin/greylist.js  to change all string concatenations to template literals.
- 
Checklist:

plugin/greylist.js replaces all string concaternation to template literals 

---

connection.js

Replaces string concatenation to template literals on connection.js file
Changes #2129 
- 
- 
Checklist:

#2129 - Replace all string concaternation with template literals on connection.js

---

host_pool.js

Changes #2129 
- Refactor host_pool.js to change all string concatenations to template literals.
Checklist:

replaces string concaternation with template literals on host_pool.js file

---

dkim.js
mailbody.js

Fixes #2133 
- Convert the current classes in mailbody module to ES6
Checklist:

mailbody: converted to class to ES6

---

Changes.md
smtp_client.js

Addresses #2129
- template literals in smtp_client.js
Checklist:

Template strings

---

attachment_stream.js

updates #2133 
- attachment_stream: convert to ES6 classes
Checklist:

convert attachment_stream to ES6 classes

---

chunkemitter.js

Updates #2133 
- convert ChunkEmitter to ES6 class

Convert chunkemitter to ES6 class

---

smtp_client.js

Convert smtp_client to ES6 class

---

dkim.js

- Replace all string concatenations with template literals in `/dkim.js`.
- updates #2129

Change string concation to template literals

---

Changes.md

- Update `Changes.md` by adding `dkim.js` to the list
- Reference: #2216  
Checklist:

Add dkim.js to changes.md

---

connection.js

Fixing incorrect RCPT TO reply message

250 recipient <...> denied

---

outbound/timer_queue.js
plugins/dkim_sign.js
tests/outbound/index.js

Fixes #2133
- outbound/timer_queue class replaced with es6 class
- unit tests added
Checklist:

Updated timer_queue to es6 class and added unit tests.

---

plugins.js

updates #2133
- Updated plugins.js to an ES6 class
Checklist:

Updated plugins.js to an ES6 class

---

connection.js

Updates #2075
- Updated connection.js regex result to use destructuring assignment

Using ES6 destructuring on regex exec result

---

dkim.js

Es6 destructuring assignment in dkim.js

---

outbound/todo.js

outbound/todo: update to es6 classes

---

plugins.js

updates #2129
closes #2217 
- Replace string concatenations with template literals
- 
Checklist:

Use template literals in plugins.js

---

host_pool.js

updates #2129 
- Use template literals in host_pool.js
Checklist:

Use template literals in host_pool.js

---

dsn.js

dsn.js update to es6 classes

---

plugins/data.uribl.js

….
Part of #2133
-  Replace string concatenations with template literals in plugins/data.uribl.js
- 
Checklist:

Replace string concatenations with template literals in plugins/data.uribl.js

---

tests/smtp_client/auth.js
tests/smtp_client/basic.js

Fixes #2129 
- Replace string concatenations with template literals
Checklist:
- [-] docs updated
- [-] tests updated
- [-] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

auth.js: Replace string concatenations with template literals

---

plugins/attachment.js

Refactor attachment.js with ES6 features, including
- Replace string concatenations with template literals 
- Arrow functions
- Destructuring

Refactor attachment.js with ES6 features

---

plugins/backscatterer.js

Migrating to ES6 string literal.
updates #2129

Converting plugins/backscatterer.js to ES6

---

plugins/delay_deny.js

Migrating to ES6 string literals.
updates #2250

Converting delay_deny to ES6

---

plugins/connect.rdns_access.js

Migrating to ES6 string literals.
Fixes #2250;

Converting connect.rdns_access to ES6

---

plugins/data.headers.js

Migrating to ES6 String Literals
Fixes #2250

Converting data.headers to ES6

---

dsn.js

Fixes #2129 
- Use template literals in dsn.js
Checklist:

Use template literals in dsn.js

---

logger.js

Fixes #2129 
- Use template literals in logger.js
Checklist:

Use template literals in logger.js

---

logger.js

Fix of error introduced in last commit of template literars at logger.js

Fix of "[core] [NOTICE] - logobj.message"

---

plugins.js

Removed trailing spaces

---

plugins/spf.js

updates #2129 
- This PR replaces string concatenations with template literals in plugins/spf.js
Checklist:

Replaces concatenations with template literals in plugins/spf.js

---

outbound/hmail.js

- encapsulate the streaming logic into  _stream_bytes_from
- with some safety rails

Hmail refactor

---

bin/haraka

closes haraka/haraka-plugin-p0f#5

in haraka plugin test mode, add server.notes

---

Changes.md
connection.js
tests/connection.js

- reduce duplicated code
- replace string constructed by array with template literal
- define _uuid outside the while loop
Checklist:

conn: define this.local.info

---

Changes.md
plugins/queue/quarantine.js

quarantine: consolidate 2x hook_init_master()

---

mailbody.js

Change severity of iconv conversion failure

---

outbound/client_pool.js

Fixes #
- Fix outbound pooling
Checklist:

Fix outbound pools

---

Plugins.md
docs/Plugins.md

- add / update doc/Plugins
- add SRS plugin to Plugin registry

update plugins documentation

---

http/package.json

The existing version of jquery has vulnerabilities

update jquery version

---

outbound/qfile.js
tests/outbound/qfile.js

- fixes #2225
- also perform replacements on passed in host values
- add outbound/qfile tests

replace _ chars in hostnames with code points

---

smtp_client.js

- fixes #2312
- arrow functions

add this.removeAllListeners('connection-error')

---

outbound/hmail.js

Fixes #
- Fix crashing on RSET
- 
Checklist:

Fix crashing on RSET

---

package.json
plugins/data.headers.js

Prevent data headers crit fail

---

connection.js
transaction.js

Warn on max_header_lines

---

connection.js

- error introduced in #2331 
- uncovered working on #2336

fix undefined max_lines in log message

---

Changes.md
package.json

updates for 2.8.17 release

---

plugins/queue/qmail-queue.js

fix crash when client disconnects during qmail-queue

---

config/dkim/dkim_key_gen.sh

+security
Maybe Changes.md does not need to be updated

Shell nicery for dkim_key_gen.sh

---

Changes.md
package.json

I was motivated in https://github.com/haraka/Haraka/pull/2361 to get a release going, so here we go ;)

updates for 2.8.18 release

---

Changes.md
plugins/queue/qmail-queue.js

fix crash bug on vanishing qmail-queue clients

---

Changes.md
docs/plugins/process_title.md
plugins/process_title.js

Add total recipients, average number of recipients per message, recipients/sec current/average/max and average number of messages per connection.
`````
Haraka (master) cn=11148 cc=1082 cps=21/25.24/79 rcpts=144950/1.84 rps=518/328.18/586 msgs=78815/7.07 mps=302/178.44/329 out=0/0/0 respawn=0 
\_ Haraka (worker) cn=1646 cc=140 cps=5/3.73/17 rcpts=20310/1.86 rps=75/46.04/102 msgs=10938/6.65 mps=42/24.8/56 out=0/0/0 
\_ Haraka (worker) cn=1563 cc=168 cps=3/3.54/18 rcpts=19844/1.87 rps=78/45/96 msgs=10627/6.8 mps=49/24.1/53 out=0/0/0 
\_ Haraka (worker) cn=1852 cc=172 cps=3/4.2/16 rcpts=26278/2.03 rps=93/59.56/114 msgs=12938/6.99 mps=40/29.33/65 out=0/0/0 
\_ Haraka (worker) cn=1704 cc=187 cps=5/3.86/14 rcpts=23688/1.84 rps=93/53.7/125 msgs=12886/7.56 mps=64/29.21/66 out=0/0/0 
\_ Haraka …
```

process_title plugin improvements

---

plugins/xclient.js

Adds support for DESTADDR and DESTPORT options in the XCLIENT plugin.

xclient: Add DESTADDR and DESTPORT

---

Changes.md
connection.js

Revert deconstruction for SMTP commands

---

plugins/max_unrecognized_commands.js

fixes haraka/haraka-plugin-limit#16

deprecate plugins/max_unrecognized_commands in favor of limit

---

.travis.yml
appveyor.yml
tests/messagestream.js

Message stream test

---

attachment_stream.js

attstream: return self so that we can stack pipe() calls

---

package.json

Release 2.8.19

---

plugins/tls.js

Fixes #2455
- removed invalid argument from load_tls_ini which prevents properly load defaults due change at #2414 https://github.com/haraka/Haraka/pull/2414/files#diff-7b009c1421c1a91ef0875d92e1159e1aR259

Removed invalid opt from load_tls_ini()

---

plugins/data.headers.js
tests/messagestream.js
tests/plugins/clamd.js

fixes #2449
- check defined-ness of hdr_address *after* try/catch
Checklist:

check defined-ness of hdr_address *after* try/catch

---

Changes.md
package.json
plugins/tls.js

Release 2.8.20

---

plugins/tls.js

Add tls_socket.load_tls_ini() to tls.register()

---

outbound/tls.js

Fixes #2471 
* skip tls_nogo when redis is undefined
* fix config loading callback

skip when redis is undefined

---

outbound/hmail.js
outbound/queue.js
outbound/tls.js
tests/outbound/index.js

Fixes #2471 (although already fixed)
- Change outbound/tls into a class
Checklist:

Change outbound/tls to a class

---

server.js

Fixes #2473
- Fix the logic to return before running an invalid command
Checklist:

Don't die on invalid commands

---

outbound/hmail.js
outbound/tls.js
tests/outbound/index.js

Fixes #2483
- refactor outbound/hmail.process_ehlo_data

refactor outbound/hmail.process_ehlo_data()

---

Changes.md
messagestream.js
package.json
transaction.js

- transaction: flow & style improvements
- transaction: improve whitespace and comments
- messagestream: rename config => cfg (for consistency)
- update Changes.md
- bump Haraka version
Checklist:

release Haraka 2.8.21

---

outbound/tls.js

Fixes #2491 
- add .name to outbound tls
Checklist:

Add .name to outbound tls for logs

---

Plugins.md
docs/plugins/auth/flat_file.md

Fixes #2379
- Added reference to encrypted file authentication
Checklist:

Added hint to encrypted file authentication

---

Changes.md
connection.js

Fixes #2528
removing huge penalty per email line
Checklist:

move max_mime_parts config load to connection init

---

outbound/tls.js

ob/tls: more concise flow control
Checklist:

ob/tls: use obtls (vs plugin) for "this" name

---

docs/plugins/relay.md

relay: update port 465 doc

---

Changes.md
package.json

release 2.8.22

---

.gitignore
.travis.yml
Changes.md
package.json

tighten Haraka pattern in .gitignore

---

docs/Outbound.md

Fix typo on Outbound.md

---

Dockerfile

Fixes #2550 
- Updated Dockerfile to use Node 10.x
- Added comment to top of file noting this is user-contributed.

Updated to node 10.x - fixes #2550

---

outbound/hmail.js

handle remote MTA that does not RSET

---

Changes.md
outbound/queue.js

- adding missing callback 
Checklist:

Add missing callback when listing queue and empty directory

---

docs/plugins/clamd.md
docs/plugins/spamassassin.md
plugins/spamassassin.js

- Update SpamAssassin plugin docs to have check flags
- check flags are defaulted to true
Checklist:

Fixes related to Check flags

---

config/smtp_forward.ini
config/smtp_proxy.ini
plugins/queue/smtp_forward.js
plugins/queue/smtp_proxy.js

fixes #1472
- queue/smtp_*: add v3 upgrade notice and config setting
- es6 & style updates
Checklist:

queue/smtp_*: add v3 upgrade notice and config setting

---

outbound/index.js
outbound/queue.js

Fixes #2591 
- mainly simplify load_queue_files and repeated code moved into multiple functions
- creted _add_file, read_parts, delete_dot_files, and rename_to_actual_pid
I've tested code in cluster/non-cluster mode
Checklist:

queue.js refactoring

---

smtp_client.js

smtp_client: destroy when connection gets conn timeout error

---

outbound/client_pool.js

Fixes #2602 
@shurli commits to resolve #2602
- on error and timeout, remove listeners and destroy conn.
Checklist:

on error and timeout, remove listeners and destroy conn.

---

server.js

make inactivity timout match docs

---

contrib/plugin2npm.sh

It's a Work In Progress, as I continue to adjust it each time I convert a haraka plugin to a module. It may never be "finished" but it's high time to get it under version control.

import plugin2npm.sh

---

Changes.md
package.json

- bump version for release
- I've been holding off on this, hoping to include a fix for #2600 but have been shy a round tuit
Checklist:

bump version, update CHANGES

---

transaction.js

to make it much easier to read
- trans: assign conditions to named vars
- trans: use `for .. of` to iterate array instead of forEach()

trans: assign conditions to named vars

---

transaction.js

trans: restore missing this

---

.travis.yml

- probably worked in node 12.2
- broken in 12.3 due to [this bug](https://github.com/nodejs/node/pull/27804)
- will probably work again after 12.3.1

node: remove 6, add 11,12

---

Changes.md
mailheader.js
tests/mailheader.js

Fixes #2641
- mailheader: add test for remove()
- mailheader: do not remove partial matches from header_list
Checklist:

mailheader: do not remove partial matches from header_list

---

plugins/toobusy.js

- changed nonexistent connect_pre hook to connect

replaced nonexistent hook

---

plugins/dnswl.js

- Replaced string concatenations with template literals

Replace string concatenations with template literals

---

outbound/hmail.js

Fixes #2683 (thanks @fredrikdev)
- Watch for timeout events
Checklist:

Watch for socket timeouts

---

.travis.yml

travis: drop node 11 testing

---

Changes.md
mailheader.js
tests/mailheader.js

Fixes #2702 
- strip whitespace between encode words
Checklist:

strip whitespace between encode words

---

messagestream.js

Fixes # Replaced concatenated strings with template literals

Replace concatenated strings with template literals

---

outbound/hmail.js

Replaced concatenated strings with template literals.

Replace concatenated strings with template literals.

---

.github/workflows/coveralls.yml
.gitignore
package.json

- downgrade nodemailer, fixes #2712

coverage: replace istanbul with nyc

---

Changes.md
config/connection_close_message
connection.js
docs/CoreConfig.md

- Add ability to modify Close connection message
Checklist:

Add connection close message

---

contrib/haraka.service

corrected spelling of smtp.ini

Fix spelling error

---

Changes.md
outbound/client_pool.js
outbound/config.js
outbound/hmail.js
outbound/index.js
outbound/queue.js
tests/outbound_bounce_rfc3464.js

Some smartass decided to split outbound into pieces and forgot to code the config reload properly.
Checklist:

fix outbound config reload

---

connection.js
package.json
plugins/attachment.js
plugins/rcpt_to.in_host_list.js

'tests' is now excluded by default

nyc: remove -x tests from invocation

---

tls_socket.js

maybe a fix for #2743, cant hurt, could benefit from further investigation
might also help #2807

add listener for secureConnect, per #2743

---

messagestream.js

Fixed #2839 
-  added total_buffered variable to keep track of total size of chunks 
-  enable spool based on the total_buffered value

Haraka spool issue fix

---

messagestream.js

messagestream: whitespace

---

README.md

Invite users to Slack instead of IRC

---

config/smtp.ini
connection.js
transaction.js

proposed alternative to #2851
- add [headers] config section to smtp.ini 
- consolidate max_header_lines and max_received_count to same
Checklist:

config options for headers

---

Changes.md
outbound/mx_lookup.js
package.json
plugins/mail_from.is_resolvable.js
spf.js

fixes #2778
- resolveMX -> haraka-net-utils.get_mx with punycode support
Checklist:

replace resolveMX with nu.get_mx with punycode

---

config/log.ini

log.ini: add json to list of formats in config doc

---

outbound/hmail.js

- fix bounced_rcpt parameter passed to bounce hook

fix bounced_rcpt for bounce hook

---

Changes.md
connection.js

Make Received: header more RFC compliant

---

Changes.md
connection.js

- fix AR cleanup code so that it works as explained in the comment above
- beautify AR header output for improved human consumption
Checklist:

Fix `Authentication-Results` header cleanup code.

---

connection.js

Fix barelf URL

---

plugins/queue/smtp_forward.js
plugins/queue/smtp_proxy.js

(backstory: I tried to bring in more async/await, found it was more invasive than I wanted, so reverted. almost.
related to #3033
Checklist:

fix: revert a call signature change

---

Changes.md
plugins/helo.checks.js

Fixes #3040
- remove multi check (run tests every time for HELO/EHLO)
Checklist:

helo: remove multi check

---

.github/workflows/ci-test.yml
.github/workflows/coveralls.yml
.github/workflows/lint.yml
Changes.md

enable windows 2022 testing

---

messagestream.js
tests/transaction.js

Fix for https://github.com/haraka/Haraka/issues/3057
Fixes #
- 
- 
Checklist:

Fix for boundary marker corrupt issue

---

Changes.md
package.json

this fixes an issue where banner was inserted into text attachments
Checklist:

bump haraka-email-message to 1.1.0

---

docs/CoreConfig.md

Checklist:
Matches the code in https://github.com/haraka/Haraka/blob/master/server.js#L48

doc: default nodes value is 1 and not 0

---

plugins/dns_list_base.js

Fixes #3106 
Check for 127.255.255.x error values.
Checklist:

A records matching 127.255.255.xxx are query errors, not block listings.

---

README.md
package.json

- [doc(README): remove broken slack URL](https://github.com/haraka/Haraka/commit/b92d82c7aa167c9c8236b9fcd974fb4e4295cd04)

dep(spf): bump version

---

endpoint.js
host_pool.js
outbound/config.js
outbound/index.js
package.json

- refactor: use includes instead of indexOf test
- refactor: push operator into assignment
- refactor: merge object destructuring assignments

P42 refactor: includes, obj destructuring, push operator

---

dkim.js

fix: dkim_verify fails to find record (#3148)

---

docs/plugins/clamd.md

Fixed spelling error

---

Changes.md
outbound/tls.js

Rename redis command setex to setEx #3174

---

Changes.md
connection.js
package.json
plugins/dns_list_base.js
tests/plugins/dns_list_base.js

- connection: handle dns.reverse invalid throws
- chore: update a few deps in package.json
- dns_list_base: avoid test failure when public DNS used
Checklist:

Node v20 test fix

---

Changes.md
plugins/helo.checks.js
tests/config/helo.checks.ini
tests/plugins/helo.checks.js

test(helo.checks): add regression tests for #3191

---

Changes.md
package.json

Fixes #
Fixes issue in SPF plugin where skip configuration was not being set correctly
Checklist:
- [X ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

Bump haraka-plugin-spf to 1.2.1

---

plugins/clamd.js

Added  X-Haraka-Virus header so scoring can happen.

Add missing X-Haraka-Virus header

---

docs/Plugins.md

- preview [in the branch](https://github.com/haraka/Haraka/blob/docs-plugins/docs/Plugins.md)

doc(Plugin): improve GHFM formatting

---

Changes.md
outbound/index.js

outbound: replace empty Message-ID header

---

Changes.md
plugins/helo.checks.js
tests/plugins/helo.checks.js

helo.checks: declare literal_mismatch boolean

---

Changes.md
connection.js

when setting remote.is_private, support IPv6

---

docs/Plugins.md

doc: don't register a hook twice in example

---

package.json

move redis into dependencies, since redis plugin is a dep

---

Changes.md
connection.js
tests/connection.js

fixes haraka/haraka-dsn#16
- add test case from haraka/haraka-dsn#16
Checklist:

add connection response tests

---

Changes.md
bin/haraka
config/smtp.ini
connection.js
haraka.js
package.json
server.js

which includes the git commit ID, when Haraka is running from a git repo. 
```
❯ ./bin/haraka -v
Haraka.js — Version: 3.0.3/e627f3b9
```
and
`Starting up Haraka version 3.0.3/75fc8afc`
- remove last vestiges of header_hide_version (long ago renamed)
- server.js: use the local logger methods
Checklist:

get Haraka version from utils.getVersion (3x)

---

connection.js

reduce severity of data after disconnect

---

docs/Transaction.md

doc(Transaction): updated to match code

---

Changes.md
docs/Outbound.md

Checklist:
See a preview [here](https://github.com/haraka/Haraka/blob/outbound-docs/docs/Outbound.md#fn1)

doc(Outbound): improve GHFM formatting

---

outbound/hmail.js

o/hmail: fix transaction notes setting bind_helo

---

tls_socket.js

fix: TLS SNI wasn't working due to missing context

---

Changes.md

Corrected spelling for function name.
Changed net_utils.HarkaMx to net_utils.HarakaMx

Spelling correction in Changes.md

---

Changes.md
bin/haraka

fix: install Plugins.md when haraka -i

---

Changes.md
plugins/queue/lmtp.js

Fixes #3403
- revert a refactoring error
Checklist:

fix: revert refactoring error, fixes #3403

---

package.json

deps: bump various to latest

---

.github/workflows/release-branch.yml

push to a 'release' branch with package-lock.json

---

.github/workflows/release-branch.yml
plugins/status.js
plugins/tls.js

chore: add -f to git ci for package-lock.json
